
BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBBBBB
XXXXXXX
XX XXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXX XX
XXXX X
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXXXX
  XXXXXXXXXXX XXXXXX
  XXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXXX XXXXXX XXXX XXXXXX XXXXXXXXXXX
X

XX XXXXXXXX XXXXXXXX XXXXXXXXXX XX
XXXXXXXXX X
  XXXXXXXXX XXXXXX
  XXXX XX XXXXX XX XXXXXX XXXXXX XXXXXXX XXXXXX
  XXXXXXXX XXX
  XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
  XXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
X

XX XXXXXXXX XXXX XXXXXXX XX
XXXXXXXXXXX X
  XXXXXXXXX XXXXXX
  XXXX XX XXXXX XX XXXXXX XXXXXX XXXXXXX XXXXXX
  XXXXXXXX XXX
  XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXX XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXX XXXX XXXXXXXXXXX XXXXX
  XXXXXXXXXXXXXXXX XXXX XXXXX
  XXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXXXX
X

XXXXXXXXXX XXXXXXXXXXX X
  XX X XXXXXXXX XXXX XXXXXXXXXX XXXXXXXXX X
  XXXX X XXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX X
X

XXXXXXXXXX XXXXXXXXX X
  XX X XXXXXXXXXX XXXXXXXXXXXX XXX X
  XXXX X XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX X
X

XX XXXXXXXX XXXXXXXXX XX
XXXXXXXXXX X
  XXXXXXXXX XXXXXX
  XXXX XX XXXXX XX XXXXXX XXXXXX XXXXXXX XXXXXX
  XXXXXXXX XXX
X

XXXXXXXXX X
  XXXXXXXXX XXXXXXXXX
  XXXXXX XXXX XXXXXXX XXXX
  XXXXXXXXXXX XXXXXXXX
  XXXXXXXXXXXXXX XXXX
  XXXXXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXXXX
X

XXXXXXXXXX XXXXX X
  XXX XXXX X XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX X
  XXX X XXXXXXXX XX X
  XXX X XXXXXXXX XX X
  XXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
X

XX XXXX XXXX XXXXXXXXX XX
XXXXXXXXXXX X
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXX XXXXXXXX XXX XXX XXXXX XXXXXX
  XXXXXXXXXXXXXX XXXXX
  XXXXXXXXXXX
    X X XXXX XXXX XXXXXXX XXXX XXXX XXXXX
    X X X XXX XXXXXXX XXXX XXXX XXXXX
    XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
  XXXXXXXX XXXXX
  XXXXXXX XXXX XXXXX
  XXXXXX XXXXXXXX
  XXXXXXXXXXXXXXXX XXXXXXXXXXX
  XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
  XXXXXXXXX XXXXXXXXX
  XXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXX X
  XXXXXXXX XXX
  XXXXXXXXX XXXXXXXXX
  XXXX XX XXXXX XX XXXXXX XX XXXXXXX XX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXX XXXX XXXX XXXXXXXXXXX XXXXX
  XXXXXXXXXX XXXXXXXXX XX XXXXXXXXXXX XXXXXXXXX
X

XXXXXXXXXX XXXXXXXXX X
  XX X XXXXXXXXXX XXXXXXXXXXXXXXXXXX X
  XXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXX X
X

XX XXXXXXXX XXXX XXXXXX XX
XXXXXXXXXXXX X
  XXXXXX XXXXXXX XXXXXXXXXXX
  XXXXXXXXXXXX XXXXX
  XXXXXXXXXXXXXXX XXXX
  XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
  XXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXXX
  XXXXXXXXXXXXXX XXXXXXX
  XXXXXXXX XXXXXX
  XXXXXXXXX XXXXXXXXX
X

XXXXXXXXXXXXXXXXXXX X
  XXXXXXXX XXX
  XXXXXXXXX XXXXXXXXX
  XXXXXXX XXXXX XXXXX XX
  XXXXXX XXXXX XXXXXXX XXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
X

XX XXXXXXXX XXXX XXXXXX XX
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX X
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXX XXX XXXXXXXX XXX XXX XXXX XXXXX XXXXXXXXXXX
  XXXXXX XXXXXXX XXXXXXXXXXX
  XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
  XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
  XXXXXXXXXXXX XXXXXX XXXX XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
  XXXXXXXXXX XXXXXX XXXXXXXXXXX
  XXXXXXXX XXXXXX XXXX XXXXXXXXXXX
  XXXXXXXXXXX
    X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXX X X XXXX XXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
  XXXXXXXXXXX XXX XXXX XXXXX
  XXXXXX XXXX XXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXXXX XXXX XXXXXXXXXXX
  XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  XXXXXXXXXXX
    X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXX X X XXXX XXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
  XXXXXXXXXX XXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
  XXXXXXXXXXX XXXXXXX
X

XX XXXXXXX XXXXXXXXXXX XXXX XX XXXXXXXX XX XXXXXXX XX
XXXXXXXXX X
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXX XXX XXXXXXXX XXX XXX XXXX XXXXX XXXXXXXXXXX
  XXXXXX XXXXXXX XXXXXXXXXXX
  XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
  XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
  XXXXXXXXXXXX XXXXXX XXXX XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
  XXXXXXXXXX XXXXXX XXXXXXXXXXX
  XXXXXXXX XXXXXX XXXX XXXXXXXXXXX
  XXXXXXXXXXX
    X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXX X X XXXX XXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
  XXXXXXXXXXX XXX XXXX XXXX XXXXXXXXXXX
  XXXXXX XXXX XXXXXXXXXXX
X

XXXXXXXXXXXXXXX X
  XXXXXXXX XXXX XXXXXXXXXXX
  XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  XXXXXXXXXXX
    X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXX X X XXXX XXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
  XXXXXXXXXX XXXXXXXXXXXX
X

XXXXXXXXX XXXXXX X
  XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  XXXXXX XXXXXXX XXXXXXXXXXX
  XXXXXXXX XXXXXX XXXXXXXXXXX
  XXXXXXX XXXX XXXXXXXXXXX
X

XX XXXXXXX XX XXXXXXX XX XX XXXXXXXX XX
XXXXXXXXXXXXXX X
  XXXXXXXX XXXXXXXXXXXXX
  XXXXXX XXXXX
  XXXXXXX XXXXX
  XXXXXXXXXXXXXX XXXX
  XXXXXXXXXXXXX XXXX
  XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
  XXXXXXXXXXXXXXX XXXXXXX
X

XX XXXXXXXX XXXXXXX XX
XXXXXXXXXX X
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
  XXXXXX XXXXXXXX
  XXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXXX XXXXXX XXXXXXXXXXX
  XXXXXXXXXX XXXXXXX
  XXXXXXXXXXXX XXXXX
  XXXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXX
    X X XXXX XXXXXXX XXXX XXXX XXXXX
    X XXX XXXX XXXXXXX XX XX XXXXX
  XXXXXXXX XXXX XXXXX
  XXXXXXXXXXX XXX XXXX XXXXX
  XXXXXXX XXXXX
  XXXXXXXXXXXXXXX XXXXXXXXXX
  XXXXXXXXXXXXXXX XXXX
  XXXXXXXXX XXXXXXXXX
  XXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXX X
  XXXXXXXX XXX
  XXXXXXXXX XXXXXXXXX
  XXXX XX XXXXX XXXXXX
  XXXXXX XXXXX XXXXXXX XXXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
  XXXXXXXXXXX XXXX XXXXX
X

XXXXXXXXXXXXXXXX X
  XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXXXXXX
    X X XXXX XXXXXXX XXXX XXXX XXXXX
    X XXXX XXXX XXXXXXX XX XX XXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXX X
  XXXXX XXXXX
X

XX XXXXXXXX XXXXX XX
XXXXXXXXXXXX X
  XXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXXX XXXXXX XXXXXXXXXXX
  XXXXXXXXXX XXXXXXX
  XXXXXX XXXXXXXX
  XXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXX XXXXX
  XXXXXXXXXXXX
    X X XXXX XXXXXXX XXXX XXXX XXXXX
    X X XXXX XXXXXXX XXXX XXXX XXXXX
    X X XXX XXXXX
  XXXXXXXXXXXXXXX XXXXXX
  XXXXXXXXXX XXXXXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
X

XXXXXXXXXX XXXXXXXXXX X
  XX X XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX X X XXX XXXXX X
  XXXX X XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXX X X XXXX XXXXXXX XXXX XXXX XXXXX X X XXX XXXXX X
X

XX XXXXX XXXXXXX XX
XXXXXXXXXXXX X
  XXXXXXXXXXX XXXXXXXXX XX XX XXXXX
  XXXXXXX XXX XXXXX XXXXXXXXX XXX XX XXXXX
  XXXXXXXXXXXXXX XXXXX
  XXXXXXXX XXXXXXX
  XXXXXXXXXXXXXX XXXXX
  XXXXXXXXXXX X X XXXX XXXXXXXXX XXX XX XXXXX
X

XX XXXXX XXXXXXXXXX XX
XXXXXXXXXXXXXXXX X
  XXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXXXX XXX
  XXXXXXXXX XXXXXXXXX
  XXXX XXXXX XXXXX XXXXX XXXXXX XXXXX XXXXXXX XXXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX XXXXXXXX XXXX XXXX XXXXX XXXXXXXXX XXX XXXX XXXXXX
  XXXXXXXXXXXXXX XXXXXXX
  XXXXXXXX XXX
  XXXXXXXX XX
  XXXXXXXXXXX XXXXXXX XXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXXXX XX
X

XX XXXX XXXXXXX XX
XXXXXXXXXXXXX X
  XXXXXX XXXXX
  XXXXXXX XXXXX
  XXXXXXXXXXXXXX XXXX
  XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
  XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
X

XX XXXXX XXXX XXXXXXX XX
XXXXXXXXXXX X
  XXXXXXXXXXX XXXXXXX XX XX XXXXX
  XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
  XXXXXXXXXXXXXX XXXX
  XXXXXXXX XXXX
  XXXXXXXXXXXXXX XXXXX
  XXXXXXXXXXXX XXXXXX XXXX XXXXXX XXXXXXXXXX
  XXXXXXXXXX XXXXXXX
  XXXXXX XXXXXXX XXXX XXXX XXXXX
X
XXXXXXXX

XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

XXXX XXXXXXXX XXXXXXXXXX XXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
  XXXX XXXXXXX XXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXX XXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
    BB BBBBBBBBB BB BBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX
    BBBB BBBBBBBBB BB BBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX
    BBBBB
  XXXXXX

  XXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX

  XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB

    BB BBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX XX XX XXXXXXXXXXXXXXXX
        BBB BBBBBB BBBBBB BB BBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBB BBBBB BB BBBBBB
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX
            BBBBBB
          XXXXXX
        BBBBBB
      XXXXXX
    BBBBB

    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
      XXXX XXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFFFFFFFFFF
      XXXXXX

      XXXX XXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFFFFFFFFFF
      XXXXXX

      XXXX XXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFFFFFFFFFF
      XXXXXX

      XXXX XXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFFFFFFFFFF
      XXXXXX

      XXXX XXXXXXXXX XXXXXX XX XXXXXX X XXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFFFFFFFFFF
      XXXXXX

      BB BBBBBBBBB BB BBBB
        XXXX XXXXXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
          FFFFFFFFFFFFFFFFFFFFFFF
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          FFFFFFFFFFFFFFFFFFFFFFF
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX
          FFFFFFFFFFFFFFFFFFFFFFF
        XXXXXX
      BBBB
        XXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          FFFFFFFFFFFFFFFFFFFFFFF
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          FFFFFFFFFFFFFFFFFFFFFFF
        XXXXXX
      BBBBB

      XXXX XXXXX XX XXXXXXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFFFFFFFFFF
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX
          BB BBBBBBBBB BB BBBB
            XXXXXX X XXXXX XX XXXXXXXX XXXX XXXXXXXXXXXXXXXXX
          BBBB
            XXXXXXXXXX XX XXXXX XXXX XXXXXXXXXXX X XXXX XXXXXXXXXXXXXXXXXXX
          BBBBB
        XXXXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        X XXXXXXX XXXXXXX
      XXXXXXXXX
    XXXXXX
  XXXXXXX
XXXXXX

XXXX XXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXX XXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
  XX XXXXXX XXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXXXXX

  XX XXXXXX XXXXX XXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXXXXXXXXXXXXX XX XXXXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXX X
      XXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXX XXXXXXXXX XXXXXXXXXX

      XX XXXXX XXXXXX XXX XXXX XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXX X XXXXX

      XXXXXXXXXXXX X
        XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXX XX X
            XX XXXXXXXXXXXXXX X
              XXXXX XXX XXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
            X
            XXXXXX XXXXXXXXXXXXXXXX
          XX
          XXXXXXXXXX XX X
            XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX

            XXXXXXXXXXXXXX XXX XX X
              XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXX XX XXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            X XXXX X
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX X XXXXXXXXXX
                XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XX XXXXXXXXX XX XXXXXXXXXXXXXXXXX X
                  XXXXXXXXXXXXXXX X XXXXX
                X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXX
            X
            XXXXXXXXXXXXXXXXXXXXX X XXXXXX
          XX
          XXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXX XXXXX XX XXXXXX XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXX XXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX X XXXXXX
          XXX
      X XXXX X
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX X XXXXXX
      X
    X

    XX XXXX XXXXXX XX XXXXXX XX XXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XX XXXXXX XXXXXX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
  X

  XX XXXXXX XXX XXXXXXXXXXXXX
  BB BBBBBBBBB BB BBBB
  XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXX X
      XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXX XXXX XXXXXXXXX XXXXXXXXXX

      XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX X XXXXX

      XXXXXXXXXXXX X
        XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
          XXXXXXXXXX XX X
            XXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXX

            XXXXXXXXXXXXXX XXX XX X
              XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXX
            X XXXX X
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX X XXXXXXXXXX
                XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XX XXXXXXXXX XX XXXXXXXXXXXXXXXXX X
                  XXXXXXXXXXXXXXX X XXXXX
                X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXX
            X
            XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
          XX
          XXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXX XXXXX XXXXXXX XXX XXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
          XXX
      X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX X XXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
      X
    X

    XXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
  X
  BBBBB

  XX XXXXXX XXXXX XXXXXXX
  XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXX X
    XX XXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX X X
      XXXXXXXX XXXXXXXXXXXXX
      XXXXXX XXXXX
      XXXXXXX XXXXX
      XXXXXXXXXXXXXX XXXX
      XXXXXXXXXXXX XXXXX
      XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
      XXXXXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXX XXXXX
    XX

    XX XXXXXXXX XXXXXXX XXXXXXX XXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXX XXXX XXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
      XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX X
        XX XXXXXXX XX XXXXXX XX XXXXX XXX XXXXX XX XX XXXXXX X XX XX XXXXXXXX XXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
      X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
      X
    X

    XX XXXXXXXXXX XXXXXXX XX XXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXX XXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
  X
XXX

XXXXXXXX XXXXXXXXXXXXXXXXX X
  XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXX X XXX

  XXXXXXX X X XX X X XXXXXXXXXXXXXX XXXX X
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXX X XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X X X XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X X X XX X XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X
X
XXXXXXXXX
BBBBBBBB
