BBBB BBBB
XXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXXXX gettext(u'Test Template Resolution') XXXXXXXX
XXXXXXX
XXXXXX
    XXXXX  gettext(u'Template Resolution Test') XXXXX
    XXXXXXXX XX X XXXXXXX XXXXXX
    XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
        XXXX gettext(u'Sistema de Resolución Funcionando') XXXXX
        XXXXXXX XXXXXXXX XXX XXXXXXX XXXXXXXXXXXX XXXXXX XX XXXXXXX XX XXXXXXXXXX XXXX X XXXXXXXXXXX
    XXXXXX
XXXXXXX
XXXXXXX
