BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBBB
XXXXXXX
  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
                X X X XXX XXXXXXX XXXX XXXX XXXXX
                XXXXX X XXX X XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXX XXXXXXXXXXXX X
    XXX XXXX X XXXXXXXX XXXX X
    XXX X XXXXXXXX XX X
  X

  XXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXX XXXXX
  X

  XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXX XX
    XXXXXXXXXX XXXXXX
  X

  XXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXX XXXXXX
    XXXXX XX
    XXXXXX XXXXXX
    XXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
    XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXX XXX XXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXX XXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
    XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
                XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XXXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
    XXXXXXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXX
  X

  XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX
    XXXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXX XX XX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXXX XX XX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
  X

  XXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXX XXXX
    XXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXXX XX
    XXXXXXXX XXX
    XXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX XXXXXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXX
  X

  XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXX XXXX
    X

    XXXXXXXXXXXXX X
      XXXXXXXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXXX X
      XXXXXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXX X
      XXXXXXXXXX XXXXX
      XXXXXXXXXX XXXXX
    X

    XXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXX XXXXXXX
    X
  X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXX gettext(u'Create Client') XXXXX

      XXXX XXXXXXXX XXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXX XXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXX XXXXXXXXXXXXXXXX
          XXXXXXXXX
        XXXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXXX XXXX
      XXXXXXXX XXXX
      XXXXXXX XXXXX XXXX
      XXXX XXXXXXX XXXXX
    XXXXXX

    XXXXX XXXXXXXXXXXXXX
      BBBBBBBBBB

      BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXXXBB BBBBBBBBBBBBB BB BBBBXXXX XXXXXXXBBBBXXXXXXX XX XX XXXXXXXXXXXBBBBBXXXXX

        XXXXXX
      BBBBB

      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'First Name') XXXXXXXXX
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFF FFFFFF FFFFF FFFFF FFF
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Last Name') XXXXXXXXX
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFF FFFFFF FFFF FFFFF FFF
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Email') XXXXXXXXX
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFF FFFFFF FFFFF FFFFFFFF FFF
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Phone') XXXXXXXXX
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFF FFFFFF FFFFF FFFFFFF FFF
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Address') XXXXXXXXX
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFF FFFFFF FFFFFFFF FFF
        XXXXXX
      XXXXXX

      BB BBBBBBBBB BB BBBB
        XXXX XXXXXX XXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'State') XXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'City') XXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Zip Code') XXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFF FFFFFF FFF FFFFF FFF
          XXXXXX
        XXXXXX

        XXXX XXXXXX XXXXX XXXXXXXXX XXXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Region') XXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'City') XXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
          XXXXXX
        XXXXXX
      BBBB
        XXXX XXXXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Region') XXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'City') XXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF
          XXXXXX
        XXXXXX

        XXXX XXXXXX XXX XXXXXXXXX XXXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'State') XXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'City') XXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Zip Code') XXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
          XXXXXX
        XXXXXX
      BBBBB

      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Save Client') XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXX
      XXXXXX
    XXXXXXX
  XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBB
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
  XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXX gettext(u'Select City') XXXXXXXXXXX

      XX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXX XXXXXXXXX XXXXXXXXXX

        XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
          XXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXX

            XX XXXXXXXXXXXX XXX XX X
              XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXX X XXX
              XXXXXXXXXXXXXXXXXX X X gettext(u'No cities available for this state') XX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX X
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX X XXXXXXXXXX
                XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XX XXXXXXXXX XX XXXXXXXXXXXXXXXXX X
                  XXXXXXXXXXXXXXX X XXXXX
                X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXX
            X

            XX XXXXXX XXX XXXX XXX XXXXX XXXXXX XX XXX XXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX X XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Add New City...') XX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX
          XXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXX XXXXXX XXXXX
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX X XXX
            XXXXXXXXXXXXXXXXXX X X gettext(u'Error loading cities') XX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX
      X
    X

    XX XXXXXX XXXXXXXX XX XX XXX XX XXXXXX XXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XX XXXXX XXXXXXXX XXXX XXXXXXX XX XX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XX XXXXX XXXXXXXX XXXX XXXXXXX XX XX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XX XXXXXXXXXXX XXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX
      X
    XXX
  X
XXX

XXXXXXXX XXXXXXXXXXXXXXXXXX X
  XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XX XXXXXX XXXXX XXXX
  XXXXX XXXXXXXXX X X
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXX XXXXXXXX XXXXX XXXXX XX XXXX XX XXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX XXXXXXX XXX XXXXX XXXXXXXX XXXXX XXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX
          XXX XXXXXXXXXXXXX XXXXXXXX XXXXXXX XX XXXXXXXXXX XXXXXX XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXXXX gettext(u'Add New City') XXXXX
          XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'Adding a new city to')  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX gettext(u'City Name') XXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX gettext(u'Enter city name') XX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX gettext(u'Zip Code (Optional)') XXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX gettext(u'Enter zip code') XX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXX XXX XXXX XXXXXXX gettext(u'Cancel') XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXX XXX XXXX XXXXX XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXXXX gettext(u'Save City') XXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XX

  XX XXX XXXXX XX XXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

  XX XXXXX XX XXXX XXXX XXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXX X
  XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXX X
    XXXXXXXXXXXXXXX
  X

  XX XXXXX XXXX XXXXXX XX XXXXX XXXXXX
  XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX
  X
X

XXXXXXXX XXXXXXXXXXXXX X
  XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XX XXXXXXXXXXXXXX X
    XXXXXXX gettext(u'Please enter a city name') XXX
    XXXXXXX
  X

  XX XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX gettext(u'Please select a state first') XXX
    XXXXXXX
  X

  XX XXXX XXXXXXX XXXXX
  XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Saving...') XX
  XXXXXXXXXXXXXXXXXXX X XXXXX

  XX XXXXXXX XXXX
  XXXXX XXXXXXXX X XXX XXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XX XXXX XXXX XXXXXXX
  XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX X
    XXXXXXX XXXXXXX
    XXXXX XXXXXXXXX
    XXXXXXXX X
      XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
  XX
  XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
  XXXXXXXXXX XX X
    XX XXXXXXXXXXXXXX X
      XX XXXXX XXXXX
      XXXXXXXXXXXXXXXXXXXX

      XX XXXXXX XXXXXX XXX XXX XXXXXXX XXXXX
      XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX X
        XX XXXXXX XXXXXX XXX XXXXXX XXX XXX XXX
        XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXX gettext(u'Select City') XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
              XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXX X XXXXXXXXXX
              XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
              XX XXXXXXXXXX XX XXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXX X XXXXX
              X
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX

            XX XXX XXXX XXX XXXXX XXXXXX XXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX X XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Add New City...') XX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX
      X

      XX XXXX XXXXXXX XXXXXXX
      XXXXXXX gettext(u'City added successfully!') XXX
    X XXXX X
      XXXXXXX gettext(u'Error adding city') X X X XXXXXXXXXXX XX X gettext(u'Unknown error') XXXX
    X
  XX
  XXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXX gettext(u'Error adding city') X X X XXXXXXXXXXXXXXX
  XX
  XXXXXXXXXXX XX X
    XX XXXXXXX XXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX X XXXXXX
  XXX
X
XXXXXXXXX
BBBBBBBB
