BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBB

BBBBB BBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX X XXXXXXX XXXXX XX
    XXXXXXXXXXX X XXXXXX X XXXXXX XXXXXXXXXXXXX X XX
    XXXXXXXXXX X
      XXXXXXX X XXXXXX XXX XX
      XXXXXX X XXXXXX XXXXXXXXX XX
      XXXXX X XXXXXX X XX
      XXXXX X XXXXXXX XXXXX XXXXXX XXX XX
      XXXXXX X XXXXXXX XXXXX XXXXXX XXXXXXXXXX XXXXXXXX XXX X
    X
  XXX
XXX
XXXXXXXXX
XXXXXXX
XXXX X
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXX XXXXXX
  XXXXXXXXXXX XXXXXX
X
XXXXXXXXXXXX X
  XXXXXXXXX XXXXXX
  XXXXXX XX
  XXXXXXXX XX
X
XXXXXXX X
  XXXXXXXXX XXXXXXXXX
  XXXXXXXX XX
X
XXXXXXXX XXXXXXX XX XXXXXXXXXXXXX XXXXXXXXXXXX X X
  XXXXXX XXXX XXXXXXXXXXX
X
XXXXXXXXXXXX X
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  XXXXXX XXXX XXXXXXXXXXX
  XXXXXXXX XXXXX
  XXXXXXXXXXXXXX XXXXX
  XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX XXXX
X
XXXXXXXXXXXXXXX X
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
  XXXXXXX XXXXX
  XXXXXX XXXXXX
  XXXXXXXX XXXX XXXXX
  XXXXXXXXXXXXXX XXXX
  XXXXXXXXXXXX XXXX
  XXXXXXXXXXXXXXXX XXXXX
  XXXXXXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXX XXXXX
  XXXXXXX XXXXXXXX
  XXXXXXXXXXX XXX XXXX XXXXX
X
XXXXXXXXXXXXXXXXXXXXX X
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
  XXXXXX XXXXXX
  XXXXXXXXXXXXXXXX XXXXX
  XXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXXXXX
X
XXXXXXXXXXX X
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
X
XXXXXXXXXXXXXXXXX X
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
X
XXXXXXXXXXXXXX X
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
X
XXXXXXXXXXXXXXXXXXXX X
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
X
XXXXXXXXXXXXXX X
  XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBXXXXXXXXX XXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXXX XX XXXXXXXX XX XXXXXXXXX XXXXXXXXXXXXX

    XXX XXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBB
      BB BBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXX FFFFFFFFXXXXXBBBBB
      BB BBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBB
      BB BBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBB
      BB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXBBBBB
    XXXXX

    XX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXX XX XX XXXXX XXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXX
      BBBBBBBBBB
      XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXBBBBB XX XXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXFFFFFFFFFFFXX
          X XXXXXXXX
        XXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXX
      XXXXXX
    XXXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
