BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBBBBBB
XXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX X
    XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXX X
    XXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXX XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXX XXXX XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXX XXXXX
    XXXXXXXXX XXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXX XXX
    XXXXXXXX XXXX
  X

  XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXX X
    XXXXXXXXXXX X X XXXX XXXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
  X

  XXXXXXXXXXXX X
    XXXXXX XXXXXXXX
  X

  XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
  X

  XXXXXXXXXXX X
    XXXXXXXXXXX XXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
  X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX X XXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXX XXXXXX XXXX XXXXX XXXXXX XXXXX XXXXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXX XXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX
  XXXX XXXXXX XXXXXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX
               gettext(u'Vehicles') 
            XXXXX
            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Professional vehicle management system') XXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'System Active') XXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXX XXXXXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX X X XXXXX X X X X XXXX XXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX
                 XXXXXXXXXXXXX gettext(u'Search by license plate, customer, brand or model...') X
                 XXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX X X XXXXX X X X X XXXX XXXXXXXXXXX
          XXXXXX
          XXXXXX gettext(u'Search') XXXXXXX
        XXXXXXXXX
      XXXXXX
    XXXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXX XXXXXXXX XXXX XXX
  XXXX XXXXXXXXXXXXXXXXXX
    BBB BBBBBBBB BB BBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXX X XXXXXXXXX XXXXXXXXXXX XXX X X XXX XXXXXXXX XXX X X XXXXXXXX XXXXXXXXXXXX XXXXX X XXX XXXXXX X X XXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Identification') XXXX
              XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Owner') XXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFXXXX
            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFFFXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Manufacturer') XXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXFFFFFFFFFFFXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Model') XXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFXXXX
          XXXXXX
        XXXXXX

        XXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXX XXXXXX XXXXXXX X X XXXXXXXXX X X XXXXXXXXXX X X XXXX XXXXXX X X XXX XXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Year') XXXX
              XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXFFFFFFFFFFFXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX
             XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXX X X XXXX X X X X XXX XXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXX XXXXX X XX XXXXXXX X XXXXX XXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXXX gettext(u'View') XXXXXXX
          XXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX
             XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXX X X XXXX XXXXXX X X XXX XXXXXX X X XXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXXX gettext(u'Edit') XXXXXXX
          XXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXX XXXXXX XXX XXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXX
            XXXXXX gettext(u'Last updated') X FFFFFFFFFFFFXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Active') XXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    BBBBB
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXX X X XXX XXXXX X X XXXX XXXXX X X XXXXXXXXXXX X X XXXXXXXX XXXXX X X XXXXXXXX XXXXXX X X XXXXXXX XXXXX X X XXXXXXXXX X X XXX XXXXX XXXXXXXXXXXXX
        XXXXXX
      XXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'No vehicles registered') XXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Start by adding your first vehicle to the system') XXXX
    XXXXXX
    BBBBBB
  XXXXXX

  XXXX XXXXXXXXXXXX XXXXXXXXXX XXX
  BB BBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
      XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXX X X XXXXXXXXXX X X XXXX XXXXX X X XXX XXXXX X X XXXXXXXX XXXXX X X XXXXXXXXX X X XXX XXXXXXX XXX X X XXX XXXXX X X XXXXXXX XXXXX X X XXXXXXXXX X X XXX XXXXXX X X XXXX XXXXXX X X XXXXXXXXXXXXXXXX
          XXXXXX
          XXXXXX gettext(u'Page')    gettext(u'of')  XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX  gettext(u'records') XXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXXBB BBBBBBBBBBBBBXXXBBBBBX
               XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX
              XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXX
              XXXXXX
              XXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'First') XXXXXXX
            XXXX
            XX XXXXXXXXXXXXBB BBBBBBBBBBBBBXXXBBBBBX
               XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX
              XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX
              XXXXXX
              XXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Previous') XXXXXXX
            XXXX
          BBBBB

          XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX
            
          XXXXXX

          BB BBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXBB BBBBBBBBBBBBBXXXBBBBBX
               XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX
              XXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Next') XXXXXXX
              XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXX XXX XXXXXXXXXX
              XXXXXX
            XXXX
            XX XXXXXXXXXXXXBB BBBBBBBBBBBBBXXXBBBBBX
               XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX
              XXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Last') XXXXXXX
              XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXX XXX XXX XXX XXX XXXXXXXXXX
              XXXXXX
            XXXX
          BBBBB
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  BBBBB

  XXXX XXXXXXXXXXXX XXX XXXXXXX XXXXXX XXX
  XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
    XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX
       XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXX
      XXXXXX
      XXXXXX gettext(u'Add Vehicle') XXXXXXX
    XXXX
  XXXXXX

  XXXX XXXXXXXXXXXX XXXXXX XXXXXX XXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXX gettext(u'Professional vehicle management system')  X  gettext(u'Version')  XXXXXXXXXX
      XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
