[pytest]
DJANGO_SETTINGS_MODULE = gestion_taller.settings
testpaths =
    tests
    tests/unit
python_files = test_*.py
addopts = -ra --strict-markers --disable-warnings --maxfail=1 --cov=taller --cov=gestion_taller --cov-report=term-missing --cov-report=xml --cov-fail-under=22

markers =
    slow: slow tests
    django_db: db access
    kpi: kpi tests
