BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBB

BBBBB BBBBB
X BB BBBBBBBBBBBBB BB BBBBXXXXXXXXX XXXXXXXXXXXBBBBXXXXXXX XXXXXXXXBBBBB X 
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXX XXXXXX
  XXXX XXXXXX XX XXXXX XXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXX XXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXXX

    XXXX XXXXXX XXX XXXXX XX XXXXXXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
        XX
      XXXXXX

      XXXX XXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          X BB BBBBBBBBBBBBB BB BBBB
            XXXXXXXXX XXXXXXXXXXX
          BBBB
            XXXXXXX XXXXXXXX
          BBBBB
        XXXXX

        XXXX XXXXXXX XXXXXXXXX XXX
        XX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBB BB BBBB
            XXXXXXX XXX XXXXXX XXXXXXXX XX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXX XXXXXX XX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBB
            XXX XXX XXXX XXX XXXX XX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXX XXXXXX XX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB
        XXXX

        XXXX XXXXXXXXXXX XXX XXXXXXX XXX
        XXXX XXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX

          BB BBBBBBBBBBBB
          XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
          XXXXXX
          BBBBB

          BB BBBBBBBBBBBBBBB
          XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBXXXXXBBBBB
            XXXX
            XX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX
          BBBBB
        XXXXXX

        XXXX XXXXXXXXXX XX XXXXXXXXXXXX XXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX

            XXXX XXXXX XXXXXXXX XXX
            BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
            XX XXXXXXX
               XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXBB BBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBXXXXXXBBBBBXXXXXXX
            XXXX

            XXXX XXXXX XXXXXXXX XXX
            XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXBB BBBBBBBBBBBBB BB BBBBXXXXXXXX XXXXXXXXXXXXXXXBBBBXXXXXX XXXXXXXXXXXBBBBBXXXXXXX
              XXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
          XXXXXX
        XXXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXX XXX
        XXXX XXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBB BB BBBBXXXXX XX XXXXXXXXXBBBBXXXXXX XXXXXXXXXBBBBBXXXX
              XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                XXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXX XXX XX XXXXX XXXXXXXXXX XXXXXXXXXBBBBXXXXXX XXXXX XXX XX XXXXXXXXXX XXXXXXXXXBBBBBXXXXX
                XXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXX XXX XXXXX XX XXX XXXXXXXXXBBBBXXXXXX XXXX XX XXX XXXX XXBBBBBXXXXX
                XXXXX BB BBBBBBBBBBBBB BB BBBBXXXX XXXXXX XX XX XXXXX XXXXXXXXBBBBXXXX XXXXXX XXXXXX XX XXXXXXBBBBBXXXXX
              XXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXXXXX
XXXXXXXXXX XXXXX X
  XXX XXXX X XXXXXXXX XX X
  XXX X XXXXXXXX XXXX X
X
XXXXXXXXXXXXXX X
  XXXXXXXXXX XXXXX XX XXXXXXXXXXXXXXXXX XX XXXX XX XXXXXXXXX
X
XXXXXXXX
BBBBBBBB
