"""
Tests for the International Content Engine.

Covers:
- Engine output correctness (language, substitutions, structure)
- HTTP 200 for all country × vertical combinations via landing_vertical view
- Landing URLs generated by get_hub_landing_urls
- No cross-contamination of language/terminology
"""

import pytest
from django.contrib.auth.models import AnonymousUser
from django.test import RequestFactory

from taller.country.engine import get_hub_landing_urls, get_landing_context
from taller.country.verticals import VERTICAL_CONTENT
from taller.views.landing_views import landing_vertical

COUNTRIES = ["cl", "ar", "pe", "mx", "us_en", "us_es", "br", "ec", "ve"]
VERTICALS = ["workshop", "parts", "salvage", "tire", "carwash"]


# ---------------------------------------------------------------------------
# Engine — structural completeness
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("country_key", COUNTRIES)
@pytest.mark.parametrize("vertical_key", VERTICALS)
def test_engine_returns_required_keys(country_key, vertical_key):
    ctx = get_landing_context(country_key, vertical_key)
    required = {
        "seo_title", "meta_description", "hero_h1", "hero_badge",
        "hero_cta_primary", "tw", "rubro_key", "language",
        "cta_mid_heading", "cta_final_heading", "cta_final_button",
    }
    missing = required - set(ctx.keys())
    assert not missing, f"{country_key}/{vertical_key} missing keys: {missing}"


@pytest.mark.parametrize("country_key", COUNTRIES)
@pytest.mark.parametrize("vertical_key", VERTICALS)
def test_engine_no_unresolved_placeholders(country_key, vertical_key):
    ctx = get_landing_context(country_key, vertical_key)
    string_vals = [v for v in ctx.values() if isinstance(v, str)]
    for val in string_vals:
        assert "{" not in val or "}" not in val or val.count("{") == val.count("}") == 0 or \
               not any(k in val for k in ["workshop_name", "plate_term", "city_1", "currency_code"]), \
               f"{country_key}/{vertical_key}: unresolved placeholder in '{val[:80]}'"


# ---------------------------------------------------------------------------
# Language routing
# ---------------------------------------------------------------------------

def test_us_en_uses_english():
    ctx = get_landing_context("us_en", "workshop")
    assert ctx["language"] == "en"
    assert "8 seconds" in ctx["hero_h1"] or "Do you remember" in ctx["hero_h1"]


def test_us_es_uses_spanish():
    ctx = get_landing_context("us_es", "workshop")
    assert ctx["language"] == "es"
    assert "¿Recuerdas" in ctx["hero_h1"]


def test_br_uses_portuguese():
    ctx = get_landing_context("br", "workshop")
    assert ctx["language"] == "pt"
    assert "lembra" in ctx["hero_h1"].lower() or "Você" in ctx["hero_h1"]


def test_cl_uses_spanish():
    ctx = get_landing_context("cl", "workshop")
    assert ctx["language"] == "es"
    assert "¿Recuerdas" in ctx["hero_h1"]


# ---------------------------------------------------------------------------
# Substitution correctness
# ---------------------------------------------------------------------------

def test_plate_term_substituted_in_step():
    ctx_cl = get_landing_context("cl", "workshop")
    ctx_pe = get_landing_context("pe", "workshop")
    step_cl = ctx_cl["steps"][0]["body"]
    step_pe = ctx_pe["steps"][0]["body"]
    assert "patente" in step_cl
    assert "placa" in step_pe


def test_workshop_name_substituted():
    ctx_br = get_landing_context("br", "workshop")
    assert "Oficina Mecânica" in ctx_br["hero_h1"] or "Oficina Mecânica" in ctx_br["hero_badge"]


def test_tire_name_substituted_for_each_country():
    expected = {
        "cl": "Vulcanización",
        "ar": "Gomería",
        "pe": "Llantería",
        "mx": "Llantera",
        "br": "Borracharia",
        "us_en": "Tire Shop",
    }
    for country, tire in expected.items():
        ctx = get_landing_context(country, "tire")
        assert tire in ctx["hero_h1"], f"{country}: expected '{tire}' in hero_h1"


def test_parts_name_substituted():
    ctx_mx = get_landing_context("mx", "parts")
    assert "Refaccionaria" in ctx_mx["hero_badge"]


def test_carwash_name_mexico():
    ctx = get_landing_context("mx", "carwash")
    assert "Autolavado" in ctx["hero_badge"]


def test_example_car_substituted_in_parts_setup():
    ctx_pe = get_landing_context("pe", "parts")
    assert "Toyota Yaris" in ctx_pe["hero_setup"]
    ctx_mx = get_landing_context("mx", "parts")
    assert "Nissan Versa" in ctx_mx["hero_setup"]


# ---------------------------------------------------------------------------
# Case studies and testimonials
# ---------------------------------------------------------------------------

def test_cl_workshop_has_case_study():
    ctx = get_landing_context("cl", "workshop")
    assert ctx["case_study"] is not None
    assert "Rancagua" in ctx["case_study"]["before_label"]


def test_ar_workshop_has_case_study():
    ctx = get_landing_context("ar", "workshop")
    assert ctx["case_study"] is not None
    assert "Córdoba" in ctx["case_study"]["before_label"]


def test_us_en_workshop_has_english_case_study():
    ctx = get_landing_context("us_en", "workshop")
    assert ctx["case_study"] is not None
    assert "Atlanta" in ctx["case_study"]["before_label"]


def test_cl_workshop_has_testimonial():
    ctx = get_landing_context("cl", "workshop")
    assert ctx["testimonial"] is not None
    assert ctx["testimonial"]["name"] == "Carlos Muñoz"


def test_br_workshop_has_testimonial():
    ctx = get_landing_context("br", "workshop")
    assert ctx["testimonial"] is not None
    assert "Paulo" in ctx["testimonial"]["name"]


def test_salvage_has_no_case_study_for_countries_without_one():
    # Salvage case studies aren't defined per-country — engine should not crash
    ctx = get_landing_context("cl", "salvage")
    # Either has a case or not — just must not raise
    assert isinstance(ctx["case_study"], (dict, type(None)))


# ---------------------------------------------------------------------------
# Hub landing URLs
# ---------------------------------------------------------------------------

def test_hub_landing_urls_cl():
    urls = get_hub_landing_urls("cl")
    assert urls["workshop"] == "/cl/talleres/"
    assert urls["parts"] == "/cl/repuestos/"
    assert urls["salvage"] == "/cl/desarmadurias/"
    assert urls["tire"] == "/cl/vulcanizaciones/"
    assert urls["carwash"] == "/cl/lavado/"


def test_hub_landing_urls_ar():
    urls = get_hub_landing_urls("ar")
    assert urls["workshop"] == "/ar/talleres/"
    assert urls["tire"] == "/ar/gomeria/"
    assert urls["salvage"] == "/ar/desarmaderos/"


def test_hub_landing_urls_us_en():
    urls = get_hub_landing_urls("us_en")
    assert urls["workshop"] == "/us/en/auto-repair/"
    assert urls["tire"] == "/us/en/tire-shop/"
    assert urls["parts"] == "/us/en/auto-parts/"


def test_hub_landing_urls_us_es():
    urls = get_hub_landing_urls("us_es")
    assert urls["workshop"] == "/us/es/talleres/"
    assert urls["tire"] == "/us/es/llantera/"


def test_hub_landing_urls_br():
    urls = get_hub_landing_urls("br")
    assert urls["workshop"] == "/br/oficina-mecanica/"
    assert urls["tire"] == "/br/borracharia/"
    assert urls["parts"] == "/br/autopecas/"


def test_hub_landing_urls_mx():
    urls = get_hub_landing_urls("mx")
    assert urls["parts"] == "/mx/refaccionaria/"
    assert urls["tire"] == "/mx/llantera/"
    assert urls["salvage"] == "/mx/yonke/"
    assert urls["carwash"] == "/mx/autolavado/"


def test_hub_landing_urls_ve_ec():
    assert get_hub_landing_urls("ve")["tire"] == "/ve/cauchera/"
    assert get_hub_landing_urls("ec")["tire"] == "/ec/llantera/"
    assert get_hub_landing_urls("pe")["tire"] == "/pe/llanteria/"


# ---------------------------------------------------------------------------
# HTTP rendering via landing_vertical view
# ---------------------------------------------------------------------------

@pytest.fixture
def rf():
    return RequestFactory()


def _render(rf, country_key, url_slug):
    request = rf.get("/")
    request.user = AnonymousUser()
    response = landing_vertical(request, country_key, url_slug)
    return response.content.decode()


@pytest.mark.django_db
def test_cl_talleres_renders_200(rf):
    html = _render(rf, "cl", "talleres")
    assert "¿Recuerdas exactamente" in html
    assert "Rancagua" in html


@pytest.mark.django_db
def test_ar_talleres_no_chilean_city(rf):
    html = _render(rf, "ar", "talleres")
    assert "Rancagua" not in html
    assert "Córdoba" in html


@pytest.mark.django_db
def test_mx_repuestos_has_refaccionaria(rf):
    html = _render(rf, "mx", "repuestos")
    assert "Refaccionaria" in html
    assert "Casa de Repuestos" not in html


@pytest.mark.django_db
def test_us_en_talleres_is_english(rf):
    html = _render(rf, "us_en", "talleres")
    assert "Do you remember" in html
    assert "Auto Repair Shop" in html
    assert "Atlanta" in html


@pytest.mark.django_db
def test_us_es_talleres_is_spanish(rf):
    html = _render(rf, "us_es", "talleres")
    assert "¿Recuerdas" in html
    assert "Los Angeles" in html
    assert "Do you remember" not in html


@pytest.mark.django_db
def test_br_neumaticos_is_portuguese(rf):
    html = _render(rf, "br", "neumaticos")
    assert "Borracharia" in html
    assert "Passo 1" in html
    assert "Paso 1" not in html


@pytest.mark.django_db
def test_pe_desarmadurias_has_desarmadero(rf):
    html = _render(rf, "pe", "desarmadurias")
    assert "Desarmadero" in html


@pytest.mark.django_db
def test_ar_gomeria_renders_200(rf):
    html = _render(rf, "ar", "gomeria")
    assert "Gomería" in html
    assert "Argentina" in html


@pytest.mark.django_db
def test_mx_refaccionaria_renders_200(rf):
    html = _render(rf, "mx", "refaccionaria")
    assert "Refaccionaria" in html


@pytest.mark.django_db
def test_ec_llantera_renders_200(rf):
    html = _render(rf, "ec", "llantera")
    assert "eGarage" in html


@pytest.mark.django_db
def test_ve_cauchera_renders_200(rf):
    html = _render(rf, "ve", "cauchera")
    assert "Venezuela" in html or "Caracas" in html


@pytest.mark.django_db
def test_br_oficina_mecanica_renders_200(rf):
    html = _render(rf, "br", "oficina-mecanica")
    assert "São Paulo" in html


@pytest.mark.django_db
def test_us_en_auto_repair_renders_200(rf):
    html = _render(rf, "us_en", "auto-repair")
    assert "Atlanta" in html
    assert "Do you remember" in html


@pytest.mark.django_db
def test_cl_vulcanizaciones_renders_200(rf):
    html = _render(rf, "cl", "vulcanizaciones")
    assert "Vulcanización" in html


@pytest.mark.django_db
def test_generic_slug_still_resolves(rf):
    # Generic slugs remain valid aliases so existing links don't break
    html = _render(rf, "br", "neumaticos")
    assert "Borracharia" in html


@pytest.mark.django_db
def test_br_navbar_is_portuguese(rf):
    html = _render(rf, "br", "oficina-mecanica")
    assert "Entrar" in html
    assert "Criar conta" in html
    assert "Ingresar" not in html
    assert "Registrarse" not in html


@pytest.mark.django_db
def test_us_en_navbar_is_english(rf):
    html = _render(rf, "us_en", "auto-repair")
    assert "Sign in" in html
    assert "Create account" in html
    assert "Ingresar" not in html


@pytest.mark.django_db
def test_cl_navbar_is_spanish(rf):
    html = _render(rf, "cl", "talleres")
    assert "Ingresar" in html
    assert "Registrarse" in html


@pytest.mark.django_db
def test_br_footer_is_portuguese(rf):
    html = _render(rf, "br", "oficina-mecanica")
    assert "Início" in html
    assert "Oficina Mecânica" in html
    assert "Borracharia" in html
    assert "Desmanche" in html
    assert "Talleres" not in html
    assert "Vulcanización" not in html


@pytest.mark.django_db
def test_us_en_footer_is_english(rf):
    html = _render(rf, "us_en", "auto-repair")
    assert "Home" in html
    assert "Auto Repair Shop" in html
    assert "Tire Shop" in html
    assert "Ingresar" not in html


@pytest.mark.django_db
def test_cl_footer_has_local_slugs(rf):
    html = _render(rf, "cl", "talleres")
    assert "/cl/vulcanizaciones/" in html
    assert "/cl/desarmadurias/" in html
    assert "/cl/repuestos/" in html


@pytest.mark.django_db
def test_mx_footer_has_local_slugs(rf):
    html = _render(rf, "mx", "talleres")
    assert "/mx/refaccionaria/" in html
    assert "/mx/yonke/" in html
    assert "/mx/llantera/" in html


@pytest.mark.django_db
def test_html_lang_attribute(rf):
    assert 'lang="pt"' in _render(rf, "br", "oficina-mecanica")
    assert 'lang="en"' in _render(rf, "us_en", "auto-repair")
    assert 'lang="es"' in _render(rf, "cl", "talleres")


@pytest.mark.django_db
def test_invalid_country_raises_404(rf):
    from django.http import Http404
    with pytest.raises(Http404):
        _render(rf, "zz", "talleres")


@pytest.mark.django_db
def test_invalid_slug_raises_404(rf):
    from django.http import Http404
    with pytest.raises(Http404):
        _render(rf, "cl", "noexiste")
