BBBB BBBBBBBBBBB
BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBXXXXXXXXXXXXX XXX XXXXXXBB BBBBBBB X BBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXX
  XXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXX
    BB BBBBBBB
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    BBBB
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX XX XXXXXXXX XXXXXXXXXXX XX XX XXXXXXXXXXX
    BBBBB
  XXXXXX

  XXXX XXXX XX XXXXXXXXXXXXXXX XXX
  XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX

    XXXX XXXXXXXXXXXXX XX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBB B B
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        BBBBB
      XXXXXX

      XX
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
  XXXXXXFFFFFFFFFFFX
        XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      X
        XXXXXXXXX XXXXXXXX X
      XXXX
    XXXXXX

    XXXX XXXXXXXXXXXXX XX XXXXXXX XXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXXXXXXX
          BB BBBBBBBBBBBBBBBB
          XXXXXX XXXXXX
          BBBBB
          BB BBBBBBBBBBBBB
          XXXXXX XXXXXX
          BBBBB
        XXXXXX
      XXXXXX

      XXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXX
      X
        XXXXXXXXXXXX
      XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXX XXX XXXXXX XX XXXXXXXXXX
      XXXXXX

      XXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXX
      X
        XXXXXXXXXXXX
      XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXX XX XXXXXXXX XXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XX XX XXXXXXXXXX
      XXXXXX

      XXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXX
      X
        XXXXXXXXXXXX
      XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXX XX XXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX XXXXX XXXXXXXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXX

      XX
        XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      X
        XXXXX XXXXX X
      XXXX
    XXXXXX

    XXXX XXXXXXXXXXXXX XX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXX XXXXX XXX XXXXXXXXXXXXXX
      XXXXXX

      XX
        XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
        XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      X
        XXX XXXXXXXXXX X
      XXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXX XXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXX
    XX
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXXFFFFFFFFFFFX
      XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    X
      X XXXXXX XX XXXXXXXXX
    XXXX
  XXXXXX
XXXXXX
BBBBBBBB
