BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXX XXXXXXXX XXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXXXX

  XXXX XXXXXXXXXX XXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXX XXXX XXXXX
    XXXX XXXXXXXXXX XX XXXXXX XXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                   gettext(u'Configuración del Taller')
                XXXXX
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                  XX XX
                XXXXXXX
              XXXXXX
              XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Sistema avanzado de gestión de taller') XXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXX XX XXXXXXXXXXXX XXX
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Total Técnicos') XXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Técnicos Activos') XXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Técnicos Inactivos') XXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Total Documentos') XXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXX XX XXXXXXXXXXX XX XX XXXXXXX XXX
      XXXX XXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'Información de la Empresa') XXXXX

          XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
              XXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX
                   gettext(u'Nombre del Taller')  X
                XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                       XXXXXXXX
                       XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXX
              XXXXXX

              XXXXX
                XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX
                   gettext(u'Teléfono')
                XXXXXXXX
                XXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                       XXXXXXXX
                       XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX

              XXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX
                   gettext(u'Correo Electrónico')
                XXXXXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                       XXXXXXXX
                       XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX

              XXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX
                   gettext(u'Dirección')
                XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                       XXXXXXXX
                       XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX
                   gettext(u'Logo de la Empresa')
                XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXX
                    XXXX XXXXXX XXXXX gettext(u'Logo Actual') X
                         XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Logo actual') XXXX
                  XXXXXX
                BBBBB
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                XXXXXX gettext(u'Actualizar Información de la Empresa') XXXXXXX
              XXXXXXXXX
            XXXXXX
          XXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXX XX XXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX gettext(u'Gestión de Técnicos') XXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
              XXXXXX gettext(u'Agregar Técnico') XXXXXXX
            XXXXXXXXX
          XXXXXX

          XXXX XXXXXXXXXX XX XXXXXXX XXXXXXX XXXXXXX XXX XXXXXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX gettext(u'Agregar Nuevo Técnico') XXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              BBBBBBBBBB
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX

              XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                XXXXX
                  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX
                     gettext(u'Nombre')  X
                  XXXXXXXX
                  XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                         XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX

                XXXXX
                  XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX
                     gettext(u'Apellido')  X
                  XXXXXXXX
                  XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
                         XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX

                XXXXX
                  XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX
                     gettext(u'Teléfono')
                  XXXXXXXX
                  XXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                         XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX

                XXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX
                     gettext(u'Especialidad')
                  XXXXXXXX
                  XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                         XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXX

              XXXX XXXXXXXXXXX XXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                  XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                  XXXXXX gettext(u'Agregar Técnico') XXXXXXX
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                  XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                  XXXXXX gettext(u'Cancelar') XXXXXXX
                XXXXXXXXX
              XXXXXX
            XXXXXXX
          XXXXXX

          XXXX XXXXX XX XXXXXXXX XXX
          BB BBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXXX
                  XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Nombre') XXXXX
                    XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Teléfono') XXXXX
                    XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Especialidad') XXXXX
                    XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Estado') XXXXX
                    XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Acciones') XXXXX
                  XXXXX
                XXXXXXXX
                XXXXXXX
                  BBB BBBBBBB BB BBBBBBBB
                  XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXFFFFFFFFFFFXXXXX
                    XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXFFFFFFFFFFFXXXXX
                    XXX XXXXXXXXXXX XXXXXX
                      BB BBBBBBBBBBBBBB
                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                          XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                           gettext(u'Activo')
                        XXXXXXX
                      BBBB
                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                          XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                           gettext(u'Inactivo')
                        XXXXXXX
                      BBBBB
                    XXXXX
                    XXX XXXXXXXXXXX XXXXXX
                      XXXX XXXXXXXXXXX XXXXXXX
                        BB BBBBBBBBBBBBBB
                          XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            BBBBBBBBBB
                            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX gettext(u'¿Estás seguro de que quieres desactivar este técnico?') XXXX
                              XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                              XXXXX XXXXXXXXXXXXXXXX gettext(u'Desactivar') XXXXXXX
                            XXXXXXXXX
                          XXXXXXX
                        BBBB
                          XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            BBBBBBBBBB
                            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                              XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                              XXXXX XXXXXXXXXXXXXXXX gettext(u'Activar') XXXXXXX
                            XXXXXXXXX
                          XXXXXXX
                        BBBBB

                        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                          BBBBBBBBBB
                          XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                          XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX gettext(u'¿Estás seguro de que quieres eliminar este técnico? Esta acción no se puede deshacer.') XXXX
                            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXX gettext(u'Eliminar') XXXXXXX
                          XXXXXXXXX
                        XXXXXXX
                      XXXXXX
                    XXXXX
                  XXXXX
                  BBBBBB
                XXXXXXXX
              XXXXXXXX
            XXXXXX
          BBBB
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'Aún no hay técnicos') XXXXX
              XX XXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Comienza agregando tu primer técnico') XXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                XXXXXX gettext(u'Agregar Técnico') XXXXXXX
              XXXXXXXXX
            XXXXXX
          BBBBB
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXX XXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
  XX XXXXXXXXXXX XXXXXX XX XXXXXXXXXX
  XX XXXXXXX XXXXXXXXXXX XXX XXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXX X XXXXXXX XXXXX XX
      XXXXXXXXXXX X XXXXXX X XXXXXX XXXXXXXXXXXXX X XX
      XXXXXXXXXX X
        XXXXXXX X XXXXXX XX XX
        XXXXXX X XXXXXX XXXXXXXXX XX
        XXXXX X XXXXXX X XX
        XXXXX X XXXXXXX XXXXX XXXXXX XXX XX
        XXXXXX X XXXXXXX XXXXX XXXXXX XXXXXXXXXX XXXXXXXX XXX X
      X
    XXX
  X
XXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
  XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X
XXXXXXXXX
BBBBBBBB BBBBBBB
