BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBBB
XXXX X XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXX XXXXXX XXXX XXXXX XXXXXX XXXXX XXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXX
XXXXXXX
XX XXXXXXX XXXXXXXXXXXXX X XXXXXXX XX
XXXXXXXXXXXXX X
  XXXXXXXXXXX XXXXXXXXX XXXX XXXXX XXXXXXXXXX XXXX XXXXX
X

XXXXXXXXXXXXXXXXXXX X
  XXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXXX
X

XX XXXXXXXXXX XXXX XXXXXXXXXXX XX
XXXXXX XXXXXXXXXXX XXXXXX X
  XXXXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXXXXX
  X
X

XX XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXX XX
XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
  XXXXXXXX XXXX XXXXXXXXXXX
X

XX XXXXXXX XXXXXXXXX XXX XXXXXXXXXXX XXXXXX XX
XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
  XXXXXXXXXX XXXX XXXXXXXXXXX
X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXX

XXXX XXXXXX XXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX gettext(u'Vehículos') XXXXX
          XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Sistema de gestión vehicular profesional') XXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXX gettext(u'Sistema activo') XXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXX XXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXX
             XXXXXXXX
             XXXXXXXX
             XXXXXXXXXXXXX gettext(u'Buscar por patente, cliente, marca o modelo...') X
             XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
         gettext(u'Buscar') 
      XXXXXXXXX
    XXXXXXX
  XXXXXX
XXXXXX

XXXX XXXXX XXXXXXX XXXXXXXX XXX
XXXX XXXXXXXXXXX XXXXXXXXXXXXX
  XX XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXXXXBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX gettext(u'Agregar Vehículo') XXXXXXX
  XXXX
XXXXXX

XXXX XXXX XX XXXXXXXXX XXXXXXXX XXX
XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  BBB BBBBBBBB BB BBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
    XXXX XXXXXX XXX XXXXXXX XXX
    XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXX
          XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXX
          XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
      XXXX XXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Propietario') XXXX
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
            FFFFFFFFFF FFFFFFFFFF
          BBBB
            X
          BBBBB
        XXXX
      XXXXXX

      XXXX XXXXX X XXXXXX XXX
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Marca') XXXX
          XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXFFFFFFFFFFFXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Modelo') XXXX
          XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXFFFFFFFFFFFXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXX XX XXXXXX XXX
    XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
      XX XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXBBBBBX
         XXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
          XXXXXXXXXXXXXXX
          XXXXXX gettext(u'Ver') XXXXXXX
        XXXXXXX
      XXXX
      XX XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXXXXXXBBBBBX
         XXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
          XXXXXXXXXXXXXXX
          XXXXXX gettext(u'Editar') XXXXXXX
        XXXXXXX
      XXXX
    XXXXXX
  XXXXXX
  BBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
        X
      XXXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'No hay vehículos registrados') XXXXX
      XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Comienza agregando tu primer vehículo al sistema') XXXX
    XXXXXX
  XXXXXX
  BBBBBB
XXXXXX

XXXXXX

XXXX XXXXXXXXXX XXXXXX XXXX XXXXXXXX XXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXX XXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXX X XXXXXXXX
                X XXXX X
                    XXXXXXXXXXXXXXXXXX X XXXXXXX
                X
            XXX
        XXX
    X
XXX
XXXXXXXXX

BBBBBBBB
