BBBBBBB BBBBBBBBBBB
BBBBB BBBBBXXXXX XX XXXXXXXX X XXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
