BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBBBBBBBBBBB BBBB

BBBBB BBBBB gettext(u'Configuración de Empresa') BBBBBBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX
  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
  X
  
  XXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXX
  X
  
  XXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXX
  X
  
  XXXXXXXXXXXXXX X
    XXXXXXXXXXXXXX XX
  X
  
  XXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXXX
  X
  
  XXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXX XXXXX
  X
  
  XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X X X XXX XXXXXXXXX XXXX XXX XXXXX
    XXXXXXXX XXXXX
  X
  
  XXXXXXXXXXXXX X
    XXXXXX XXXXXXXXX XXXX XXXX XXXXXX
    XXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXX
  X
  
  XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
  X
  
  XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXX
  X
  
  XXXXXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXXX
    XXXXXXXX XXXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXXXX
  X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'Configuración de la Empresa') 
  XXXXX

  XXXX XXXXXXXX XXXXX XX XX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Datos Generales') 
    XXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      BBBBBBBBBB
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
      
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        XXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Nombre del Taller')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXX
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        XXXXXX
        
        XXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
             gettext(u'Razón Social') 
          XXXXXXXX
          FFFFFFFFFFFFFFFFFFFFFFFFFFFF
        XXXXXX
      XXXXXX
      
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        XXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
             gettext(u'Teléfono') 
          XXXXXXXX
          FFFFFFFFFFFFFFFFFFFFFFFFFFFF
        XXXXXX
        
        XXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
             gettext(u'Logo') 
          XXXXXXXX
          FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          BB BBBBBBBBBBBB
            XXXX XXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Logo actual:') XXXX
              XXXX XXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX
          BBBBB
        XXXXXX
      XXXXXX
    XXXXXXX
  XXXXXX

  XXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Identificación Tributaria') 
      XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBB BB BBBBXX XXXXX
        BBBB BBBBBBBBBBBB BB BBBBXX XXX
        BBBB BBBBBBBBBBBB BB BBBBXX XXXXXX
        BBBB BBBBBBBBBBBB BB BBBBXX XXXX
        BBBB BBBBBBBBBBBB BB BBBBXX XXXXXXXXX
        BBBBB
      XXXXXXX
    XXXXX
    
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'Tipo de Identificador') 
        XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXX  gettext(u'Seleccione')  XXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBXXX XXX XXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBXXX XXX XXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBXXX XXX XXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBXXX XXX XXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXBBBBBXXX XXXX XXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBXXX XXX XXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBXXX XXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'Selecciona el tipo de identificador tributario') 
        XXXXXX
      XXXXXX
      
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Número de Identificación') 
          XXXXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX 
               XXXXXXXFFFFFFFFFFX 
               XXXXXXXXXXXXX gettext(u'Ingresa el número') X
               XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Ingresa el número de identificación tributaria') 
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXX XXXXXXXXX XXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Dirección Legal de la Empresa') 
    XXXXX
    
    XXXX XXXX XX XXXXX XXXXXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'País')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
          XXXXXXX XXXXXXXXXXX  gettext(u'Seleccione')  XXXXXXXXXXX
          XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXX XXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXX XXXXXXXXXXXX
          XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXX XXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXX XXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'País donde opera la empresa') 
        XXXXXX
      XXXXXX
      
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Estado/Región') XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
          XXXXXXX XXXXXXXXXXX  gettext(u'Seleccione país primero')  XXXXXXXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'Estado, región o departamento') 
        XXXXXX
      XXXXXX
      
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Ciudad')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
          XXXXXXX XXXXXXXXXXX  gettext(u'Seleccione estado primero')  XXXXXXXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'Ciudad donde está ubicada la empresa') 
        XXXXXX
      XXXXXX
    XXXXXX
    
    XXXX XXXX XX XXXXXXXXX XXXXX X X XXXXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Dirección Línea 1')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX 
               XXXXXXXXXXXXX gettext(u'Calle, número, oficina/local') X 
               XXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'Dirección principal (calle, número, oficina)') 
        XXXXXX
      XXXXXX
      
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Código Postal') 
        XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX 
               XXXXXXXXXXXXX gettext(u'Código postal') X
               XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'Código postal (si aplica)') 
        XXXXXX
      XXXXXX
    XXXXXX
    
    XXXX XXXX XX XXXXXXXXX XXXXX X XXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Dirección Línea 2')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'opcional') XXXXXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX 
               XXXXXXXXXXXXX gettext(u'Piso, depto, edificio, referencias (opcional)') X
               XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'Información adicional de la dirección (opcional)') 
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXX XXXXXXX XXXXXX XXX XXXXX XXXX XXX XXXXXXXXXXXXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Guardar Configuración de Empresa') 
    XXXXXXXXX
  XXXXXX

  XXXX XXXXXX XX XX XXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Estado de la Cuenta') 
    XXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX gettext(u'Días restantes') XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXFFFFFFFFFFFFFXXXXXX
        XXXX XXXXXXXXXXXXXXXX gettext(u'Suscripción') XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXFFFFFFFFFFFFXXXXXX
        XXXX XXXXXXXXXXXXXXXX gettext(u'Fecha de inicio') XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBB
XXXXXXX XXXXXXXXXXXXXX
  XX XXXXXXXX XXXXXXXXXXXX
  XXXXXX X XXXXXXXXXXXXXXXXXXXX X XXXX XBBBBBB BBBBBBBBBBBBBBBBBXX
  
  XX XXXXXXXX XXXXXXX XX XXXXXXXXX XXXX XXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  
  XX XXX XXXXXXXXX XXXXXXXXX XXXX XXX XX XXX
  XXXXX XXXXXXXXXXXXX X X
    XXXXXXXXX X
      XXXXXX XXX XXXXX
      XXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXX
    XX
    XXXXXXXXX X
      XXXXXX XXX XXXXX
      XXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXX
    XX
    XXXXXXXXX X
      XXXXXX XXX XXXXX
      XXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXX XXXXXXX XXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXX
    XX
    XXXXXXXXX X
      XXXXXX XXX XXXXX
      XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXX XXXX XXXXXXXXXX XXX XXXXXXXXX
    XX
    XXXXXXXXXX X
      XXXXXX XXX XXXXXX
      XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXX XXXXXXXXXX XXX XXXXXXXXX
    XX
    XXXXXXXXX X
      XXXXXX XXX XXXXX
      XXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXX XXXX XXXXXXX XXX XXXXXXXXX
    XX
    XXXXXXXXX X
      XXXXXX XXX XXXXX
      XXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXX XXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
    X
  XX
  
  XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  
  XX XXXXXXXXXXXXXXXX XX XXXXXXXXXX XX XXXXXXXXXX XX XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXX XXXXXXXXXXXX X XXXXXXXXXXX
      XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      
      XX XXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
      X XXXX X
        XXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Número de Identificación') XX
        XXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Ingresa el número') XX
        XXXXXXXXXXXXXXXXXXXXX X X gettext(u'Ingresa el número de identificación tributaria') XX
      X
    XXX
    
    XX XXXXXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    X
  X
  
  XX XXX XXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXX XXXX XXX
  XXXXX XXXXXXXXXXXX X X
    XXXXX X gettext(u'Región') XX
    XXXXX X gettext(u'Estado') XX
    XXXXX X gettext(u'Estado') XX
    XXXXX X gettext(u'Departamento') XX
    XXXXX X gettext(u'Estado') XX
  XX
  
  XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  
  XX XXXXXXXXXXXXXX XX XXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXX XXXXXXX X XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XX X gettext(u'Estado/Región') XX
      
      XX XXXXXXXXXX XXXXX XX XXXX
      XX XXXXXXXXXXXXXX X
        XXXXX XXXXX X X
          XXXXX XXX XXXXXXX
          XXXXX XXX XXXXX
          XXXXX XXX XXXXXXXX
          XXXXX XXX XXXXXX
          XXXXX XXX XXXXXXXXXX
        XX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX XX XXXXXXXX
      X
    XXX
    
    XX XXXXXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    X
  X
  
  XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXX XXXXXXX XXXXXXXXX
XXXXXXXXX
BBBBBBBB

