BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
XXXXXXX
  XX XXXXXX XXXX XXXXXX XXX XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XX XXXXXX XX
  XXXXX XXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XX XXXXX XX XXXX X XXX XXXXXX XXXXXXXXXXXX XX XXXX XXXXXX XXXXXXXXXX XX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX XX XXXXXXXXXXXX XX
    XXXXXXXXXXX XXXXX
  X

  XXXXX XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXX XXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX X  XX XXXXX XX
  XXXXX XXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXX XXXX XXX XXXXXX X XX XXXXX XX
  XXXXX XXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXX X  XX XXXXXXX XX

  XXXXX XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXX XXXXXXXXX X XXXXXXX XXXXX XXXXXXXX XXXXX X
  XXXXX XXXXXXXXX   XXXXXXXXXXXXXXXXXXX XXXXXXXX   X XXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX X XX XXXXXXXX X XXXXXXXX XX
  XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX X XX XXXXXXXXX X XXXXXXXXX XX
  XXXXX XXXXXXXXXX  XXXXXXXXXXXXXXXXXXX XXXXXXXXX  X XXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX X XX XXXXXXXXXXX X XXXXXXXXXXX XX
XXXXXXXX
