BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBB

BBBBB BBBBBXXXXXXXXX X XXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXX
  XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX
  XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX X XXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXX XX XX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXX
          XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
        BB BBBBBBBBB
          BBB BBBBBBBB BB BBBBBBBBB
          XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXXXXXXXXX
            XXX XXXXXXXXXXX XXXXXXXXXXX
            XXX XXXXXXXXXXX XXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXX XXXXXXXXXXX
              XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
              XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXX
          XXXXX
          BBBBBB
        BBBB
          XXXX
            XXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXX
        BBBBB
      XXXXXXXX
    XXXXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
