BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBXXXXX XXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXX XXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX

        XXXX XXXXXXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX
                                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                     gettext(u'Other Services')
                                XXXXX
                                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Advanced other services management system') XXXX
                            XXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXX XXXXXXX XXX
                        XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Operations Center') XXXXXXX
                            XXXX

                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Vehicles') XXXXXXX
                            XXXX

                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Clients') XXXXXXX
                            XXXX

                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Documents') XXXXXXX
                            XXXX

                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Reports') XXXXXXX
                            XXXX

                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Settings') XXXXXXX
                            XXXX

                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Parts') XXXXXXX
                            XXXX

                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Services') XXXXXXX
                            XXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
                XX  gettext(u'Other Services')
            XXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Manage additional services and special operations') XXXX
        XXXXXX

        XXXX XXXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search service...') X XXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            BBB BBBBBBBB BB BBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXX XXXXXXXX XXXXX XXXXXXX
                    XXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXX XXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Edit') XXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Delete') XXXX
                    XXXXXX
                XXXXXX
            BBBBB
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                            XX
                        XXXXXX
                        XXXXX
                            XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'No other services registered') XXXXX
                            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Start by adding your first additional service to the system') XXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            BBBBBB
        XXXXXX

        XXXX XXXXXXXX XXX XXXXXX XXX
        BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBB
            XX XXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'New Service') XXXXXXX
            XXXX
        BBBBB
    XXXXXX
XXXXXX

XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXX X X XXXX XXXXXXXX X X XXX XXXXXXXX X X XXX XXXXX
        XXXXXXXXXXXXXXX XXXX
    X
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXX X XXX XXX XXXXXX X XXX X XXXXXX
        XXXXXXXXXXXXXXX XXXX
    X
    XXXXXXXXXXXXX X
        XXXXXXXXX XXXXXX
        XXXXXX XX
        XXXXXX XXXXXX
        XXXXXXX XXXXXX
        XXXXXXXX XX
        XXXXXXXXXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXX XXXXXXXXXXXX X
        XXX XXXX X XXXXXXXXXX XXXXXXXXXXXXXX X
        XXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXX X
    X
XXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XX XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXX X
                    XXXXXXX X XXXXXX XXX XXXXXXXX X XXXXXXX XXXXX XXXXXXXXXXX XXX X XX
                    XXXXXX X XXXXXX XXXXXXXXX XX
                    XXXXXX X XXXXX XXXXXXXX XX
                    XXXXXXXX X XXXXXX XXXX XXXXXXX XXXX XX
                    XXXXX X XXXXXX XX XXXXXXX XXXX XX
                    XXXXXXXXXXXX X XXXXXXX XXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXXXX X XX
                    XXXXX X XXXXXXX XXXXX XXXXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXX XXXXXX XXXXXXXXX XXXXXX XXXXXXX XXXXX X
                XX
                XXXXXXXXXXXXXX X
                    XXXXXXXXXX XXXXXXXXX
                    XXXXXXX X
                        XXXXXXXX X XXXXXXX XXXXX XXXXX XXXXXXXXX XX
                        XXXXXXXX X XXXXXXX XXXXX XXXXX XXXXXX XX
                        XXXXXXX XXXX
                    XX
                    XXXXXX X
                        XXXXXXXX X XXXXXXXXX XXX XXXXXXXXX XXX XX
                        XXXXX X XXXXXXXXXXXXX X X
                    X
                XX
                XXXXXXXXXXXXXX XXXX
            XXX
        X
    XXX
XXXXXXXXX

XXXXXXXX
    XX XXXXXXX XXXXXXXXX XXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XX XX X XXX
        XXX

        XX XXXXXX XXXXXXXXXXXXX
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX X XXXXXXX
            XXX
        XXX
    XXX
XXXXXXXXX
BBBBBBBB
