BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBBB
BBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXX XXXXXXXX XXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXXXX

  XXXX XXXXXXXXXX XXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXX XXXX XXXXX
  XXXX XXXXXX XXXXXXX XXXX XXXXXXX XXXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
               gettext(u'Servicios Mecánicos')
            XXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Sistema de gestión de servicios avanzado') XXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX gettext(u'Sistema activo') XXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
               XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXXXX gettext(u'Agregar Servicio') XXXXXXX
            XXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXX
          XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
                 XXXXXXXXXXXXX gettext(u'Buscar por nombre, categoría o subcategoría...') X
                 XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
           gettext(u'ESCANEAR')
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXX gettext(u'Todas las Categorías') XXXXXXXXX
        BBB BBBBBBBBB BB BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBB
      XXXXXXXXX

      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXX gettext(u'Todas las Subcategorías') XXXXXXXXX
        BBB BBBBBBBBBBBB BB BBBBBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBB
      XXXXXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXX XXXX X XXXXXXX XXXXX XXX
  XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    BBB BBBBBBBB BB BBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
         XXXXXXXXXXXFFFFFFFFFFX
         XXXXXXXXXXXXXXXXFFFFFFFFFFX
         XXXXXXXXXXXXXXXXXXXFFFFFFFFFFX
         XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFX
         XXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXX
      XXXX XXXX XXXXXX XXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

      XXXX XXXX XXXX XXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXX
        XXXX XXXXXX XXXX XX XXX
        XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXX
              XXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXFFFFFFFFFFFFFFFFXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXX XXXXXXXXX XXXXXXXX
          XXXX XXXXXX XXX XXXXXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Servicio') XXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXFFFFFFFFFFFXXXX
          XXXXXX

          XXXX XXXXXXXXX X XXXXXXXXXXXX XXX
          XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Categoría') XXXX
              XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXFFFFFFFFFFFXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Subcategoría') XXXX
              XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXFFFFFFFFFFFXXXX
            XXXXXX
          XXXXXX

          XXXX XXXX XX XXXXXXXX XXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Tipo') XXXX
              XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                BB BBBBBBBBBBBBB
                  FFFFF
                BBBB
                  XXXXXXX
                BBBBB
              XXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX
               XXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXX
                XXXXXX gettext(u'Ver') XXXXXXX
              XXXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX
               XXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXX
                XXXXXX gettext(u'Editar') XXXXXXX
              XXXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XFFFFFFFFXXX
                    XXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXX
                XXXXXX gettext(u'Eliminar') XXXXXXX
              XXXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    BBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
            X
          XXXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'No hay servicios registrados') XXXXX
          XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Comienza agregando tu primer servicio al sistema') XXXX
        XXXXXX
      XXXXXX
    XXXXXX
    BBBBBB
  XXXXXX

  XXXX XXXXXXXXXX XXXXXXXXX XXX
  BB BBBBBBBBBBBB
  XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX gettext(u'Página')    gettext(u'de')  XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX  gettext(u'registros') XXXXXXX
          XXXXXX

          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBB
              XX XXXXXXXXXXXXXBB BBBBBBBBBBBBBXXXBBBBBX
                 XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                  XXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Primera') XXXXXXX
                XXXXXXX
              XXXX
              XX XXXXXXXXXXXXBB BBBBBBBBBBBBBXXXBBBBBX
                 XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                  XXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Anterior') XXXXXXX
                XXXXXXX
              XXXX
            BBBBB

            BB BBBBBBBBBBBBBBBBB
              XX XXXXXXXXXXXXBB BBBBBBBBBBBBBXXXBBBBBX
                 XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Siguiente') XXXXXXX
                  XXXXXXXXXXXXXXX
                XXXXXXX
              XXXX
              XX XXXXXXXXXXXXBB BBBBBBBBBBBBBXXXBBBBBX
                 XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Última') XXXXXXX
                  XXXXXXXXXXXXXXX
                XXXXXXX
              XXXX
            BBBBB
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  BBBBB
  XXXXXX
XXXXXX

XXXX XXXXX XX XXXXXXXXXXXX XX XXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXX
  XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Confirmar Eliminación') XXXXX
          XX XXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'¿Está seguro de que desea eliminar el servicio')  XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
               gettext(u'Cancelar')
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
               gettext(u'Eliminar')
            XXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXX XXX XXX
XXXXXXX
XXXXXXXXXX XXXXXXXXXX X
  XX X XXXXXXXXXX XXXXXXXXXXXXXXXX X
  XXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
X

XXXXXXXXXX XXXXXXX X
  XXX XXXX X XXXXXXXX XXXX X
  XXX X XXXXXXXX XX X
X

XXXXXXXXXX XXXXXXXXXXX X
  XX X XXXXXXXXXX XXXXXXXXXXXXXXXXXX X
  XXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXX X
X

XXXXXXXXXX XXXXX X
  XXX XXXX X XXXXXXXXXX XXXXXXXXXXXXXXXX X
  XXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXX X
X

XXXXXXXXXX XXXXXXX X
  XX X XXXXXXXXXX XXXXXXXXX XXXXXXXX XX X
  XXXX X XXXXXXXXXX XXXXXXXXX XXXXXXXX XX X
X

XXXXXX X
  XXXXXXXXX XXXXXXXXX
  XXXXXX XXXXX
  XXXXXXX XXXXX
  XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXX XX XXXX XXXXX XXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXX XX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXX XX XXXX XXXXX XXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXX XX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXX XX XXXXX XXXXX XXXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXXX XXXXX XXXXXX
  XXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXX
X

XXXXXXXXXX X
  XXXXXXXXX XXXXXXXXX
  XXXXXX XXXXX
  XXXXXXX XXXXX
  XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXX XX XXXX XXXX XXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXX XX XXXX XXXXX XXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXX XX XXXXX XXXXX XXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXX XX XXXXX XXXXX XXXXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXXX XXXXX XXXXXX
  XXXXXXXXXX XXXXXXX XX XXXXXXXXXXX XXXXXXXXX
X

XXXXXXX X
  XXXXXXXXX XXXXXXXXX
  XXXXXX XXXXX
  XXXXXXX XXXXX
  XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXX XX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXX XX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXXX XXXXX XXXXXX
  XXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXX
X

XXXXXXXXX X
  XXXXXXXXX XXXXXXXXX
  XXXXXX XXXX
  XXXXXXX XXXX
  XXXXXXXXXXX XXXXXXXX
  XXXXXXXXXXXXXX XXXX
  XXXXXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXXXX
X

XXXXXXXXXX X
  XXXXXXXXX XXXXXXXXX
  XXXXXX XXXX
  XXXXXXX XXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXX XXXX
  XXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXXX
X

XXXXXXXXXXXXX X
  XXXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXXXXXX X
  XXXXXXXX XXX
X
XXXXXXXX

XXXX XXXXXXXXXX XXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
  XX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXX X XXXXX

  XX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XX XXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXXXXXX XXXXXXXXXXXXXXX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXX XX X
      XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX XX
                          XXXXXXXXXXXXXXXXXXXXXXXXX XX
                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX

      XXXXX XXXXXXX X XXXXXXXXXXXX XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX

      XX XXXXXXXXX X
        XXXXXXXXXXXXXXXXXX X XXXXXXXX
        XXXXXXXXXXXXXXXXXX X XXXX
        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
      X XXXX X
        XXXXXXXXXXXXXXXXXX X XXXXXX
        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
      X
    XXX
  X

  XX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XX XXXXXXXXXX X XXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXX X X XX X X XXX XXXX X
      XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXX X XXXX
      XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXX X XXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X X X XXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
  X

  XXXXXXXX XXXXXXXXXXXXXXXXXX XX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX X X X XXXXX
    XXXXXXXXXXXXXXXXXXX X X X XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXX XX X
      XXXXXXXXXXXXXXXXXXX
    XX XXXXX
  X

  XX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXXXXXXX X XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX

  XXXXXXXXXXXXXXXXXX X XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX X XXXXX
  XX

  XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXX

    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXX XXXXXXX
      XXXXXXXX X
        XXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XX
    XX
    XXXXXXXXXXXXXX XX X
      XX XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXX
      X XXXX X
        XXXXXXXXXXXX XX XXXXXXXX XX XXXXXXXXXXX
      X
    XX
    XXXXXXXXXXXX XX X
      XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXXX XX XXXXXXXX XX XXXXXXXXXXX
    XXX
  XX

  XX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX XXX XXX X XXXXXX
    XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX XXX XXX X XXXXXX
    XXX
  X

  XX XXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  X

  XX XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  X

  XX XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  X

  XX XXXXX XXXXXXXXX XXXX XXX XXXXXXXX XX XXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
      XX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
          XXXXXXXXX X XXXXXXXXXX
          XXXXXXXXX X XXXXXXXX
        XX
      X
    XXX
  XXX

  XX XXXXX XXXXXXXXX XXXX XX XXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XX XXXXXX XXX XXXXXXXXX X
      XXXXXXXXXXXXXX
    X
  XXX

  XX XXXXXX XXXXX XX XXXXX XXXX XXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XX XXXXXXXXX XXX XXXXX X
      XXXXXXXXXXXXXX
    X
  XXX

  XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX

  XX XXXXXXXXXXX XXXXXXXXXX
  XXXXXXXXXXXXXX XX X
    XXXXX X X XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
    XXXXX X X XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX XXX
  XX XXXXXX
XXX
XXXXXXXXX

BBBBBBBB
