BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBBB

BBBBB BBBBBX XXXXXXXX XX XXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XX XXXXX XXXXXXXXXX XXXX XXXX XXXXXX XX
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
        XXXXXX XXXXX
        XXXXXXXXXXXX XXXX
    X

    XX XXXXXXXXXX XXXXXXXXX XXXXXXXX XX
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXXX X XXXXX
        XXXXXXXX XXXXX
    X

    XX XXXXXX XXXXXXXXXXX XX
    XXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXXX XX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
    X

    XXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXX XX
    X

    XX XXXXXXXX XXXXXXXXX XX
    XXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
    X

    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXX
        XXXXXXX XXX XXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXXX
    X

    XXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXX XXX XX
    X

    XXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
    X

    XX XXXXXXXX XX XXXX XX
    XXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXX XXXX
        XXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
    X

    XXXXXXXXXX X
        XXXXXXXXXXX XXXXXX
        XXXXXXX XXX XXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXX X
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXX XXXXXXX
    X

    XX XXXXX XXXXXX XX
    XXXXXXXXX X
        XXXXXXXXXXX XXXXXX
        XXXXXXX XXX XXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXX
        XXXXXXXXXXXXXXX XXXX
    X

    XXXXXXXXXXXXX X
        XXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXXX XXXXXXXX
    X

    XXXXXXXXXXXXX XX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXX XXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
    X

    XXXXXXXXXXXXX XX X
        XXXXXXXX XXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
    X

    XXXXXXXXXXXXX XXXXX XXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X

    XX XXXXXX XXXXXXX XX
    XXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXX X
    XXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXX X
    XXXXXXXXXX X XXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXX X
    XXXXXXXXXXX X XXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXX X

    XX XXXXXXXXXX XX
    XXXXXX XXXXXXXXXXX XXXXXX X
        XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXX XXXX
        X
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXX XXXXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX
                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXX XXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
                    XXXX
                        XXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXX
                        XXXXXXXXXX XXXXXX
                    XXXXX
                XXXXXXXX
                XXXXXXX
                    BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBB
                    XXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX
                        XXXXFFFFFFFFFFFFFFFXXXXX
                        XXXXFFFFFFFFFFFFFFFXXXXX
                        XXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXXXXXXXXXX
                        XXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBB BB BB
                                XXXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXXXXX
                            BBBB BBBBBBBBBBBBBBBBBBBBBBBB BB BB
                                XXXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXXXXX
                            BBBB
                                XXXXX XXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXXXXX
                            BBBBB
                        XXXXX
                    XXXXX
                    BBBBB
                    XXXX
                        XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXX
                    BBBBBB
                XXXXXXXX
            XXXXXXXX
        XXXXXX

        XXXX XXXXXX XXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX
                        XXXX
                            XXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXX
                        XXXXX
                    XXXXXXXX
                    XXXXXXX
                        BBB BBBBBBBBB BB BBBBBBBBBBBBBBB
                        XXXX
                            XXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXFFFFFFFFFFFFFFFXXXXX
                            XXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXXXXXXXXXX
                        XXXXX
                        BBBBBB
                    XXXXXXXX
                XXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX
                        XXXX
                            XXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXX
                            XXXXXXXXXX XXXXXX
                            XXXXXXXXXXXXXXXXX
                        XXXXX
                    XXXXXXXX
                    XXXXXXX
                        BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
                        XXXX
                            XXXXFFFFFFFFFFFFFFFFXXXXX
                            XXXXFFFFFFFFFFFFFFFFXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXXXXXXXXXX
                            XXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXXXXXXXXXX
                        XXXXX
                        BBBBBB
                    XXXXXXXX
                XXXXXXXX
            XXXXXX
        XXXXXX

    XXXXXX
XXXXXX

XXXXXXXX
XX XXXXXXX XXXXXXXXX XXXXXXXX X XXXXXX XXX XXXXX
XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX XXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXX
    XXXXX X
        XXXXXXX XBBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBXFFFFFFFFFFFFFFFFXBB BBB BBBBBBBBBBBBXBBBBBBBBBBBXX
        XXXXXXXXX XX
            XXXXXX XXXXXXXXXXX
            XXXXX XBBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBXBBBBBBBBBBBXX
            XXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXX X
        XX
    XX
    XXXXXXXX X
        XXXXXXXXXXX XXXXX
        XXXXXXXX X
            XXXXXXX X XXXXXXXX XXXXX XX
            XXXXXXXX X
                XXXXXXXXXX X
                    XXXXXX XXXXXXXXXXXXXXXXX X
                        XXXXXX XXXXXXXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X
                X
            X
        XX
        XXXXXXX X
            XX X
                XXXXXXXXXXXX XXXXX
                XXXXXX X
                    XXXXXXXXX XXXXXXXXXXXXXXX X
                        XXXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXX
                    X
                X
            X
        X
    X
XXX

XX XXXXXXX XXXXXXXXX XXXXXXXX X XXXXXX XXX XXXXX
XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX XXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXX
    XXXXX X
        XXXXXXX XBBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBXFFFFFFFFFFFFFFFFXBB BBB BBBBBBBBBBBBXBBBBBBBBBBBXX
        XXXXXXXXX XX
            XXXXXX XXXXXXXXXXX
            XXXXX XBBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBXBBBBBBBBBBBXX
            XXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXX X
        XX
    XX
    XXXXXXXX X
        XXXXXXXXXXX XXXXX
        XXXXXXXX X
            XXXXXXX X XXXXXXXX XXXXX XX
            XXXXXXXX X
                XXXXXXXXXX X
                    XXXXXX XXXXXXXXXXXXXXXXX X
                        XXXXXX XXXXXXXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X
                X
            X
        XX
        XXXXXXX X
            XX X
                XXXXXXXXXXXX XXXXX
                XXXXXX X
                    XXXXXXXXX XXXXXXXXXXXXXXX X
                        XXXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXX
                    X
                X
            X
        X
    X
XXX
XXXXXXXXX
BBBBBBBB
