BBBB BBBBBB

XXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XX XXXXXXXXXX XXX
XXXX XXXXX XXXXXXXXX XXXXXX X XXXXXX XX X XXXXXXX X XXX X XXXXXXX XXX


XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX


XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX


XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX


XXXXXXXX
  XX XXXXXXXXXXXXX XXXXXX XXXX XX XXXXXXXXXX XX XXXXXXXXXX
  XXXXXXXXX X XXXXXXXXX XX XXX
  XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XX XXX

  XX XXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXX
  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
  BBBBB

  XX XXXXXXXXXXXXX XX XXXX
  XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XX XXX
  XXXXXXXXXXXXXXXXXXXXXXXX X XFFFFFFFFFFFFXX
XXXXXXXXX
