BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBXXXXXXXXXX X XXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX X XXXXXXX XXXXX XX
    XXXXXXXXXXX X XXXXXX X XXXXXX XXXXXXXXXXXXX X XX
    XXXXXXXXXX X
      XXXXXXX X XXXXXX XX XX
      XXXXXX X XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XX
      XXXXX X XXXXXX XXX XX
      XXXXX X XXXXXXX XXXXX XXXXXX XXX XX
      XXXXXX X XXXXXXX XXXXX XXXXXX XXXXXXXXXX XXXXXXXXX XXX X

    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX
X
XXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXX XXXXXX
    XXXXXXX XXXXXXXXXXXXX X XXXX XXXXXXXXXXX
X
XXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXX XXXX XXXXXXXX XXXXXXXXXX
X
XXXXXXXXXX XXXXXXXXX X
    XX X XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX X XXX XXXXXXXXXXX X
    XXXX X XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX X XXXX XXXXXXXXX X
X
XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXX X X XXXX XXXXXXXX X X XXXX XXXXXXXX X X XXX XXXXX
X
XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXXX XXXXXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXX XXXXX
X
XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXXXXXXX XXXXXXXXXXXX
X
XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXX XXXXX XXXXXXXXX XXXXX
X
XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXX
    XXXXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXX
X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBBB
XXXXXXXX
  XXXXX XXXXXX X X
    XXXXXXXXXXXX XX XXXXXXXX
    XXXXXXXXX XXXXXXXXX XXXXXXXXX X XXXXXXXXX XX XX XXXX XXXXXXXX
    XXX XXXXXXX XX XXXXXXXX XX XXXXXXXXX
    XXXXXXXXXXX X XXXXXX XXXXXX XXXXX XXX XXXXXXX
    XXXXXXXX X XXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXX XXXX XXX XXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXX XXXXX XX XXXXXXXXXX XX XX XXXXXXXXXXXXX
  XX
  XXX X X XX
  XXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
    X X XX X XX X XXXXXXXXXXXXXX
  XX XXXXXX
XXXXXXXXX
BBBBBBBB
