BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBBB
XXXXXXX
  XX XXXXXXX XX XX XXXXXXXXX XXXX XXXXXXXXX XX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXXXX
    XXXXXXXXXXXXXXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXXX
    XXXXXXXXXXX XXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
  X

  XXXXXXXXXX XXXXXXXXXXXXXXXXX X
    XX X XXXXXXXXXXXXXXXXXXXX XX XXXX X
    XXX X XXXXXXXXXXXXXXXXXXXX XXXX XXXX X
    XXXX X XXXXXXXXXXXXXXXXXXXX XX XXXX X
  X

  XX XXXXXXXXXX XX XX XXXXXXXXX XX
  XXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXX
    XXXXXXXX XX
  X

  XXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXX XXXX
    XXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXXX XX XXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXX
  X

  XX XXXXXXXXXX XXXX XXXXXXXXXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXX
  X

  XXXXXXXXXX XXXXXXXX X
    XXX XXXX X
      XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
      XXXXXXXX XXXX
    X
    XXX X
      XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXXXX XX
    X
  X

  XX XXXXXXXXXX XXXXXXXXX XXX XXXXXXX XXXXXXXXXXXX XX
  XXXXXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXXXX XXX
    XXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXX X XXXXX
  X

  XX XXXXXX XXXXXXXXX XXX XXXXXXX XX XX XX
  XXXXXXXXXXXXXX X
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXX XXXXXXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXXX XXXX
  X

  XXXXXXXXXX XXXXXXXXXXXXXXXXX X
    XX X XXXXXXXXXXXXXXXXXXXX XX XXXX X
    XXX X XXXXXXXXXXXXXXXXXXXX XXXX XXXX X
    XXXX X XXXXXXXXXXXXXXXXXXXX XX XXXX X
  X

  XX XXXXX XX XXXXXXXX XXXXXXXXXXX XX
  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX
      X X XXXX XXXXXXX XXXX XXXX XXXXX
      XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XXXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXX
      XXXXXXX XXXX XXXX XXXXX
      XXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXX XX XXXXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXX XXXXXXXX X
    XX X XXXXX XXXXXX X
    XXX X XXXXX XXXXX X
    XXXX X XXXXX XXXXX X
  X

  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXX XXXX XXXXXXX
    XXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX
      X X XXXX XXXXXXX XXXX XXXX XXXXX
      X X X XXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXX XXXX XXXX XXXXX
  X

  XX XXXXX XXXXXXXXX XXX XXXXXXX XX XX XX
  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXX XXXXXXX
    XXXXXXXXXXX
      X X XXXX XXXXXXX XXXX XXXX XXXXX
      XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
  X

  XXXXXXXXX XX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXX
    XXXXXXXX XXXXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
  X

  XXXXXXXXX XX X
    XXXXXXXX XXXXXX XXXXX
    XXXXXXXXXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
  X

  XXXXXXXXX XXXXXXXX XX X
    XXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXX
  X

  XX XXXXXXX XXX XXXXXXX XX XX XX
  XXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXXX XXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXX
      X X XXXX XXXXXXX XXXX XXXX XXXXX
      XXXXX X X XXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XXXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXX
      XXXXXXXXX XXXX XXXX XXXXX
      XXXXXXXXXXXXX
    XXXXXXXXXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXX
  X

  XXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXX
      X X XXXX XXXXXXX XXXX XXXX XXXXX
      X X XXXX XXXXXXX XXXX XXXX XXXXX
      XXXXX X X XXXX XXXXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
  X

  XX XXXXXXX XXX XXXXXXX XX XX XX
  XXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXX XXXXX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXXXXXX XXXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXX
  X

  XXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXXX
  X

  XX XXXXXXXXXX XXXXXXXXX XX
  XXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXX XXXXX
    XXXXXXX XXXX XX
  X

  XXXXXXXXXXXXXX X X
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXX XXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
  X

  XXXXXXXXXXXXXX XXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXX XXXXXX XXXXXXX
  X

  XX XXXXXX XXX XXXXXXX XX XX
  XXXXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXX
    XXXX XXXXX
    XXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXXX
    XXXXXX XXXX
    XXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXX XXXXXXXX XX XXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXX
  X

  XXXXXXXXXX XXXXXXXX X
    XXX XXXX X XXXXXXXX XX X
    XXX X XXXXXXXX XXXX X
  X

  XXXXXXXXXX XXXX X
    XX X XXXXXXXXXX XXXXXXXXXXXXX X
    XXXX X XXXXXXXXXX XXXXXXXXXXXXXXX X
  X

  XX XXXXXXXXXX XX
  XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXXXXXXXX X
      XXXXXXXXXX XXXXXXX
      XXXXXXXXXXXXXXX XXXX
    X

    XXXXXXXXXXXXXXXXXX X
      XXXXXXXX XXXXX
    X

    XXXXXXXXX XXX
    XXXXXXXXX XX X
      XXXXXXXX XXXXXX XXXXXXX
      XXXXXXXXXX XXXXXXX
    X
  X
XXXXXXXX

XXXX XXXXX XXX XXXXXXX XX XX XXX
XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXX XX XX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
  XXXXXX

  XXXX XXXXXX XXX XXXXXXX XX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXX XXXXXXXXX
  XXXXXX

  XXXX XXXXXXXXXX XXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX


    XXXX XXXXX XX XXXXXXXX XXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXX
                 XXXXXXXX
                 XXXXXXXXXXXXXXXX
                 XXXXXXXX
                 XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXX
            X XXXXXXXX XX XXXXXX XXXX XXXXXX
          XXXXXX
        XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
          X XXXXXX
        XXXXXXXXX
        BB BBBBBBBBBBBBB
        XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          X XXXXXXX
        XXXX
        BBBBB
      XXXXXXX

      BB BBBBBBBBBBBBB
      XXXX XXXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
          X XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
          X XXXXXXXXXXXXXXXXXXXXXXXXXXXX FFFFFF
        XXXX
      XXXXXX
      BBBBB
    XXXXXX

    XXXX XXXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXX
          XXXX
            XXXXX XXXXXXXXXXX
            XXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXX
            XXXXX XXXXXXXXXX
            XXXXX XXXXXX XXXXXXXXXX
            XXXXX XXXXXXXXXXXXX
          XXXXX
        XXXXXXXX
        XXXXXXX
          BBB BBBBBBBB BB BBBBBBBBBBB
          XXXX
            XXXX
              XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFXXXXXXX
            XXXXX
            XXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFXXXXXXX
            XXXXX
            XXXX
              BB BBBBBBBBBBBBBBBBBBBBBBB
                XXXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB B BBXXXXXXXXXXXXBBBB BBBBBBBBBBBBBBBBBBBBBBB B BBXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXBBBBBXX
                  
                XXXXXXX
              BBBB
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              BBBBB
            XXXXX
            XXXX
              BB BBBBBBBBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXXXX
              BBBB
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              BBBBB
            XXXXX
            XXXX
              XXXX XXXXXXXXXXX XXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX
                   XXXXXXXXXXXXXXXXXX XXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX
                   XXXXXXXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX
            XXXXX
          XXXXX
          BBBBB
          XXXX
            XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XX XX XXXXXXX XXXXXXXXX XXX XXXXXXXXX XXX XXX XXXXXXXXX XX XXXXXXXXXXXXX
                XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                  X XXXXXXXXX XXXXXX XXXXXXXX
                XXXX
              XXXXXX
            XXXXX
          XXXXX
          BBBBBB
        XXXXXXXX
      XXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXX XXXXXXXXX XXX
    BB BBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXBB BBBBBBBBBBBBBXXXBBBBBXX
          X XXXXXXX
        XXXX
        XX XXXXXXXXXXXXBB BBBBBBBBBBBBBXXXBBBBBXX
          XX XXXXXXXX
        XXXX
      BBBBB

      XXXXXX
        X XXXXXX  XX 
      XXXXXXX

      BB BBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXBB BBBBBBBBBBBBBXXXBBBBBXX
          XXXXXXXXX XX
        XXXX
        XX XXXXXXXXXXXXBB BBBBBBBBBBBBBXXXBBBBBXX
          XXXXXX X
        XXXX
      BBBBB
    XXXXXX
    BBBBB

    XXXX XXXXX XXXX XXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        X XXXXXXX XXXXX XXXXXXXX
      XXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXXXXXX
XX XXXXXXX XX XX XXXX XXXXXXXXX XXX XXXXXXXX XX XXXXXX XXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
  XXXXXXXXXXXXXX XXXXXXX XX XX XXXX XXXXXXXXX XXXXXXXXXXX
  XXXXXXXXXXXXXX XXXXXX XX XXXXXXX XXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XX XXXXXXXXXX
  XXXXXXXXXXXXXX XXXXXXX XX XXXXXXXX XX XXXXXX XXXX XXXXXXXXXXX

  XX XXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXX XX X
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXX X XXXX
    XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXX X XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X X X XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXX XXXXXXXXX XXXXXXX XX XX XXXXXXXXX
    XXXXXXXXXXXXX XX X
      XX XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X
    XX XXXXXX
  XX XXXXXX

  XX XXXXXXX XX XXXXX XX XX XXXXX
  XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX
  XXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXX X XX X XXXX XXXXXXX XXXX XXXX XXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXX
  XXX

  XX XXXXXXX XX XXXXXXXX XX XXXXXX XXXX
  XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXX

  XX XXXXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXX XX XXXXXXXX XXXXXXXXX X XXXXXXXXXXXXXXX

    XX XXXXXXX XXXXXXXX XXX XXXXX XX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXX X XX X XXXX XXXXXXX XXXX XXXX XXXXXX
      XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXX X XX X XXXX XXXXXXX XXXX XXXX XXXXXX
      XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
    XXX

    XX XXXXXXXX XX XXXXXX XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXX X XXXXXXXXXXXXXXXXXX

      XX XXXXXXX XXXXXXXXX XX XXXXXXXXX
      XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXX X XX X
        XXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX X XX X XXXX XXXXXXXXX XXXX XX XXXXXX
      X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXX XX XXXXXX XXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX X XX X XXXX XXXXXXX XXXX XXXX XXXXXX
      X

      XX XXXX XXXXXX XX XXX XX XXXXX X XXXXXXXXXX X XX XX XXXXX XXXX
      XX XXXXXXXXXXXXX XX X XX XXXXXXXXXXXX XXX XX X
        XX XXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXX X XXXXXXXXXXXXX XX X
          XX XXXXXXXXXXXXX XX XX X
            XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX X XX X XXXX XXXXXXX XXXX XXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          X XXXX XX XXXXXXXXXXXXX XXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX X XX X XXXX XXXXXXX XXXX XXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          X
        XX XXXXX XX XXXXX XX XXXXXXXX
      X XXXX X
        XX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXX XXXX X XXXXXXXXXXXXX XXX XXXX XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX X XX X XXXX XXXXXXXXX XXXX XX XXXXXX
      X
    XXX
  X XXXX X
    XXXXXXXXXXXXXXXX XXXXX XX XXXXXXXX XX XXXXXXXXXXXXX
  X

  XX XXXXXXX XX XXXXXXXX XX XXXXXX XXXX
  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX

    XX XXXXXXX XXXXXXXXX XX XXXXX
    XXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXX XXXXXXXX XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXX XXXXXX
      XXXXXXXX X
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      X
    XX
    XXXXXXXXXXXXXX XX X
      XX XXXXXXXXXXXXXX X
        XXXXX XXX XXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
      X
      XXXXXX XXXXXXXXXXXXXXXX
    XX
    XXXXXXXXXX XX X
      XX XXXXXXX XX XXXXXXXXX XXXX
      XXXXX XXXXXX X XXX XXXXXXXXXXXX
      XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX

      XX XXXXXXXXXX XXXXX XX XXXXXXXXX
      XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX

      XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
      X

      XX XXXXXXXXXX XXXXXXX XX XXXXXXXX
      XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX X
        XX XXXXXX XX XX XXXXXX XX XXXXXXX X XXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X

      XX XXXXXXXXXX XXXXXXXXXX
      XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
      X

      XX XXXXXXX XXXXXXXXX XX XXXXX
      XXXXXXXXXXXXXXXXXXXX

      XX XXXXXXXXXX XXXXXX XX XXXXXXXX
      XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXX X
        XX XXXXXXXXXXXXX XX XX X
          XXXXX XXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX
          XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXX XXXXXXXXXX X XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
        X XXXX X
          XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXX XXX XXXXXXXXX XXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
        X

        XX XXXXXXX XXXXXX XXXXXXX XX X XXXXXXXX
        XXXXXXXXXXXXX XX X
          XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXX XX XXXXXX XXXX XXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XX XXXXXX
      X

      XX XXXXXXXXXX XXXXXXX XX XXXXX X XXX XXXXXX XXXXX
      XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXX X XX X XXXX XXXXXXX XXXX XXXX XXXXXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXX
      XXX

      XX XXXXXXXXXX XXX XXX XXXXXXXX XX XXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXX

      XX XXX XX XXXXX
      XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXX
    XX
    XXXXXXXXXXXX XX X
      XXXXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXX
      XXXXXXXXXXXXXXXXXXXX

      XX XXXXXXX XXXXX XX XX XXXXXX
      XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXX XX XX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXX XX X
          XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXX XX XXXXXX XXXX XXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XX XXXXXX
      X
    XXX
  X

  XX XXXXXXX XXXX XXXXXXX XXXXXXXXX XX XXXXX
  XXXXXXXX XXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXXX X
      XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXX X X
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXX
            X XXXXXXXX XX XXXXXX XXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXX XXXXXXX XXXXX XXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XX XXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXX XXXXXXXXXXX
          XXXXXX
        XXXXXX
      XX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XX XXXXXXXXXXX
  X

  XX XXXXXXX XXXX XXXXXXX XXXXXXXXX XX XXXXX
  XXXXXXXX XXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    X
  X
XXX
XXXXXXXXX
BBBBBBBB
