BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBB
BBBB BBBBBBBBBBB

BBBBB BBBBB gettext(u'Password Reset Email Sent')  X XXXXXXXBBBBBBBB

BBBBB BBBBBBBBBB
  XXXXXXX
    XX XXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXX XX
    XXXXXXXXXXXXXX X
      XXXXXXXXXXX XXXXXX
      XXXXXXX XX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXXXX
      XXXXXXXXXXXXXXXX XXXX XXXXX
      XXXXXXXXXX XXXXXXXXXXXXX XXX XXXX XXXXXXXXX
      XXXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXX XXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
    X

    XXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXX XXX
      XXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXXXX
      XXXXXXXXXXXXX X XXXX XXXXXXXXXX
      XXXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXX XXXXXXXXX
      XXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX
      XXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXX XXX
      XXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXX XX
      XXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
      XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXXXXXXX XXXXXXXX
      XXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXX
      XXXXXXXXXXX XXXXXXXXX XXXX XXXXX XXXXXXXXXX XXXX XXXXX
    X

    XXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXXX XXXXX
    X

    XXXXXXXXXXXXXXXX X
      XXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX
      XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXXX XXXXXXX
      XXXXXXX XXXX XX
      XXXXXXXXXXX XXXXX
    X

    XXXXXXXXXXXXXXXX XX X
      XXXXXX XXXXXXXX
      XXXXXXXXXX XXXXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXXXXXXX XX X
      XXXXXXXXXXX XXXXX
      XXXXXXXX XX
      XXXXXXX XX
    X

    XXXXXXXXXXXXXXXX XX X
      XXXXXX XXXXXXXX
      XXXXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXXXX XXXXXXX
      XXXXXXXXX XXXXXXXXX
    X

    XXXXXXXXXXXXXXXX XXXXXXXXX X
      XXXXXXXX XXXX
      XXXXXX XXXXXXXX
      XXXXXXXXXXXX XXXXX
      XXXXXXXXX XXXXXXXXX
      XXXXX XX
    X

    XXXXXXXX
      XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXXXXX
    X

    XX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
      XX
        XXXXXXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXX XXXXXXXXXX
      X
      XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXX
      X
    X

    XX XXXXXXXXXX XX
    XXXXXX XXXXXXXXXXX XXXXXX X
      XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXX XXXXX
        XXXXXXXX XXXX XXXXXXX
      X

      XXXXXXXXXXXXX XX X
        XXXXXXXXXX XXXXXXX
      X
    X
  XXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
  XXXXXX

  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX gettext(u'Email sent successfully!') XXXXX
    XXX
       gettext(u"\n      If an account exists with the email you entered, we've sent password reset instructions.\n      Please check your inbox and follow the link to set a new password.\n      ") 
      SS SS SSSSSSS SSSSSS SSSS SSS SSSSS SSS SSSSSSSS SSSSS SSSS SSSSSSSS SSSSS SSSSSSSSSSSSS
      SSSSSS SSSSS SSSS SSSSS SSS SSSSSS SSS SSSS SS SSS S SSS SSSSSSSSS
      
    XXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'What to do next') XX
      XXXX gettext(u'What to do next:') XXXXX
      XXXX
        XXXX gettext(u'Check your inbox (and spam folder)') XXXXX
        XXXX gettext(u'Open the email from eGarage') XXXXX
        XXXX gettext(u'Click the reset link') XXXXX
        XXXX gettext(u'Choose a new password') XXXXX
      XXXXX
    XXXXXXXXXX

    XX XXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBFFFFFFFFFFFXX
         gettext(u'Back to login') 
      XXXX
    XXXX

    XX XXXXXXXXXXXXXXX
       gettext(u'Need help? Contact our support team.') 
    XXXX

    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
       gettext(u'Redirecting automatically in')  XXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'seconds…') 
    XXXX
  XXXXXXX
BBBBBBBB

BBBBB BBBBBBBB
  XXXXXXXX
    XXXXXXXXXXXX
      XX XXXXXXX XXXXXXXXXXXXX XXXX XX XXXXXXX X XXXXXXXX XXXXXXXXX
      XXXXX XXXXXX X XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXX X XX
      XXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXX X XBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBFFFFFFFFFFFXX

      XX XXXXXXXX XXXXXXX  XX XXX XXXXXXXXXXXXX XX XXXXXXXXXXXXX

      XXXXX X X XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX
        XX XXXX XXXXXXXXXXXXXX X XXXXXXXXXX
        XX XXXXXXXXXX XX XX X
          XXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXX X XXXXXXX
        X
      XX XXXXXX
    XXXXX
  XXXXXXXXX
BBBBBBBB
