BBBB BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXX gettext(u'Welcome to eGarage USA') XXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
         XXXX X
       XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
       XXXXXXXXXXXX XXXX XXX XXXXXXXXXXX
       XXXXXX XXXXXXXX
       XXXXXXXXXXX XXXXXX
       XXXXXXXXXXX XXXXXXX
     X

     XX XXXXXXXXXXX XXXXXXXXXXXXXX XX
     XXXXXXXXXXXXXXXX X
       XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
       XXXXXXXXXXXXXXX XXXXXXX
     X

     XXXXXXXXXX X
       XXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXX
       XXXXXXXXXXXXXXX XXXXXXX
     X

     XXXXXXXXXXXXX X
       XXXXXXXXXXXX XXXX XXX XXXXXXXXXXX
       XXXXXXXXXXXX XXXX
       XXXXXXXXXXXXXXX XXXXXXX
     X

     XXXXXXXXXXXXXXX X
       XXXXXXXXXXXX XXXX XXX XXXXXXXXXXX
       XXXXXXXXXXXX XXXX
       XXXXXXXXXXXXXXX XXXXXXX
     X

    XXXXXXXXXXXXXXXX X
      XXXXXXXXXXXX X X XXXX XXXXXXXX XXXX XXXX XXXXX
    X

    XXXXXXXXXXXX XXXXXX X
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXX XXX XXXXXXXX XXXX XXXX XXXXX XXXXXX
      XXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXXXX
      XXXXXXX XXX XXXXX XXXXXXXX XXXX XXXX XXXXX
      XXXXXXXXXXX XXX XXXX XXXXX
      XXXXXXXXXXX
        X XXX XXXX XXXXXXXX XXXX XXXX XXXXXX
        XXXXX X XXX X XXXXXXXXX XXXX XXXX XXXXX
      XXXXXXXXX XXXXXXXXX
      XXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
      XXXXXXXX XXX
      XXXXXXXXX XXXXXXXXX
      XXXX XX
      XXXXX XXXXXX
      XXXXXX XXXXX
      XXXXXXX XXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
      XXXXXXXXXXX XXXX XXXX XXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
      XXXXX XXXXX
    X

    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
      XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX
      XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXXXXXXXX
        X XXXX XXXX XXXXXXXX XXXX XXXX XXXXX
        X X X XXX XXXXXXXX XXXX XXXX XXXXX
        XXXXX X XXX X XXXXXXXXX XXXX XXXX XXXXX
    X

    XX XXXXXXXX XXXXXXXXXX XXX XXXXXXX XXXX XX
    XXXXXXXXXX X
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX XXX XXXXXXXX XXXX XXXX XXXXX XXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXX
      XXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXXXX
      XXXXXXX XXX XXXXX XXXXXXXX XXXX XXXX XXXXX
      XXXXXXXXXXX XXX XXXX XXXXX
      XXXXXXXXXXX
        X XXXX XXXX XXXXXXXX XXXX XXXX XXXXX
        X X XXXX XXXXXXXX XXXX XXXX XXXXX
        XXXXX X XXX X XXXXXXXXX XXXX XXXX XXXXXX
      XXXXXXXXX XXXXXXXXX
      XXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXXXXXXXX X
      XXXXXXXX XXX
      XXXXXXXXX XXXXXXXXX
      XXXX XXXXX
      XXXXX XXXXX
      XXXXXX XXXXX
      XXXXXXX XXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX
      XXXXXXXXXXXXXX XXXXXXX
      XXXXXXXX XXX
      XXXXXXXX XX
      XXXXXXXXXXX XXXXXXX XXXX XXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXX XXXX
    X

    XXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX
      XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXXXXXXXX
        X XXXX XXXX XXXXXXXX XXXX XXXX XXXXX
        X X XXXX XXXXXXXX XXXX XXXX XXXXX
        XXXXX X XXX X XXXXXXXXX XXXX XXXX XXXXX
    X

    XX XXXXXXXX XX XXXXXXXX XXX XXXXXX XX XXXXX XX
    XXXXXXXXXXXX X
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX XXX XXXXXXXX XXXX XXXX XXXXX XXXXXX
      XXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXXXX
      XXXXXXX XXX XXXXX XXXXXXXX XXXX XXXX XXXXX
      XXXXXXXXXXX XXX XXXX XXXXX
      XXXXXXXXXXX
        X XXX XXXX XXXXXXXX XXXX XXXX XXXXXX
        XXXXX X XXX X XXXXXXXXX XXXX XXXX XXXXX
      XXXXXXXXX XXXXXXXXX
      XXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXX X
      XXXXXXXX XXX
      XXXXXXXXX XXXXXXXXX
      XXXX XX
      XXXXX XX
      XXXXXX XX
      XXXXXXX XX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
      XXXXXXXX XX
      XXXXXXXXXXX XXXXXXX XXXX XXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXX XX
    X

    XXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXXXX
        X XXXX XXXX XXXXXXXX XXXX XXXX XXXXXX
        X X X XXX XXXXXXXX XXXX XXXX XXXXX
        XXXXX X XXX X XXXXXXXXX XXXX XXXX XXXXX
    X

    XXXXXXXXXXX X
      XXXXXXXXX XXXXXX
      XXXXXXX XXXXXXX
      XXXXXX XXXXXXX
      XXXXXXXX XXX
      XXXXXXXX XXXXX
      XXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXX
    X

    XXXXXX XXXXXXXXXXX XXXXXX X
      XXXXXXXXXXX X
        XXXXXX XXXXXXX
        XXXXX XXXXXXX
        XXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
      X
    X

    XXXXXXXXXXX X
      XXXXXXXXXXX XXXXXXXXX XXXX XXXXX
      XXXXXX XXXXXXXX
      XXXXXXX XXXXXXXXXXXXX X XXXX XXXXXXXX XXXX XXXX XXXXXX
    X

    XXXXXXXXXXXXXXXXX X
      XXXXXXXXXX XXXXXXXXXXX
      XXXXXX XXXXXXXX
      XXXXXXX XXXXXXXXXXXXX X XXXX XXXXXXXX XXXX XXXX XXXXXX
    X

    XX XXXX XXXXXXX XX XXXXX XXX XXXXXXX XX
    XXXXXXXX X
      XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXX XXXX XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX XXXX XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXX XXXX XXXXX
      XXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXXXX
    X

    XXXXXXXXXX XXXXXXXXX X
      XX X XXXXXXXXXX XXXXXXXXXXXX XXX X
      XXXX X XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX X
    X

    XX XXXXXX XX XXXXXXX XX
    XXXXXXXXXXXXX X
      XXXXXXXXX XXXXXXXXX
      XXXX XX
      XXXXX XX
      XXXXXX XXXXX
      XXXXXXX XXXXX
      XXXXXXXXX XXXXXXX
      XXXXXXXX XXX
    X

    XXXXXXXXXXXX X
      XXXXXXXXX XXXXXXXXX
      XXXXXX XXXX
      XXXXXXX XXXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
      XXXXXXXXXX XXXXXXXXXXX XX XXXXXX XXXXXXXXX
    X

    XXXXXXXXXX XXXXXXXXXXX X
      XX X XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
      XXX X XXXXXXXX XX X
      XXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    X

    XX XXXXXXXXXX XXXXXXXXX XX
    XXXXXXXXXX X
      XXXXXXXXX XXXXXXXXX
      XXXX XX
      XXXXX XX
      XXXXXX XXXXX
      XXXXXXX XXXXX
      XXXXXXXXX XXXXXXX
      XXXXXXXX XXX
    X

    XXXXXXXXX X
      XXXXXXXXX XXXXXXXXX
      XXXXXX XXXX
      XXXXXXX XXXX
      XXXXXXXXXXX XXXXXXXX
      XXXXXXXXXXXXXX XXXX
      XXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXX XXXXXXXXX
    X

    XXXXXXXXXX XXXXXXXXXXXXXX X
      XX X XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX X
      XXX X XXXXXXXX XX X
      XXX X XXXXXXXX XX X
      XXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XX X
    X

    XX XXXXXX XX XXXXXXX XX
    XXXXXXXXXX X
      XXXXXXXXX XXXXXXXXX
      XXXX XX
      XXXXX XX
      XXXXXX XXXXX
      XXXXXXX XXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
      XXXXXXXXXX XXXX XX XXXXXX XXXXXXXXX
      XXXXXXXX XX
    X

    XXXXXXXXXX XXXX X
      XX X XXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
      XXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXX X
    X

    XX XXXXXXX XXX XXXXXX XXXX XX
    XXXXXXXXXXXX X
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
      XXXXXXX XXX XXXXX XXXXXXXX
      XXXXXXXXXXX X X XXXX XXXXXXXX XXXX XXXX XXXXX
      XXXXXXXXXXX XXX XXXX XXXXX
    X

    XXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXX X X XXXX XXXXXXXX XXXX XXXX XXXXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXX
    X

    XX XXXXXXX XXX XXXXXX XXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXX X
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX
      XXXXXXXXXXXXXXXX XXXX XXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXXXXXXXXXXXXX XXXXX
      XXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXX
    X

    XXXXXXXXXX XXXXXXXXXXX X
      XXX XXXX X XXXXXXXXXXXXXXXXXXXX XX XXXX X
      XXX X XXXXXXXXXXXXXXXXXXXX XXXX XXXX X
    X
  XXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXX XXXXXXXX XXX
  XXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Language') XXXXXXXX
      XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXX XXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXX XXXXXXXXXXXXXXXX
        XXXXXXXXX
      XXXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXX XXXXXXXX XXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX

  XXXX XXXXXX XX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXX

  XXXX XXXXXXXXXX XXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXX

  XXXX XXXXX XX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX

  XXXXX XXXXXXXXXXXXXXX XXXXXX
    XXXX XXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXX XXXXXXXX XXXX XXXX XXXXXXXX

             XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXX XXXXXX
          gettext(u'The #1 Auto Shop Platform in the USA') 
       XXXXX

             XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXX gettext(u'Trusted by mechanics across America. Real features. Bilingual support. No risk.') XXXX

             XXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
         XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX  gettext(u'Start Free Trial') XXXX
         XX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'See Pricing') XXXX
       XXXXXX
    XXXXXXXXXX

         XXXX XXXXX XXXXXX XXX XXXXXXXX XXX
     XXXX XXXXXXXXXXXXXXXXXXX
       XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX  gettext(u'Start Now') XXXX
     XXXXXX

    XXXX XXXXXXX XX XXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXX
             XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
         XXXXXXXX XXX XXXXXXXXXXX
       XXXXX
      XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                 XXXX XXXXXX XXXXXXXX XXX
         XXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
           XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
           XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
           XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
             XXXXXXX XX XXXXXXXX XXXXXXXXX XX XXXXXXXXXX XXXXXXX X XXXXXXXXX XXX XXXXXXXX
           XXXX
         XXXXXXXXXX
         XXXX XXXXXXXXXXXXX X XXXXXXXXXX XXX
         XXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
           XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
           XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
             XXXXXXXXX XXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XX XXXXX X XXXXXXXXXXXX XXXXXXXX
           XXXX
         XXXXXXXXXX
         XXXX XXXXXXX X XXXXXXXXXXX XXX
         XXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
           XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
           XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
             XXXXXX XXX XXXXXXXX XXXXXXXXXX XXX XXXXXXXX XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXX
           XXXX
         XXXXXXXXXX
         XXXX XXXX XX XXXXXXXXX XXX
         XXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
           XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XX XXXXXXXXXXXXXX
           XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
             XXXXXXXXX XXXX XXXXXXX XXXXXXXXX XXXXXX X XXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXX
           XXXX
         XXXXXXXXXX
      XXXXXX
    XXXXXXXXXX

    XXXX XXXXXXXX XXXXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
             XXXX XXXXXXX XXX
       XXXX XXXXXXXXXXXXXXXXXXXXXX
         XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX gettext(u'Management') XXXXX
        XXXX XXXXXXXXXXXXXXXXX XXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX
                     XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX gettext(u'Warranty Control') XXXXX
           XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Track guarantees by time or mileage with alerts and digital records.') XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX
                     XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX gettext(u'Profit Reports') XXXXX
           XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Know your earnings from services, parts, or both — in real time.') XXXX
        XXXXXX
      XXXXXX
             XXXX XXXXXXXXXXXXXX XXX
       XXXX XXXXXXXXXXXXXXXXXXX
         XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX gettext(u'Automation') XXXXX
        XXXX XXXXXXXXXXXXXXXXX XXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX
                     XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX gettext(u'Mechanic Performance') XXXXX
           XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Measure performance, job times and track top performers.') XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX
                     XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX gettext(u'Inventory Alerts') XXXXX
           XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Get notified when stock is low or inactive.') XXXX
        XXXXXX
      XXXXXX
             XXXX XXXXXXX XXX
       XXXX XXXXXXXXXXXXXXXXXXXXX
         XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX gettext(u'Client') XXXXX
        XXXX XXXXXXXXXXXXXXXXX XXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX
                     XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX gettext(u'Digital Documents') XXXXX
           XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Paperless work orders, check-ins, diagnostics and receipts.') XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX
                     XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX gettext(u'Customer Portal') XXXXX
           XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Clients can view invoices, service history and updates online.') XXXX
        XXXXXX
      XXXXXX
    XXXXXXXXXX

    XXXX XXXXXX XXXX XXXXXXX XXXXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXX XXXX XXXXXXXX XXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
                     XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX gettext(u'All-in-one Dashboard') XXXXX
           XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Everything you need in one place: jobs, inventory, clients, and more.') XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                 XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX gettext(u'Automated Reminders') XXXXX
         XX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
         XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Never miss a service or follow-up. Automated notifications for you and your clients.') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX
                     XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX gettext(u'Timeline of Success') XXXXX
          XXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
              XXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Register your shop in minutes') XXXXXXX
            XXXXX
            XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
              XXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Import your clients and inventory') XXXXXXX
            XXXXX
            XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
              XXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Start working smarter, not harder!') XXXXXXX
            XXXXX
          XXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                 XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX gettext(u'Real-time Analytics') XXXXX
         XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
         XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Visualize your business growth and make data-driven decisions instantly.') XXXX
      XXXXXX
    XXXXXXXXXX

    XXXX XXXXXXX XXXXXXXXXXXX XXX XXXXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXX
             XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
         XXXXXX XXXXXXX X XXX XXXXX XXXXX
       XXXXX

      XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
                     XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
           XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
           XX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX
            XXXXX XXXXXXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXX XXXXXXX XXXXXXXXXXXXX
          XXXXX
          XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX
            XXXXXXX
          XXXX
        XXXXXX

        XXXX XXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX X X XXXX XXXXXXXX XXXX XXXX XXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
            X XXXXXXXXXXX
          XXXXXX
                     XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
           XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
           XX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX X XXXXXXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX
            XXXXX XXXX XXX XXXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXX XX XXXXXXXXXXXXX
          XXXXX
          XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX
            XXXXXX XXXXXXXXX
          XXXX
        XXXXXX

        XXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                     XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
           XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
           XX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX
            XXXXX XXXX XXX XXXX XXXXXXXXXXXXXX
            XXXXX XXXXXXXXXX XXX XXXXXXXXXXXX
            XXXXX XXXXXXX XXXXXXXXXXXXXXX
          XXXXX
          XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX
            XXXXXX XXXXX
          XXXX
        XXXXXX
      XXXXXX
    XXXXXXXXXX

    XXXX XXXXXXXXXXX XXXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXX
             XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
         XXXXXXXXX XXXXXX XX XXXXXXXX XXXXXX
       XXXXX

      XXXX XXXXXXXX XXXXXX XXX
      XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XX XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXX XXX
      XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
            XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                         XXXXX
               XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX
               XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
             XXXXXX
          XXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXX XXXXXX XXXX XXXXXXXXXXX XXXXX XXXX XXXXX XXXXXXX X XXXXXXXX XXX XXXXXXXX
          XXXX
        XXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
            XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                         XXXXX
               XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
               XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
             XXXXXX
          XXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXX X XXXXXXXXX XXXXXXX XXXXX XXXX XXXXXXXX XXX XXXXXXXX
          XXXX
        XXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
            XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                         XXXXX
               XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
               XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
             XXXXXX
          XXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXX XXXXXX XXX XXXXXXXXXX XXX XXXX XX XXXXXXX X XXX XXXXXXXX XX XXXXXXX
          XXXX
        XXXXXXXXXX
      XXXXXX
    XXXXXXXXXX

    XXXX XXX XXXXX XXXXXXXXX XXX
    XXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
             XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX
          gettext(u'Ready to upgrade your workshop into a smart force?') 
       XXXXX
      XX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX gettext(u'Start Free Today') XXXX
    XXXXXXXXXX

    XXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX
      XXXXXXXXX XXXX XXXXXXX XXXX  gettext(u'Built with AI for mechanics') XXXX
    XXXXXXXXX
  XXXXXXX

  XXXX XXXXXXX XXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
    XX XXXXXXXX XXXXX
    XXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXXXXXXXX XXXXXX
      XXXXXXXXXX XXXXXXX
      XXXXXXXXX XXXXXXX
      XXXXXX XXXXX
      XXXXXXXXXXXX XXXXX
      XXXXXX XXXXXXXXX
      XXXXXXX XXXXXXXXX
      XXXXXXXXXXXXXXXX XXXXXXXXX
      XXXXX XXXX
    XXX

    XX XXXXXXXX XXXX
    XXXXXXXXXXXX
      XXX XXXXXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXXXXXXXX XXXXXX
      XXXXXXXXXX XXXXXXX
      XXXXXXXXX XXXXXXX
      XXXXXX XXXXX
      XXXXXXXXXXXX XXXXX
      XXXXXX XXXXXXXXX
      XXXXXXX XXXXXXXXX
      XXXXXXXXXXXXXXXX XXXXXXXXX
      XXXXX XXXXX
      XXXXXXXX XXXXXX
      XXXXXXXXXX XXXXX
    XXX

    XX XXXXXX XXXXXXXXXXX XXXXXX
    XXXXXXXXXX
      XXXXXXXXX XXXX
      XXXXX XXXXX
      XXXXXXX XXX
      XXXXXX XXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXX
    XXX

    XX XXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
    XXX
  XXXXXXXXX
XXXXXXX
XXXXXXX
