BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBB gettext(u'Registro exitoso')  X XXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBB BB BBBBXXXXXXXXXXXX XXXXXXXXXXXBBBBXXXXXXXXX XXXXXXXXBBBBB
        XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXX
        XXX
          BB BBBBBBBBBBBBB BB BBBB
            XXXXXX XXXXX XXXX XXXXX XX XXXXXXXX XXXX XXXXXXXX XX XXX XXXXX XXX XXX XXXXXX XXXXX XXXX XXXX XXXXXX XX XXXXXXX X XXX XXXXXXXXXXXX XXXXX
          BBBB
            XXX XXXXX XXXXXX XX XXXXXX XXXXXXXXXXX XXXX XXXXXXX XX XXXXXXX XX XX XXX XX XXXXXXX XXXXXX XX XXXXXXX XX XXXX X XXXXXXXX XX XXXXX XXXXXX XX XXXXXXXXXXXXX
          BBBBB
        XXXX
      XXXXXX
  BBBB BBBBBBBBBBB
  XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u'Ir a iniciar sesión') XXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXX X X XXXX XXXXXXXX X X XXX XXXXXXXX X X XXX XXXXX
    XXXXXXXXXXXXXXX XXXX
  X
XXXXXXXX
XXXXXXXX
XX XXXXXXXXX XX XXXXXX XXXX XXXXXXXX XXXXXXXXXX
XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XX XXXXXXXX X
  XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXX
  XXX X X XXXXXXXXXXXXXXXXXX
  XXX X X XXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXX X XX
  XXXXXXXXXXXXX X XX
  XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXX XX XX XX
    XX XXXXXXXXXXXXX X XX
    XX XXXXXXXXXXXXX X XX
    XX XXXXXXXXXXXXX X XXX X XXXX
    XXX XXXXXXXXXXXXXX X XXXX X XXXX
    XXX XXXXXXXXXXXXXX X XXXX X XXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX
  XXXX
  XXXXXXXX XXXXXX X
    XXXXXXXXXXXXXXXX XX XX XXX
    XXX XXXX X XX XXXXXXXXXX X
      XXXXXXXXXXXXXXXX
      XXXXXXXXXXXX XXXX XXXX XX X X XXXXXXXXX
      XXXXXXXXXXXXX X XXXX
      XXXXXXXXXXXXXXX X XXXX
      XXXXXXXXXXXXXX X XXX
      XXXXXXXXXXX
    X
  X
  XXXXXXXX XXXXXXXX X
    XXX XXXX X XX XXXXXXXXXX X
      XXX XX XXXXX
      XXX XX XXXXX
      XX XXXX X X XX XXX X XX XXXX XX XXX
      XX XXXX X X XX XXX X XX XXXX XX XXX
    X
  X
  XXXXXXXX XXXXXXXXX X
    XXXXXXX
    XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    X X XXXXXXXXXXXXXXXXXX
    X X XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX X XX
    XXXXXXXXXXXXX X XX
  XXX
X
XXXXXXXXX
BBBBBBBB
