XXXXXXXXX XXXXX
XXXXX XXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXBB BBBBBBBBBBBBBBBB BB BBBBXXX XXXXXX XXXXBBBBXXXX XXXXXXX XXXBBBBB X XXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXX XXXXX XXX XXX
    XXXXXXX
        XXXXX X
            XXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXX XXXXXXXX
            XXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXX
        X

        X X
            XXXXXXX XX
            XXXXXXXX XX
            XXXXXXXXXXX XXXXXXXXXXX
        X

        XXXX X
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXXXX XXXXXXX
        X

        XX XXXXXXXX XXXXXXXXXX XX
        XXXXXXXXXXXXX X
            XXXXXXXXX XXXXXX
            XXXX XX
            XXXXX XX
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXX XXX
            XXXXXXXX XXXX
        X

        XXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXXX XXXX
            XXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXX XXXXX XX XXXXXXXX XXXXXXXXXXXX
        X

        XXXXXXXXXX XXXXX X
            XXX XXXX X XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX X
            XXX X XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXX X
        X

        XX XXXXXX XX
        XXXXXXX X
            XXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXX XXXX XX
            XXXXXXXXX XXXXXXX
            XXXX XX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXX X XXXXX
            XXXXXXXX X XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXX
        X

        XXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXX XXXXXXX
        X

        XXXXXXXXX X
            XXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXXXXXXX
        X

        XX XXXX XXXXXXXXX XX
        XXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXX X XXXXX
            XXXXXXXX XXXX XXXXX
        X

        XXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXX
        X

        XXXXX XX X
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
        X

        XXXXX X X
            XXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXX X XXXXX
        X

        XX XXXXX XXXX XX
        XXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
            XXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
            XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXX XXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXX
            XXXXXXXXX XXXXXXXXX
            XXXX XX
            XXXXX XXXXXX
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
            XXXXXXXXXXX XXXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXX XX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXXXX
        X

        XXXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
        X

        XX XXXX XXXXX XX
        XXXXXXXXXX X
            XXXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX XX XX XXXXX
        X

        XXXXXXXXXX X
            XXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXX XXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXX XXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXX
        X

        XX XXX XXXXXXXXXX XX
        XXXXXXXXX X
            XXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXX
        X

        XXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXXX XX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXX
        X

        XX XXXXXXXX XXXX XX
        XXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
            XXXX XXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXX XX XXXX XXXXX
            XXXXXXX XXX XXXXX XXXXXXXXX XX XXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X X XXXX XXXXXXXXX XX XXXX XXXXX
        X

        XXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXXXX
        X

        XXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX
        X

        XX XXXXXXXXXX XX
        XXXXXX XXXXXXXXXXX XXXXXX X
            XXXXX XX X
                XXXXXXXXXX XXXXX
            X

            XXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXX XXXX
            X

            XXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXX
            X
        X

        XX XXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXX
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXX
                XXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXX

    XXXX XXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXX XXXXXXX XXX
        XXXXXXXX XXXXXXXXXXXXX
            XXXX
                BB BBBBBBBBBBBBBBBB BB BBBB
                    X XXX XXXXXX XXXXX
                BBBB
                    X XXXXX XXXX XXXXXXX XXX
                BBBBB
            XXXXX
            XXX
                BB BBBBBBBBBBBBBBBB BB BBBB
                    XXXXXXXX XXXXXXXXXXXX XXXXXX XXXX XX XXXXXXXXXX XXXXXXX XXXXXXXXX XXX XXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXX XXX XXX XXXXXXXX XXXXXXXXXX XXXXXXX
                BBBB
                    XXXXXXX XXXXXXXX XX XXXXXXXXXXXX XXX XXXXXXXXX XX XXXXXXX XXXX XX XXXXX XX XXXXXXXXXX XXXXXXXX XX XXXXXXXXX X XXXXXXXXXX XXXXXXXX XXXX XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
                BBBBB
            XXXX
        XXXXXXXXXX

        XXXX XXXXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXX XXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX
                    BB BBBBBBBBBBBBBBBB BB BBBB
                        XX XX XXXXXX X XXXXXX
                    BBBB
                        XX XXXXXXX X XXXXXXXX XXX
                    BBBBB
                XXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBB BB BBBB
                        XX XX XXXXXX XXXX XXXXX XXXXXXX XXXXX XXX XXXXXX XXX XXXXXXXX XXXXXXXXXXXX
                    BBBB
                        XX XXXXXXX XX XXXXXX XXX XXXXXXXX XXXXXXXXXXXX XXXXX XX XXXXXXXXX X XXXXXXXXXXX XX XXXXX XXXXXXXXX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    BBB BBBBBB BB BBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXX XXXXXXXXX
                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXX
                    BBBBBB
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXX XXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX
                    BB BBBBBBBBBBBBBBBB BB BBBB
                        X XX XXXXXXX XXXXXXXX
                    BBBB
                        X XXXX XXXXX XXXXXXXXX XXX
                    BBBBB
                XXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBB BB BBBB
                        XX XXXXXXX XXXXXX XXXX XXXXXX XXXX XXXX XXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXX XXXXXXXX XXXXXX XXXXXXX XX XXX XX XXXXXXX
                    BBBB
                        XX XXXXXX XX XXXXXXXXX XXX XXXXXXX XXXXX XXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXX X XXXXXXXX XXXXXXXXX XX XX XXXXXXX XXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBB BB BBBBXXXXXXXX XXXXXXXBBBBXXXXXX XXXXXXXXXXXBBBBB
                        XXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        BBBBBB
                    XXXXXX
                    XXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBB BB BBBBXXXXXXXX XXXXXXXBBBBXXXXXX XXXXXXXXXXBBBBB
                        XXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        BBBBBB
                    XXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXX XX XXXXXXXXX XXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX
                    BB BBBBBBBBBBBBBBBB BB BBBB
                        X XX XXX XXXXXX
                    BBBB
                        X XXXXXXX XXXXXXXXX XXX
                    BBBBB
                XXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBB BB BBBB
                        XXXXXXXXX XXXXX XXX XXXXXXXXXXX XX XXXXX XXX XXXXX XXXX XXX XXXXXXXX XXXXXXXXXXX
                    BBBB
                        XXXXXXX XXXXXXXXXX XX XXXXX XXX XXX XXXXXX X XXXXXXX XXX XXXXXXX XX XXXXXX XXXX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXX
                        XXXXXX
                            BB BBBBBBBBBBBBBBBB BB BBBBXXXXXXXXXBBBBXXXXXXXXXBBBBB
                        XXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXX
                        XXXXXX
                            BB BBBBBBBBBBBBBBBB BB BBBBXXXXX XXX XXXXBBBBXXXXXXXX XXXXXX XXXXBBBBB
                        XXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXX
                        XXXXXX
                            BB BBBBBBBBBBBBBBBB BB BBBBXXXXXXBBBBXXXXXXBBBBB
                        XXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX
                    BB BBBBBBBBBBBBBBBB BB BBBB
                        XXXXXXX XXXXXXXXXXX XXX XXXXXXXX XX
                    BBBB
                        XXXXXXX XX XXXXXXX XXXX XXXXXXXX XX
                    BBBBB
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXX XXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX
                    BB BBBBBBBBBBBBBBBB BB BBBB
                        X XXXXXXXXX XXXXXXXX
                    BBBB
                        X XXXXXXXXX XXXXXXXXX
                    BBBBB
                XXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBB BB BBBB
                        XXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXX XXXXXXXX XXX XXXXX XX XXXXXXXX XXXXXXXX
                    BBBB
                        XXXXXXXXXX XXXXXXXXXX XX XXXXXXXXX XXXXXXXXXXXX X XXXXXXXXX XX XXXXXX XXXXXXXXXX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    BBBBBB
                XXXXXX
            XXXXXX

            XXXX XXXXXXXX XX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX
                    BB BBBBBBBBBBBBBBBB BB BBBB
                        X XXX XXXXXXXX XXXXXXXXXX
                    BBBB
                        X XXXXXXX XXXXXX XXX
                    BBBBB
                XXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBB BB BBBB
                        XXXXXX XXX XXXXXXXXXX XXXX XXXXXX XXX XXXXXXXXX XXX XXXX XXXXXXXXXX
                    BBBB
                        XXXXXXX XXX XXXXXXXXX XXX XXXXX XXXX XXXXX X XXXXXXXXX XX XXXXXXXXX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    BBB BBBBBB BB BBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBB BB BBBBXXXXXXXBBBBXXXXXXXXXBBBBB
                        XXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    BBBBBB
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX
                    BB BBBBBBBBBBBBBBBB BB BBBB
                        X XXXXXXX XXXXXXXXXXXXXXX
                    BBBB
                        X XXXXXXXXXXXXXXX XXXXXXX
                    BBBBB
                XXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBB BB BBBB
                        XXXXXXXXXXX XXXXXXXX XXX XXXXXXX XXXXXX XXXXXXXXX XXXXX XXX XXXXXX XXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXX
                    BBBB
                        XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XX XXXXXXX XX XXXXXXX XXXXXXXXXX XXXXX XX XXXXXXXXX XXXXXXXX XXXX XXXXXXX X XXXXXXXXXXXX XXXXXXXXXXX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
                        XXXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX
                        XXXXXXXX XXXX XXXXX
                        XXXXXXXXXXXXXX XXXXX
                        XXXXXXXXXXXXXXXX XXXXX
                        XXXXXXXXXXXX XXXXX
                        XXXXXXXXXXX XXX XXXX XXXXX
                        XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
                    XX
                        BB BBBBBBBBBBBBBBBB BB BBBB
                            X XXX XXXXXXX XXXX
                        BBBB
                            X XXXXXX XXXX XXXXXXX
                        BBBBB
                    XXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXXXXXX
        XX XXXXX XXXXXXXXXX XXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX X XXX

            XXX XXXX X X XX X X XXXXXXXXXXXXXX XXXX X
                XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXX X XXXX
                XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXX X XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X X X XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X X X XX X XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        X

        XX XXXXXXX XXXXXX
        XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
            XXX X
                XXXXX XXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXX XXXXXXX
                    XXXXXXXX X
                        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
                    XX
                    XXXXX XXXXXXXXXXXXXXXXXX
                XXX

                XXXXX XXXXXX X XXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXX
                X
            X XXXXX XXXXXXX X
                XXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXXXX XXXXXXX
                XX XXXXXXXXX XXXXXXXX XXX XXXXXXXXX XX XXXXXX
                XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
            X
        X

        XX XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXX

            XX XXXXXXXXX XX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX X
                XXXXXXXXXXXXXXXXXX X XXXX
                XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX

                XXXXXXXXXXXXX XX X
                    XXXXXXXXXXXXXXXXXXXXX X XXXX XXXX XXXXXX
                    XXXXXXXXXXXXXXXXXX X XXXX
                    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
                XX XXXXX X XXXXX
            XXX
        XXX
    XXXXXXXXX
XXXXXXX
XXXXXXX
