BBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXX
        XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
    XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      BBB B BB BBBBBBBBB
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXX XXXXXXXXXXX XXXXXXXXXXX
        XXX XXXXXXXXXXX XXXXXXXXXXX
        XXX XXXXXXXXXXX XXXXXXXXXXX
        XXX XXXXXXXXXXX XXXXXXXXXXX
        XXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXXBBBBB XX XXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB XX XXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB XX XXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXFFFFFFFFFFFX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XX XXXXXXFFFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXFFFFFFFFFFFX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
      XXXXX
      BBBBBB
    XXXXXXXX
  XXXXXXXX
XXXXXX
