BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Password changed!') XXXXX
  XX XXXXXXXXXXXXX gettext(u'Your password has been successfully reset. You can now sign in with your new password.') XXXX
  BBBB BBBBBBBBBBB
  XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX gettext(u'Sign in') XXXX
XXXXXX
BBBBBBBB
