BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBB
XXXXXXX
XXXXXXXXXXX X
  XXXXXXXXXXXXXX XXXXX
X
XXXXXXXXXXX XXXXX X
  XXXXXXXX XXXXXX
  XXXXXXXXXXXX XXXX
  XXXXXX XXXXXXX XXXXXXXXXXX
  XXXXXXXXXX XXXXX
  XXXXXXXXXXXXXXX XXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXX XXXX
X
XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX X
  XXXXXX XXXXX
  XXXXXXXX XXXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  XXXXXXXXXXXXXX XXXX
  XXXXXX XXXX XXXXXXXXXXX
  XXXXXXXXXX XXXXX
X
XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX X
  XXXXXXXX XXXXX
  XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  XXXXXXXXXXX X X X XXX XXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXX XXXXXXXXXXX
X
XXXXXX XXXXXX X
  XXXXXXXXXXX XXXXXXXX
  XXXXXX XXXXX
X
XXXXXXXXXXXX X
  XXXXXXXX XXXXX
  XXXXXXXXXXXXXXXXXXXXXX XXX XXXX
  XXXX XXXXX
X
XXXXXXXXXXXX X
  XXXXXXXX XXXXX
  XXXXXXXXXXXXXXXXXXXXXX XXX XXX XXXX
  XXXX XXXXX
X
XXXXXX XXXXXXXXXXX XXXXXX X
  XXXXXXXXXXXXX XXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXX XXXX
  X
X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX

  XXXX XXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXX XXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXX
      BB BBBBBB
        X XXXXXX XXXXXXXX
      BBBB
        X XXXXX XXXXXXXX
      BBBBB
    XXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      BB BBBBBB
        XXXXXXXX XXX XXXXX XXX XXXXXXXX 
      BBBB
        XXXXXXXX XX XXXXXXXXXXX XXX XXXXX XXXXXXXX
      BBBBB
    XXXX
  XXXXXX

  XXXX XXXX XXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXX XXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
      BBBBBBBBBB

      XXXX XXXXXXXXXXX XXXXXX XXX
      XXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXX
          X XXXXXXXXXXX XXXXXX
        XXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF
            BB BBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
            BBBBB
            BB BBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
            BBBBB
          XXXXXX

          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF
            BB BBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
            BBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
            BBBBB
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX
          FFFFFFFFFFFFFFFFFFFFFFFF
          BB BBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
          BBBBB
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXX XXXXXXXXX XXX
      XXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXX
          X XXXXXXXXXXX XXXXXXXXX
        XXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
            BBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
            BBBBB
          XXXXXX

          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
            BBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
            BBBBB
          XXXXXX

          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
            BBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
            BBBBB
          XXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXX XXX XXXXXXXXX XXX
      XXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXX
          X XXXXXXXXXXX XXX XXXXXXXXX
        XXXXX

        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX
          FFFFFFFFFFFFFFFFFFFFFFFF
          BB BBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
          BBBBB
        XXXXXX
      XXXXXX

      XXXX XXXXXXX XX XXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXX
          BB BBBBBB
            X XXXXXXXXXX XXXXXXXX
          BBBB
            X XXXXX XXXXXXXX
          BBBBB
        XXXXXXXXX

        XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
          X XXXXXX X XX XXXXX
        XXXX
      XXXXXX
    XXXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
