BBBB BBBBBBBBBBB
BBB BBBBBBBB BB BBBBBBBBB
XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXFFFFFFFFFFFXXXXX
  XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXFFFFFFFFFFFXXXXX
  XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXFFFFFFFFFFFXXXXX
  XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX
XXXXX
BBBBB
XXXX
  XXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXX
    XX XX XXXXXXXXXXX XXXXXXXXX XXX XXXX XXXXXXXXXX
  XXXXX
XXXXX
BBBBBB
