BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB X XXXXX XXXXXXX XXXXXXBBBBBBBB

XXXX X XXXXXXXXXXXXXX XXXXXX X XXX XXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXX XXXXXX XXXX XXXXX XXXXXX XXXXX XXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXX XXX XXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX

BBBBB BBBBBBBBB
XXXXXXX
XX X XXXXXX XX XXXXXXXX XXXXXXXX XXXX XXXXXXXXX XX
XXXXX X
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXX XXX XXX XXXXXX
    XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
    XXXXXXXXXXXX X X XXXXX
X

XXXX X
    XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXXXXXXX
    XXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXX X XXX X XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXX XX XXXXXXXXX
X

XXXXXXXXXX XXXXXXXXX X
    XXX XXXX X XXXXXXXX XX X
    XXX X XXXXXXXX XX X
X

XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        X XXXX XXXX XXXXXXXXX XXXX XX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XXXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XX XXXXX XXXXXXXXXXXXX
    XXXXXXXXXXX XXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXX
X

XXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXX
    XXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXX X
    XXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXX
X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXX


    XXXX X XXXXXXX XXXXXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX

            XXXX XXXXXXXX XXXXXXXXXXXX XXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX

            XXXX XXXXXXXXX XXXXXXXXX XXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXX

            XXXX XXXXXXXX XXXXXX XXX
            XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXX

            XXXX XXXXXX XXXXXX XXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXX

            XXXX XXXXX XXXXXXX XXX
            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX

            XXXX XXXXXX XXXX XXX
            BBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBBBB
                XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            BBBB
                XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            BBBBB
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXX
        XXXXXX
    XXXXXX

    XXXX X XXXXXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXX XXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFFXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX
            XXXXXX

            XXXX XXXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXX

            XXXX XXXXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

XXXXXX
BBBBBBBB
