BBBB BBBBBBBB
BBB BBBBBBBB BB BBBBBBBBB
XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFF FFFFFFFFFFXXXXXX
      XXXXXX
    XXXXXX
  XXXXX
  XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXXX
  XXXXX
  XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXXX
  XXXXX
  XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
      XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF XXX
    XXXXXX
  XXXXX
  XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
      XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF XXX
    XXXXXX
  XXXXX
  XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBB B BB
        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
          
        XXXXXXX
      BBBB BBBBBBBBBBBBBBBBBBBBBBB B B
        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
          
        XXXXXXX
      BBBB
        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
          XXXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
          
        XXXXXXX
      BBBBB
    XXXXXX
  XXXXX
  XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXX XXX
         XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
         XXXXXXXXXX XXXXXXXXXX
        XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXX XXX
         XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXX XXX
            XXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XX XXX XXXXXX XXXXXXXX XXXX XXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXX
      XXXXXXX
    XXXXXX
  XXXXX
XXXXX
BBBBB
XXXX
  XXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXX XX XX XXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXX
XXXXX
BBBBBB
