BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBB

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
XXXXXXX
XXXXXXX X XXXXXXXX XXXX XXXXXXXXXXX X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBB
XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
      XXXXXXXXXXXXXBB BBBBBBBBBBBBBBB BB BBBBXXXXXBBBBXXXXXBBBBBX
      XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBB BB BBBBXXXBBBBXXXBBBBBX
      XXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXX
  BBBBBBBBBB
  XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

  BB BBBBBBBBBBBBBBB BB BBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
  XXXXXX
XXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XX XXXXXXXXX XXX XXXXXXXXXX

    XX XXXXXXX XXXXXXXXX XXX XXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXX XX XX XXXXXXXXXXX XXXXXXXXX XXXXXXX X XXXXXXXXXXX
        XXXXXXX
    X

    XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX

    XX XXXXXX XXXXXX XXXXXX XX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXX XXXXXXXXXXX

        XX XXXXXXX XXXXXXXXX XX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XX XXXXXXXXX X XXXXXXXX XXXXXXXXXXX

            XX XXXXXXXX XXXX XXXXX XX XXX XXXX XXXX XX XXX XXXXXXXX
            XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX X XXXXX
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX

            XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXX

                    XX XXXXXX XX XXXXXXXX XXX XXX XXXXXXXXX
                    XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX

                    XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX X XX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX
                        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
                    X XXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXX XX XXX XXXXXXXXX XXXX XXXX XXXXXXXXXX
                    X
                XX
                XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX X
                    XXXXXXXXXXXXXXXX XXXXX XX XXXXXX XXXXXXXXXXXX XXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XX XXXXXXXXXXXX
        X
    XXX

    XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XX XX XXX XXXXXXX XXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XX XXXXXXXXX XXXXXXXXX
    X
XXX
XXXXXXXXX
BBBBBBBB
