BBBB BBBBBB
BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX gettext(u'Technician Reports')  X FFFFFFFFFFFFFFFFFFXXXXXXXX

    XXXX XXXX XXXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX

    XXXX XXXXXXXX XXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX
        XX XXXXXXXXX XX XXXX XX XXXXXXXXX XX
        XXXXX X
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXXXXX
        X

        XX XXXXX XXX XXXXXX XX XXXXXX XXXXXXX XX
        XXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX
            XXXXXXX XX
            XXXXXXXX XX
        X

        XX XXXXXX XX XXXXXXXXXX XX XXXXX XX
        XXXXXXXXXXXXX X
            XXXXXXXXX XXXXXX
            XXXX XX
            XXXXX XX
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXX XXX
        X

        XX XXXXXX XX XXXXXX XXXXXXX XX
        XXXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXX
            XXXX XX
            XXXXX XX
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXX XXXX XXX XXXX XXXXXX
                XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXX XXXX XXX XXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXX XXXXX
            XXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXX XXXXXXXXX
            XXXXXXXX XXX
            XXXXXXXX XXXX
        X

        XXXXXXXXXX XXXXXXXXXXXXX X
            XX X XXXXXXXXXX XXXXXXXXXXXXXX X
            XXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXX X
        X

        XX XXXXXXXXXX XXXXXX XX
        XXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXX XXXX XXXX XXX
                XXXXXXX XXXX XXXX XXXX XXXX
                XXXXXXXXX XX XXXX XXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXX XXXXXXX
            XXXX XX
            XXXXXXXX XXXX
        X

        XXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
        X

        XXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXX XXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX XX XX XXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX
            XXXXXXXX XXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
        X

        XX XXXXXX XXXXXXXXXX XX
        XXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXX XXXX XXXX XXX
                XXXXXXX XXXX XXXX XXXX XXXX
                XXXXXXXXX XX XXXX XXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXX XXXXXXX
        X

        XXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXX
            XXXXXXXXX XXXXXXXXX
            XXXX XX
            XXXXX XXXXXX
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX
                XXXXXXX XXXX XXXX XXXXX
                XXXXXXXXXXXXX
            XXXXXXXXXX XXXX XX XXXXXXXXXXX XXXXXXXXX
        X

        XXXXXXXXXX XXXX X
            XX X XXXXX XXXXXX X
            XXX X XXXXX XXXXX X
            XXXX X XXXXX XXXXX X
        X

        XXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXXXX
        X

        XXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXXXX
            XXXXXXXX XXXX
            XXXXXXXXXXXXXX XX
        X

        XXXXXXXXXX XXXXX X
            XXX XXXX X XXXXXXXXXX XXXXXXXXXXXXXX X
            XXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXX X
        X

        XX XXXXXXX XXXXXXXXXX XX
        XXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXX XXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX XX XX XXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
        X

        XXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXX XXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
        X

        XX XXXXXXXXXX XX
        XXXXXX XXXXXXXXXXX XXXXXX X
            XXXXXXXXX X XXXXXXXXXX XXXXX X
            XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXXX X XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX X
            XXXXXXXXXXX X XXXXXXXX XXXXX X
            XXXXXXXXXXX XXXXXXXXXXX X XXXXXXX XXXXX X
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXX XX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Technician Reports') XXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX gettext(u'Dashboard') XXXXXXX
                XXXX
                XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXX gettext(u'Documents') XXXXXXX
                XXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX gettext(u'Reports') XXXXXXX
                XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXX
                    XXXXXX gettext(u'Settings') XXXXXXX
                XXXX

                XXXX XXXXXXXX XXXXXX XXX
                XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXX XXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXX XXXXXXXXXXXXXXXX
                    XXXXXXXXX
                XXXXXXX

                XXXX XXXXXX XXX
                XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXX gettext(u'Logout') XXXXXXX
                    XXXXXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX

        XXXX XXXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX  gettext(u'TECHNICIAN REPORTS') XXXXX
            XX XXXXXXXXXXXXXXXXXXXX gettext(u'Intelligent performance analysis with predictive AI') XXXX
        XXXXXX

        XXXX XXXXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX  gettext(u'From') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                               XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX  gettext(u'To') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                               XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX  gettext(u'Technician') XXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBB BB BBBBBBBXXXXXXXXBBBBBXX  gettext(u'All technicians') XXXXXXXXX
                            BBB BBBBBBBB BB BBBBBBBBBBBBBBB
                                XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX
                                    X 
                                XXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXX
                         gettext(u'Filter') 
                    XXXXXXXXX
                    XX XXXXXXXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX
                         gettext(u'Reset') 
                    XXXX
                XXXXXX
            XXXXXXX
        XXXXXX

        XXXX XXXXX XXX XXXXXXXXX XXX XXXXXXXX XXXXXXXX XXX
        BB BBBBBBBBBBBBBB
            XXXX XXXXXXXX XXXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXX  gettext(u'Performance Metrics') XXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Total Documents') XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Total Generated') XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Average per Document') XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Active Technicians') XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXX XX XXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXX  gettext(u'Technician Performance') XXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXX
                        XXXXXXX
                            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX gettext(u'Technician') XXXXX
                                XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX gettext(u'Documents') XXXXX
                                XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX gettext(u'Services') XXXXX
                                XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX gettext(u'Total Generated') XXXXX
                                XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX gettext(u'Average') XXXXX
                                XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX gettext(u'Top Services') XXXXX
                                XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX gettext(u'Actions') XXXXX
                            XXXXX
                        XXXXXXXX
                        XXXXXXX
                            BBB BBBB BB BBBBBBBBBBBBBB
                            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXX XXXXXXXXXXX
                                XXX XXXXXXXXXXX XXXXXXXXXXX
                                XXX XXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXX XXXXXXFFFFFFFFFFFFFFFXXXXX
                                XXX XXXXXXXXXXX XXXXXX
                                    BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBB
                                        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXX XXXX XXXXXX
                                            FFFFFFFFFFFFFFFF XX
                                        XXXXXXX
                                    BBBBBB
                                XXXXX
                                XXX XXXXXXXXXXX XXXXXX
                                    XXXX XXXXXXXXXXX XXXXXXX
                                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXX gettext(u'Send summary via WhatsApp') XX
                                            X
                                        XXXXXXXXX
                                        XX XXXXXXXXXXXXX
                                           XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXX gettext(u'Download individual PDF') XX
                                            X
                                        XXXX
                                    XXXXXX
                                XXXXX
                            XXXXX
                            BBBBB
                            XXXX
                                XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                                    X  gettext(u'No technician data found for the selected period') 
                                XXXXX
                            XXXXX
                            BBBBBB
                        XXXXXXXX
                    XXXXXXXX
                XXXXXX
            XXXXXX
        BBBB
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXX gettext(u'No Data Available') XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXX gettext(u'No technician data found for the selected period. Try adjusting your filters.') XXXX
            XXXXXX
        BBBBB
    XXXXXX

    XXXX XXXXXXX XXX
    XXXXXXXX
        XX XXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX X
                XXXXXXX X XXXXXX XX XX
                XXXXXX X XXXXXX XXXXXXXXX XX
                XXXXXX X XXXXX XXXXXXXX XX
                XXXXXXXX X XXXXXX XXX XX
                XXXXX X XXXXXX X XX
                XXXXXXXXXXXX X
                    XXXXXXX XXXXX
                    XXXXXXXXX XXXX
                    XXXXXX XXXXXXXXXX
                    XXXXXXXX XXXX
                    XXXXXX X
                XX
                XXXXX X
                    XXXXXXX XXXXX
                    XXXXXX XX
                    XXXXXXXXXX XXXXXXX
                    XXXXXXX XXXXXX
                    XXXXXXXXX XXXXXX
                    XXXXXXXXX XXXXXX
                    XXXXXXX XXXXX
                X
            XX
            XXXXXXXXXXXXXX X
                XXXXXXXXXX XXXXXXXXX
                XXXXXXX X
                    XXXXXXXX X XXXXXXX XXXXX XXXXX XXXXXXXXX XX
                    XXXXXXXX X XXXXXXX XXXXX XXXXX XXXXXX XX
                    XXXXXXX XXXX
                X
            XX
            XXXXXXXXXXXXXX XXXX
        XXX

        XX XXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXX XXX XXXXXXXXXX XXX X X XXXXXXXXXXXX
        X
    XXXXXXXXX
XXXXXXX
XXXXXXX
