BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBXXXXXXX X  gettext(u'Restablecer contraseña') BBBBBBBB

BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXX gettext(u'Restablecer contraseña') XXXXX
    XX XXXXXXXXXXXXXXX gettext(u'Ingresa tu email para recibir instrucciones.') XXXX
  XXXXXXXXX

  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    

    
    BBB BBBBB BB BBBB
      XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBXXXXXXXXXXXXBBBBBXX
        
      XXXXXX
      BBB BBB BB BBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
      BBBBBB
    BBBBBB

    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Enviar instrucciones') XXXXXXXXX
  XXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'o') XXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXX gettext(u'¿Recordaste tu contraseña?') XXXXXXX
    XX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXX gettext(u'Iniciar sesión') XXXX
  XXXXXX
XXXXXXXXXX
BBBBBBBB
