BBBBBBB BBBBBBBBBBB
BBBBB BBBBBXXXXXX XXXXXXXBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXX XX XXXXXXXXXXXXX
  BBBB BBBBBBBBBBB
  XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XX XXXXXXXXX
    XX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXX XXXXXXXXXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
