BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Check your email') XXXXX
  XX XXXXXXXXXXXXX gettext(u"We have sent you a link to reset your password. If you don't see it, check your spam or junk folder.") XXXX
  XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX gettext(u'Go to main page') XXXX
XXXXXX
BBBBBBBB
