BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBB BBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXX X X XXXXXX XXXX XXX XXXXXXX X X XXXXXXXXX X X XXXXXXXXXX X X XXXX XXXXXX X X XXX XXXXXXXXXXX
        XXXXXX
      XXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'Check your inbox') XXXXX
      XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
         gettext(u'We have sent you an email with a verification link. Please click the link to activate your account.') 
      XXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX
      XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXX X XXXXXXX XXX XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX
         gettext(u'Change email / Resend') 
      XXXX

      XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
        XXXXXX
         gettext(u'Back to login') 
      XXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
         gettext(u"Didn't receive the email? Check your spam folder or contact support.") 
      XXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
