BBBB BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXX gettext(u'Welcome to eGarage USA') XXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
    XXXXXXX X
      XXXXXX XXXXX
      XXXXXXXXX XXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXX X
      XXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXXXXX XXXXXXXXX
      XXXXX XXXX
      XXXX XX
      XXXXXX XXXXX
      XXXXXXXX XXXX
      XXXXXXXXXXXX XXXX X XXXX
      XXXXXXXXXX XXXXXX XX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXX XXXXXX X
      XX X XXXXXXXXX XXXXXXXXXXXX X
      XXX X XXXXXXXXXX XXXXXXXXXXXX X
      XXX X XXXXXXXXX XXXXXXXXXXXX X
      XXX X XXXXXXXXX XXXXXXXXXXXX X
      XXX X XXXXXXXXXX XXXXXXXXXXXX X
      XXXX X XXXXXXXXX XXXXXXXXXXXX X
    X

    XXXXXXXXXXX X
      XXXXXXXXX XXXXXX
      XXXXXXX XXXXXXX
      XXXXXX XXXXXXX
      XXXXXXXX XXX
      XXXXXXXX XXXXX
      XXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXX
    X
    XXXXXX XXXXXXXXXXX XXXXXX X
      XXXXXXXXXXX X
        XXXXXX XXXXXXX
        XXXXX XXXXXXX
        XXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
      X
    X
  XXXXXXXX
  XXXXXXX
    XXXX X
      XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXX XXXXXX XXXX XXXXXX XXXXXXXXXXX XXXXXXXXXX
      XXXXXX XXXXX
      XXXXXXXXXXX XXXXXX
    X
    XXX XXX XXX XXX XXXXXXXXXXXXXXXX X
      XXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXXX XXXXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXX
    X
    XXXXXXXXXXXXXXXX X
      XXXXXXXXXXXX X X XXXX XXXXXXXX X X XXXX XXXXXXXX X X XXX XXXXX
    X
    XXXXXXXXXXXX XXXXXX X
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXX X XXX XXXX X XXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXX
      XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
      XXXXXXXXXX XXXXXXXXXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXX X
      XXXXXX XXXXXX
      XXXXXXX XXXXX
      XXXXXXX X XXXXXX
      XXXXX XXXX
      XXXXXXXXX XXXXXXXXX
      XXXXXXXX XX
    X
    XXXXXXXXX X
      XXXXXX XXXXXX
      XXXXXXX XXXXXX
      XXXXXXXX XXXXXX
      XXXXXXX XX
      XXXXXXXX XX
    X
    XXXXXXXXXXX X
      XXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXX
      XXXXXXXXXXXX XXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXX X
      XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXX X
      XXXXXX XXXXX
      XXXXXXX XXXXX
      XXXXXXX X XXXX XXXXXX XXXXX
      XXXXXXXX XXXXXX
    X
    XXXXXXXXXXXX X
      XXXXXXXX X XXXXXXXXXXX
      XXXXXXXXXX XXXX XXXXXXXXXXX
    X
  XXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXX XXXXXXXX XXX
  XXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Language') XXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXXXXX XXXXXXXXXXBBBBXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBBXX
          XX XXXXXXX
        XXXX
        XX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXXXXX XXXXXXXXXXBBBBXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBBXX
          XX XXXXXXX
        XXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXX XXXX XXX
  XXXX XXXXXXXXXXXX XXXXX XXXXXX XXXX XXXXXXXXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXX
    XXXXXXX XXXXXXXXX XXXX
    XXXXXXX XXXXXXXX XXXX
    XXXXXXX XXXXXXXXX XXXX
    XXXXXXXXXXX XXXXX  gettext(u'Language') 
  XXXXXX
  XXXX XXXXX XXXXXXX XXXXXXXX XXX
  XXXX XXXXX XXXXXX XXXXXXX XXXXXXXX XX XXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXX
    XXXX XXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXX XXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXX gettext(u'The #1 Auto Shop Platform in the USA') XX gettext(u'The #1 Auto Shop Platform in the USA') XXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXX
        XXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXXXXXXX
        XXXXXXXXXXXXX
      XXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Trusted by mechanics across America. Real features. Bilingual support. No risk.') XXXX
      XXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX  gettext(u'Start Free Trial') XXXX
        XX XXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX  gettext(u'See Pricing') XXXX
      XXXXXX
    XXXXXXXXXX
  XXXX XXXXX XXXXXX XXX XXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX  gettext(u'Start Now') XXXX
  XXXXXX
    XXXX XXXXXXXXX XXX XXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX X XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXX XXXXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
      XXXX XXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX gettext(u'Management') XXXXX
        XXXX XXXXXXXXXXXXXXXXX XXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Warranty Control') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Track guarantees by time or mileage with alerts and digital records.') XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Profit Reports') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Know your earnings from services, parts, or both — in real time.') XXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX gettext(u'Automation') XXXXX
        XXXX XXXXXXXXXXXXXXXXX XXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Mechanic Performance') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Measure performance, job times and track top performers.') XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Inventory Alerts') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Get notified when stock is low or inactive.') XXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX gettext(u'Client') XXXXX
        XXXX XXXXXXXXXXXXXXXXX XXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Digital Documents') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Paperless work orders, check-ins, diagnostics and receipts.') XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Customer Portal') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Clients can view invoices, service history and updates online.') XXXX
        XXXXXX
      XXXXXX
    XXXXXXXXXX
    XXXX XXXXXXXXX XXX XXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX X XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXX XXXX XXXXXXX XXXXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXX XXXX XXXXXXXX XXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX gettext(u'All-in-one Dashboard') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Everything you need in one place: jobs, inventory, clients, and more.') XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX gettext(u'Automated Reminders') XXXXX
        XX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Never miss a service or follow-up. Automated notifications for you and your clients.') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX gettext(u'Timeline of Success') XXXXX
          XXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
              XXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Register your shop in minutes') XXXXXXX
            XXXXX
            XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
              XXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Import your clients and inventory') XXXXXXX
            XXXXX
            XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
              XXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Start working smarter, not harder!') XXXXXXX
            XXXXX
          XXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX gettext(u'Real-time Analytics') XXXXX
        XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Visualize your business growth and make data-driven decisions instantly.') XXXX
      XXXXXX
    XXXXXXXXXX
    XXXX XXXXXXXXX XXX XXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX X XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'What our clients say') XXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XX
          XX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXX gettext(u'This software changed how we work forever.') XXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX X XXXXXXXX XXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XX
          XX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXX gettext(u'Bilingual support helped us migrate fast. Recommended for any shop in the USA.') XXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XX
          XX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXX gettext(u'The free trial convinced us. Now everything is digital and our customers notice.') XXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX X XXXXXXX XXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXXXXXX
    XXXX XXXXXXXXX XXX XXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX X XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXX XXXXX XXXXXXXXX XXX
    XXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXXXXXXX
        XXXXXXXXXXXXX
      XXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
         gettext(u'Ready to upgrade your workshop into a smart force?') 
      XXXXX
      XX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Start Free Today') XXXX
    XXXXXXXXXX
    XXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX
      XXXXXXXXX XXXX XXXXXXX XXXX  gettext(u'Built with AI for mechanics') XXXX
    XXXXXXXXX
  XXXXXXX
  XXXX XXXXXXX XXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
    XX XXXXXXXX XXXXX XXXXXX XX XXXXXXXX
    XXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXXXXX XXXXXXX
      XXXXXXXXX XXXXXXX
      XXXXXX XXXX
      XXXXXXXXXXXX XXXX
      XXXXXX XXXXXXXXX
      XXXXXXXXXXXXXXXX XXXXXXXXX
      XXXXXXX XXXXX
      XXXXXXXXXXXX XXXXX
      XXXXXXXX XXXX
    XXX
    XX XXXXXXXX XXXXX XXXXXXX XXXXXXX
    XXXXXXXXXXXXX
      XXX XXXXXXXXXXXX
      XXXXXX XXXXXXXXX
      XXXXXXXXXX XXX
      XXXXXXXXXXX XXX
      XXXXXXXXXX XXXX
      XXXXX XXXXX
      XXXXXXXXXXXXXXXX XXXXXXXX
    XXX
    XX XXXXXX XXXXXXXXXXX XXXXXX
    XXXXXXXXXX
      XXXXXXXXX XXXX
      XXXXX XXXXX
      XXXXXXX XXX
      XXXXXX XXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXX
    XXX
    XX XXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
    XXX
  XXXXXXXXX
XXXXXXX
XXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX
BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXX XX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX
  XXXXXXXXXXXXXXXX XXX X XXXX XXXX XXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
    XXXXXXXXXXXXXXX X X
      XXXXXX X
        XXXXXXX X
          XXXXXXX X
            XXXXXX XXXXXXXXXX
            XXXXXXXX XXXXXXXXXX
            XXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXX XXXXXXXXXX
            XXXXXXX XXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXX
          XX
          XXXXXXXXXX X
            XXXXX XX X XXXX XXXXXXXX X X XXXX XXXXXXXXX
          XX
          XXXXXXXXXX X
            XXXXXX XXXXXX XX XXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXX XXXXXX XX XXXXXXXXXX
            XXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX
          XX
          XXXXXXXXXX X
            XXXXXX X
              XXXX XXXXXX X XXXXXXXXXX XXXXXXXXXXXXXXX XX
              XXXXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
            XX
            XXXXXXXXX X
              XXXXX X XXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XX
              XXXXXXX X XXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXX X
            X
          X
        X
      X
    X
  XXXXXXXXX
  XXXXXXX
    XXXX X
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
      XXXXXXXXXXX XXXXXXX
    X
    XXXXXXXXXXXXX X
      XXXXXXXXX XXXXXX
      XXXX XX
      XXXXX XX
      XXXXXX XXXXXX
      XXXXXXX XXXXXX
      XXXXXXXX XX
      XXXXXXXX XXXXX
      XXXXXXXXXXXXXXX XXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXX XXXX XXXXXXX XXXXXX
      XXXXXXXXXXX XXXXXXX XXXXX
    X
    XXXXXXXXX X
      XXXXXXXXX XXXXXXXXX
      XXXXXX XXXX
      XXXXXXX XXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
      XXXXXXXXXXXXXX XXXX
      XXXXXXXXXX XXXXX XX XXXXXXXX XXXXXXXXXXXX
      XXXXXXXXXXX X X XXXX XXXXXXXX X X XXXX XXXXXXXX
    X
    XXXXXXXXXX XXXXX X
      XXX XXXX X XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX X
      XXX X XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXX X
    X
    XXXXXXXXXX XXXXXXXX X
      XX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXX X
      XXXX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXX X
    X
    XXXXXX X
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXXXXXX X XXX XXXX XXXXXXXXXX
      XXXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXX XXXXX XXXXX XXXXXXXXXX
    X
    XXXXXXXXXX X
      XXXXXXXXXXX X X XXXX XXXXXXXX X X XXXX XXXXXXXX
      XXXXXXX XXX XXXXX XXXXXXXX
      XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXX
    X
    XXXXXXXXXXXXXXXX X
      XXXXXXXXXXX X X XXXX XXXXXXXX X X XXXX XXXXXXXX
      XXXXXXXXXXXXX XXXXXXXX
      XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
    X
    XXXXXXXXX X
      XXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXXXX
      XXXXXXXX XX
      XXXXXXXXXX XXXXXXXXXXXXXXXXX
    X
    XXXXXX XXXXXXXXXXX XXXXXX X
      XXXXXXXXXXX X
        XXXXXXXXXX XXXXXX XXXXXXXXXXX
      X
      XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
      X
    X
  XXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
  XXXX XXXXX XXXXXXX XX XXXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX


  XXXX XXXX XXXXXXX XXX
  XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'The #1 Auto Shop Platform in the USA') XXXXX
    XX XXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Trusted by mechanics across America. Real features. Bilingual support. No risk.') XXXX
    XXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX  gettext(u'Start Free Trial') XXXX
      XX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX  gettext(u'See Pricing') XXXX
    XXXXXX
  XXXXXXXXXX

  XXXX XXXXXXXX XXXX XXX
  XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'AI Recommendations') XXXXX
      XXX gettext(u'Get smart service suggestions based on vehicle history.') XXXX
    XXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'Smart Inventory') XXXXX
      XXX gettext(u'Stay ahead with low-stock notifications and trends.') XXXX
    XXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'Paperless Invoicing') XXXXX
      XXX gettext(u'Send invoices instantly via WhatsApp or Email.') XXXX
    XXXXXX
  XXXXXXXXXX


  XXXX XXXXXXX XXXXX XXX
  XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXX gettext(u'Pricing') XXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX gettext(u'Free Trial') XXXXX
        XX XXXXXXXXXXXXX gettext(u'30 days access, no credit card.') XXXX
        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX gettext(u'Standard Plan') XXXXX
        XX XXXXXXXXXXXXX gettext(u'Full access, bilingual support.') XXXX
        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXX gettext(u'Annual Plan') XXXXX
        XX XXXXXXXXXXXXX gettext(u'2 months free.') XXXX
        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXXX

  XXXX XXXXXXXXXXX XXX
  XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX gettext(u'Testimonials') XXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XX
        XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'Before eGarage, we used Excel and paper... now everything is automated. Total change for our shop!') XXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXX XXXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XX
        XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'Bilingual support helped us migrate fast. Recommended for any shop in the USA.') XXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XX
        XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'The free trial convinced us. Now everything is digital and our customers notice.') XXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXXX

  XXXX XXXXXX XXX
  XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXX  gettext(u'All rights reserved.') XXXX
    XX XXXXXXXXXXXXXX XXXXXX gettext(u'Built for mechanics. Backed by technology.') XXXX
  XXXXXXXXX
  XXXXXXXX
    XX XXXXX XXXXXXX XX XXXXXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXXX X
      XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXX X XXX
      XXX XXXX X X XX X X XXXXXXXXXXXXXX XXXX X
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXX X XXXX
        XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXX X XXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X X X XXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X X X XX X XXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXX XXXXXXXX XX XXXXX XXXXXX
      XXXXX XXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXX XX X
          XX XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          X
        XXX
      XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXX
      XXX
    XXX
  XXXXXXXXX
XXXXXXX
XXXXXXX
