BBBB BBBBBBBBBBB
BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBB

BBBBB BBBBBBB
  XXXXXXX
    XXXXX XXXXXXXX XXXXXXX XX XXXXXX XXXXXX XXXXXX XXX XXX XXXXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXX X
      XXXXXX XXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
      XXXXXX XXXX XXXXXXXXXXX
    X
  XXXXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXX XXXXX XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXX XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XX XXXXXXXXXXXXXX
      XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX
        X XXXXXXX XXXXXXXX
      XXXX
    XXXXXX

    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXX X XXXXXXXXXX
      XXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XXXX
            XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX
          BBB BBBBBBBB BB BBBBBBBBB
          XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXXXXXXXXX
            XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFXXXXX
            XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX
              XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXX
          XXXXX
          BBBBB
          XXXX
            XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXX
          BBBBBB
        XXXXXXXX
      XXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
      XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX X XX X XXXXXXX
      XXX
    XXX
  XXX
XXXXXXXXX
BBBBBBBB
