"""
Catalogo curado de marcas y modelos comercializados en Mexico.

Se usa para poblar un catalogo propio de MX, evitando depender del bootstrap
temporal que copiaba CL -> MX.
"""

MX_MARCAS_MODELOS = {
    "Nissan": [
        "March",
        "Versa",
        "V-Drive",
        "Sentra",
        "Altima",
        "Maxima",
        "Kicks",
        "X-Trail",
        "Pathfinder",
        "Frontier",
        "NP300",
        "Urvan",
        "Murano",
        "Armada",
    ],
    "Chevrolet": [
        "Aveo",
        "Onix",
        "Cavalier",
        "Malibu",
        "Spark",
        "Sonic",
        "Tracker",
        "Trax",
        "Groove",
        "Captiva",
        "Equinox",
        "Blazer",
        "Cheyenne",
        "Silverado",
        "Tornado",
    ],
    "Volkswagen": [
        "Gol",
        "Polo",
        "Virtus",
        "Jetta",
        "Vento",
        "Passat",
        "T-Cross",
        "Taos",
        "Tiguan",
        "Teramont",
        "Saveiro",
        "Amarok",
        "Pointer",
        "Beetle",
    ],
    "Toyota": [
        "Yaris",
        "Corolla",
        "Camry",
        "Prius",
        "Avanza",
        "RAV4",
        "Highlander",
        "Hilux",
        "Tacoma",
        "Sienna",
        "Raize",
        "Sequoia",
        "Land Cruiser",
    ],
    "Kia": [
        "Rio",
        "Forte",
        "K3",
        "Soul",
        "Seltos",
        "Sportage",
        "Sorento",
        "Telluride",
        "Niro",
        "Carnival",
    ],
    "Mazda": [
        "Mazda2",
        "Mazda3",
        "Mazda6",
        "CX-3",
        "CX-30",
        "CX-5",
        "CX-50",
        "CX-9",
        "BT-50",
        "MX-5",
    ],
    "Hyundai": [
        "Grand i10",
        "Accent",
        "Elantra",
        "Sonata",
        "Creta",
        "Tucson",
        "Santa Fe",
        "Palisade",
        "Venue",
        "Kona",
    ],
    "Honda": [
        "City",
        "Fit",
        "Civic",
        "Accord",
        "HR-V",
        "CR-V",
        "BR-V",
        "Pilot",
        "Odyssey",
    ],
    "Ford": [
        "Fiesta",
        "Figo",
        "Focus",
        "Fusion",
        "Escape",
        "Edge",
        "Explorer",
        "Bronco Sport",
        "Bronco",
        "Maverick",
        "Ranger",
        "Lobo",
        "Expedition",
    ],
    "Renault": [
        "Kwid",
        "Logan",
        "Sandero",
        "Stepway",
        "Duster",
        "Captur",
        "Koleos",
        "Oroch",
        "Kangoo",
        "Megane",
    ],
    "Suzuki": [
        "Ignis",
        "Swift",
        "Dzire",
        "Baleno",
        "Ertiga",
        "Vitara",
        "S-Cross",
        "Jimny",
        "XL7",
        "Ciaz",
    ],
    "Mitsubishi": [
        "Mirage",
        "Mirage G4",
        "L200",
        "Montero Sport",
        "Eclipse Cross",
        "Outlander",
        "ASX",
        "Xpander",
    ],
    "SEAT": [
        "Ibiza",
        "Leon",
        "Toledo",
        "Arona",
        "Ateca",
        "Tarraco",
        "Cordoba",
        "Altea",
    ],
    "Peugeot": [
        "208",
        "2008",
        "301",
        "308",
        "3008",
        "5008",
        "Rifter",
        "Partner",
        "Expert",
    ],
    "Jeep": [
        "Renegade",
        "Compass",
        "Commander",
        "Cherokee",
        "Grand Cherokee",
        "Wrangler",
        "Gladiator",
    ],
    "Ram": [
        "700",
        "1200",
        "1500",
        "2500",
        "4000",
        "ProMaster Rapid",
    ],
    "Dodge": [
        "Attitude",
        "Neon",
        "Journey",
        "Durango",
        "Charger",
        "Challenger",
    ],
    "MG": [
        "MG3",
        "MG5",
        "GT",
        "ZS",
        "HS",
        "RX8",
        "MG One",
        "MG4 EV",
        "ZS EV",
    ],
    "JAC": [
        "Sei2",
        "Sei3",
        "Sei4",
        "Sei6 Pro",
        "Sei7 Pro",
        "J7",
        "Frison T6",
        "Frison T8",
        "E10X",
        "Sunray",
    ],
    "Chirey": [
        "Tiggo 2 Pro",
        "Tiggo 4 Pro",
        "Tiggo 7 Pro",
        "Tiggo 8 Pro",
        "Tiggo 8 Pro Max",
        "Arrizo 5",
        "Arrizo 8",
        "Omoda C5",
        "Jaecoo 7",
    ],
    "Audi": [
        "A1",
        "A3",
        "A4",
        "Q2",
        "Q3",
        "Q5",
        "Q7",
    ],
    "BMW": [
        "Serie 1",
        "Serie 2",
        "Serie 3",
        "X1",
        "X3",
        "X5",
        "X6",
    ],
    "Mercedes-Benz": [
        "Clase A",
        "Clase C",
        "Clase E",
        "GLA",
        "GLB",
        "GLC",
        "GLE",
        "Sprinter",
    ],
    "BYD": [
        "Dolphin",
        "Dolphin Mini",
        "Yuan Pro",
        "Song Plus",
        "Seal",
        "Han EV",
        "Tang",
    ],
}
