BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XX XXXXXXXXXXXX
  XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX  X XXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BBB B BB BBBBBBB
      XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX
          BBB B BB BBBBBBB
            XXXXXXXXX
          BBBBBB
        XXXXX
      XXXXXX
    BBBBBB
  XXXXXX
XXXXXX
BBBBBBBB
