BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXX X FFFFFFFFFFFFFFFFFXXXXXXXX
    XXXXXXX
        XX XXXXXXX XXXX XXXX XXX XX
        XXXXX X
            XXXXX XXX
            XXXXXXX XXXX
            XXXXXXXXXXX X
                XXXXXXXX XFFFFFFFFFFFFFFFFFXX
                XXXXXXXXXX XXXXX
                XXXXXX FFFFFFFFFFFFFFFFFX
            X
        X

        XXXX X
            XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXX
            XXXXXX XXXXX
            XXXXXXX XX
            XXXXXXXX XX
        X

        XX XXXXXX XXXXXXXXXXXXX XX
        XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXX XXX XXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXX X
            XXXXX XX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXX XX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXX XXX XX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXX
            XXXXXXXXXXXX XXX XXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXX FFFFFFFFFFFFFFFFFX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXX XXXX
        X

        XX XXXXXXX XX XXXXXXX XX
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXX
            XXXXXXX XXXX XX
        X

        XXXXXXXXXXXXXXX XX X
            XXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXX XX
            XXXXXXXXXXXXXX XXX XXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXXXXX XXXX
        X

        XX XXXXX XX XXXXXXXXX XX
        XXXXXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXXX XX
        X

        XXXXXXXXXXXXXX XX X
            XXXXXXXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXX XXXXXX
            XXXXXXXX XXXX XXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXX XX X
            XXXXXXXX XXXX XXXX
            XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXX XXXXXXXX X
            XXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX
        X

        XX XXXXXXX XX
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXXX
        X

        XXXXXXXXXXXXX XX X
            XXXXXXXX XXX XXXXX
            XXXXXXX XXXXX
        X

        XXXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXX XXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
        X

        XX XXXXXX XX
        XXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXX XXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXX
        X

        XXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXX XX
            XXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXX XX
        X

        XXXXXXXXXXXXXX XX X
            XXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X

        XX XXXXXXXX X XXXXXXXXXXX XX
        XXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXX
        X

        XXXXXXXXXXXXXX XX X
            XXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXX XX
        X

        XX XXXXXXXXXX XX
        XXXXXXXXXXXX X XXXXXXXXXXX XXXXXXX X
        XXXXXXXXXXX X XXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXX X XXXXXX FFFFFFFFFFFFFFFFFX X
        XXXXXXXXXXXXXXX X XXXXXX FFFFFFFFFFFFFFFFFX X
        XXXXXXXXXX X XXXXXXXXXXXX XXXXX X
        XXXXX X XXXXXXXXXXXXXX XX X
        XXXXXX X XXXXXXXXXXX XXXXX X

        XX XXXXXXXXXX XXXX XXXXXXXXX XX
        XXXXXX XXXXX X
            XXXXXXXXX X XXXXXXXX XXXXX X
            XXXXXXXXXXX X XXXXXXXXXXXXXXXXXX XXXXXXX X
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXX XXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBB BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXX XXXXXFFFFFFFFFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXX
            BBBBB

            XXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFXXXXX

            BB BBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB

            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBB
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                BBBBB
                BB BBBBBBBBBBBBB
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                BBBBB
                BB BBBBBBBBBBBBB
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                BBBBB
                BB BBBBBBBBBBBBBB
                    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                BBBBB
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXFFFFF XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFXXXXXX
            BB BBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFXXXXXX
            BBBBB
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXX XXXXXXX XXX
    BB BBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                BB BBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXX XXXX
                BBBBB
                BB BBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXXXXX XXXX
                BBBBB
            XXXXXX
            XXXXX
                BB BBBBBBB
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
                BBBBB
            XXXXXX
        XXXXXX
    XXXXXX
    BBBBB

    XXXX XXXXXXXXX XXXXXXXXX XXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBB BBBBBBBBBBBBBBBB
        XXXX XXXX XXXXXX XXXX XXXXXXXXXXX XXX XXX XXXXXXXXX XXXXXXXXXXX XXX
        BBBBBBBB
    XXXXXX

    XXXX XXXXXXX XXX
    BB BBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBB
            XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
            XXXXX
            BBBBB

            BB BBBBBBBBBB
            XXXX
                XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
            XXXXX
            BBBBB

            BB BBBBBBBB
            XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
            XXXXX
            BBBBB

            XXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXXXXXXXXXXX
            XXXXX
        XXXXXXXX
    XXXXXX
    BBBBB

    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
                XXXFFFFFFFFFFFFFFFFFXXXX
                BB BBBBBBBBBBBBBBB
                    XXXXXXX
                BBBBB
                BB BBBBBBBBBBBBB
                    XXXXXXX XXXX
                BBBBB
                BB BBBBBBBBBBBBB
                    XXXXXXX
                BBBBB
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX XXXXXXXXXXX
                BB BBBBBBBBBBBBBB
                    XXXXXXX XXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXXXXXXXXXX XXXX
                BBBBB
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX
                XXXFFFFF XX XXXX
                XXXXXXXXXXXX FFFFFFFFFFF FFFFXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXX X XXXXXXXXXXX XXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX X XXXXXXXXXXXXXXXX
        XXXFFFFFFFFFFXXXX
    XXXXXX
    BBBBB

    XXXX XXXXXXX XX XXXXX XX XX XXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXX
    BB BBB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBB BB BBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXX XXXXXXX
        XXXXXXXXXXX XXX XXXXXXX XXX X XXXXXXX XX XXXXXXX XX XXXXXXXXXXXX
    XXXXXX
    BBBBB
XXXXXXX
XXXXXXX
