
BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
     gettext(u'Payment Status') 
  XXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXX gettext(u'Pending') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX gettext(u'Paid') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXX gettext(u'Partial') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Canceled') XXXXXXXXX
  XXXXXXXXX
XXXXXX
