BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXBBBBB BBBBBXXXXXXXBBBBBBBBXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
    XXXXX X
      XXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFX
      XXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFX
    X
    XXXXXXXXXXXXXXX X
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX
      XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXX X
      XXXXXXXXXXX XXXXX
      XXXXXXXXXX XXXXXX
      XXXXXXXXXXX XXXXXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXX XXXXX
      XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXX X
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXX XXXXXXX
      XXXXXXXXXXXX XXXX
      XXXXXXXXXXXXXXX XXXX
    X
    XXXXXXXXXXXXXXXX X
      XXXXXX XXXXXXXX
      XXXXXXXXXX XXXXXXX
      XXXXXXXXXXXX XXXX
      XXXXXXXXXXX XXXX
      XXXXXXXXXXXXXXX XXXX
    X
    XX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXX XX XXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX X
      XXXXXXXX XXXXXXXXXXXX
      XXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXX
      XXXXXXXX XXXXXXX XXXXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXX XXXXX XXX XXXXXXXX XXX XXX XXXXX XXXXXX
      XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
      XXXXXXXXXXXXXX XXXX
      XXXXXXXXXXXXXXXX XXXXX
      XXXXXX XXXXXXXX
      XXXXXXXXXXXX XXXX
      XXXXXXXXXX XXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
      XXXXXXXXX XXXXXXXXX
      XXXXXXXXX XXXXXXXX
      XXXXXXXXXXXX XXXXXXX
      XXXXXXXXXX XXXXXXXX
    X

    XX XXXXX XXXXXXXXX XXXX XXXXXXX XXX XX XXXXX XXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXX XXX
      XXXXXXXXX XXXXXXXXX
      XXXX XXXXX
      XXXXX XXXXX
      XXXXXX XXXXX
      XXXXXXX XXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX 
        XXXXXXXXXXX XXXX 
        XXXXXXX XXXX XXXX XXXX XXXX 
        XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXXX XXX
      XXXXXXXX XXXX
      XXXXXXXXXX XXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXX
      XXXXXXXXXXXXXXXX XXXX XXXXX
    X

    XX XXXXXX XX XXXXXX XXX XX XXXXXXXX XXXXX XX XXXXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXX XXX
      XXXXXXXXX XXXXXXXXX
      XXXX XX
      XXXXX XXXXXX
      XXXXXX XXXXX
      XXXXXXX XXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX 
        XXXXXXXXXXX XXX 
        XXXXXXX XXXX XXXX XXXXX XXXX
        XXXXXXX XXXX XXXX XXXXX XXXX
        XXXXXXX XXXX XXXX XXXXX XXXX
        XXXXXXXXXXX XXXXXX
      XXXXXXXXXXXXXX XXXX
      XXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXX
      XXXXXXXXXXXXXXX XXXXX
    X

    XXXXXXXXXX XXXXXXXXXXXXXXX X
      XX X
        XXXXXXXXXXXXXXXXXXXX XX XXX
        XXXXXXXX XXXX
      X
      XXX X
        XXXXXXXXXXXXXXXXXXXX XXXX XXX
        XXXXXXXX XXXX
      X
      XXX X
        XXXXXXXXXXXXXXXXXXXX XXXX XXXXX
        XXXXXXXX XXXX
      X
      XXX X
        XXXXXXXXXXXXXXXXXXXX XX XXXXX
        XXXXXXXX XXXX
      X
      XXXX X
        XXXXXXXXXXXXXXXXXXXX XX XXX
        XXXXXXXX XXXX
      X
    X

    XXXXXXXXXX XXXXXXXXXXX X
      XX X
        XXXXX XXXXXX
        XXXXXXXX XX
      X
      XXX X
        XXXXXXXX XX
      X
      XXXX X
        XXXXX XXXXX
        XXXXXXXX XX
      X
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX
      XXXXXX XXXXXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXX XXXXXXXX XXX XXX XXXXX XXXXXX
      XXXXXXXXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        XXXXX X XXX X XXXXXXX XXXX XXXX XXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXX XX
      XXXXXXXXXXXXXXXXXXX XXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXX XXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXX XXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
      XXXXXXXXXX XXXXX
      XXXXXXX XXXXXXXXXXXXX X XXX XXXXXXX XXXX XXXX XXXXXX
      XXXXXXXXXXX XXXXXX XXXX XXXXX
      XXXXXXXXX XXXXXXXXX
      XXXXXXXX XX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
      XXXXXXX XXXXXXXXXXXXX X XXX XXXXXXX XXXX XXXX XXXX
    X

    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
      XXXXXXXXX XXXXXXXXX
      XXXXXXXX XX
      XXXXXXXXXXXX X X XXX XXXXXXX XXXX XXXX XXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
      XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    X

    XX XXXXXX XXXX XXXXX XX XXXXX XXXXX XXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX
      XXXXXX XXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX 
        XXXXXXXXXXX XXXX 
        XXXXXXXXX XXX XXX XXXX XXXX 
        XXXXXXXXXXX XXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX 
        XXXXXXXXXXX XXX 
        XXXXXXXXX XXX XXX XXXXX XXXX
        XXXXXXXXX XXXX XXXX XXXXX XXXX
        XXXXXXXXX XXX XXX XXXXX XXXX
        XXXXXXXXXXX XXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX
      XXXXXXXXXXX
        X X XXXX XXXXXXXXX XXX XXX XXXXX
        X X XXXX XXXXXXXXX XXX XXX XXXXX
        X X XXXX XXXXXXXXX XXX XXX XXXXX
        XXXXX X XXX X XXXXXXXXX XXXX XXXX XXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
      XXXXXXX XXXXXXXXXXXXX X XXX XXXXXXXXX XXX XXX XXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
      XXXXXXX XXXXXXXXXXXXX X XXX XXXXXXXXX XXXX XXXX XXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
      XXXXXXXXXXXX X X XXX XXXXXXXXX XXX XXX XXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
      XXXXXXXXXXXX X X XXXX XXXXXXXXX XXXX XXXX XXXXX
    X
    XXXXXXXXXXXXXXXX X
      XXXXXXXX XXXXX
      XXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXX
      XXXXXXX X XXXX XXXXXX XXXXX
      XXXXXXXXXX XXXXX
      XXXXXXXX XXXXXX XX
    X
  XXXXXXXX
  BBBBB BBBBBBBBBBBBBBBBBB
  BBBBB BBBBBBBBBBBBBBBBB
XXXXXXX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
        BB BBBBBBBBBBBBBBBB
          XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        BBBBB
        XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFXXXXXX
          BB BBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX
    XXXXXX
  XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XX XXXXXXXXXX XXXXXXXXX X XXXXX XXXXXXXXXX XXX
    BBBBBBBBBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
    BB BBBBBBBBBBB
    XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX gettext(u'Ajustes') XXXXXXX
    XXXX
    BBBBB

    XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX gettext(u'Centro') XXXXXXX
    XXXX

    XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX gettext(u'Clientes') XXXXXXX
    XXXX

    XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX gettext(u'Documentos') XXXXXXX
    XXXX

    XX XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX gettext(u'Extra') XXXXXXX
    XXXX

    XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX gettext(u'Repuestos') XXXXXXX
    XXXX

    XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX gettext(u'Reportes') XXXXXXX
    XXXX

    XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
      BBBBBBBBBB
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX gettext(u'Salir') XXXXXXX
      XXXXXXXXX
    XXXXXXX

    XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX gettext(u'Servicios') XXXXXXX
    XXXX

    XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX gettext(u'Vehículos') XXXXXXX
    XXXX
  XXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXX
    BBBBB BBBBBBBBBBBBBBB
  XXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
    XXXXXX XXXX XXXXXXX
  XXXXXXXXX
  BBBBB BBBBBBBBBBBBBBBB
XXXXXXX
XXXXXXX
