BBBB BBBB BBBBBB BBBBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXX X XXX X XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX
XXXXXXX
  XXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXX XXX XXXXXXXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX XXXXXXX
  X

  XX XXXXXXXXXX XXXXXXXXX XXXXXXXX XX
  XXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
                XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
                XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXXX XXXX XXXXX XXX XXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXXXXX XXX
  X

  XXXXXXXXXX XXXXXXX X
    XX X XXXXXXXX XXXX XXXXXXXXXX XXXXXXXXX X
    XXXX X XXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXX X
  X

  XXXXXXXXXX XXXXXXXX X
    XX X XXXXXXXXXXX X X XXX XXXXXXXX X X XXXX XXXXXXXX X X XXXX XXXXXXXX X
    XXXX X XXXXXXXXXXX X X XXXX XXXXXXXX X X XXXX XXXXXXXX X X XXXX XXXXXXXX X
  X

  XXXXXXXXXX XXXXXXXXXXX X
    XX X XXXXXXXXXX XXXXXXXXX XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX X
    XXXX X XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX X
  X

  XXXXXXXXXX XXXX X
    XXX XXXX X XXXXXXXXXXXX X X XXX XXXXXXXX X X XXXX XXXXXXXX X X XXXX XXXXXXXX X
    XXX X XXXXXXXXXXXX X X XXXX XXXXXXXX X X XXXX XXXXXXXX X X XXXX XXXXXXXX X
  X

  XX XXXXXXXX XX XXXXXXXXXX XX
  XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX
    XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXX XXXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
  X

  XXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXX XXXXX
  X

  XXXXXXXXX XXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXX XXXXXXXXXXXXX X XXXX XXXXXXX XXXX XXXX XXXXXX
  X

  XXXXXXXXX XX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXX XX
    XXXXXXXXXX XXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
  X

  XXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
  X

  XXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXX XXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XXXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
    XXXXXXXXXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXX
  X

  XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXX
    XXXXXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
  X

  XXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXX X XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXXXXXXX X XXXXXX
  X

  XX XXXXXXX XXXX XX XXXXXXXXXX XX
  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
                X X XXXXX XXXXXXX XXXX XXXX XXXXX
                XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXX XXXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
    XXXXXX XXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXX X XXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XXXXX
    XXXXX XXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXX
    XXXXXXXXXX XXXXXXX XX XXXXXX XXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
                XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXX
  X

  XXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
                 X X XXXX XXXXXXX XXXX XXXX XXXXX
                 X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXX XXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXX
    XXXXXXXXX XXXXXXXXX
    XXXXX XXXXXX
    XXXX XXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXX XX XXXXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXX XXXXXX
    XXXX XXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXX XX XXXXXXXXXXX XXXXXXXX XXX
  X

  XXXXXXXXXX XXXXXXX X
    XXX XXXX X XXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX X
    XXX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX X
  X

  XX XXXX XXXXXXX XXXXXXXX XX XXXXXX XX
  XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX X XXXX XXXXXXXXXXXXXXXXXXXX XXXXX X X XXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXX X XXXX XXXXXXXXXXXXXXXXXXXX XXXXX X X XXXX XXXXXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX X XXXX XXXXXXXXXXXXXXXXXXXX XXXXX X X XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXX XXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXX XX XXXXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXX
    XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXX XXXX X XX
  X

  XXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXX
    XXXXXXXXXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXXX
    XXXXXXXXXXXXXXX XXXXXXX
  X

  XX XXXXXXX XXX XXXXX XXXXXXXX XXXX XXXXX XX
  XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXX XX XXXXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
                X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XXXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
    XXXXXXXXXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XXXXX
    XXXXX XXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXX
    XXXXXXXX XX
    XXXXXXXXXXX XXXXXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XX
  X

  XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
                X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXX XXXX XXXXXX
    XXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXX XXXX XXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXXX XXXX XXXX XXXXX
  X

  XX XXXXXXX XX XXXXXXXXXX XX
  XXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXX XXXX
    XXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXX X XXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXX X
  XXXXXXXXXXXXXXXXXXXXXX X XXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXX X
  XXXXXXXXXXXXXXXXXXXXXX X XXXX XXXX XXXXXX XXXX XXXXXXXXXXXXXXXX XXX X
  XXXXXXXXXXXXXXXXXXXXXX X XXXXXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXX X
  XXXXXXXXXXXXXXXXXXXXXX X XXXXXXX XXXX XXXXXX XXXX XXXXXXXXXXXXXXXX XXX X

  XXXXXXXXXX XXXXX X
    XXX XXXX X XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXX X
    XXX X XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XX X
  X

  XX XXXXXXX XXXX XXXXXXXXXXXXXX XX XXXXXXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXX XXXXX
  X

  XX XXXXXXX XXX XX XXXXXXXX XXXXXXX XXXXX XXX XXXXXX X XX XXXXXXXXXX XXXXX XX XX XXXXXXX XX
  XXXXXXXXXXXXXXXX X XXXXXXXXX XXXXXXXX X
  XXXXXXXXXXXXX X XXXXXXXXX XXXXXXXX X

  XX XXXXXXXX XX XXXXXXX XXXX XX XXXXXX XX XX XXXXXXXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXXXXX XX X

  XX XXXXXXXX XXX XXXXXXXXXXXXXX XX
  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXX XXXXX
    XXXXX XX
    XXXXXX XX
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXX XXXXXXX XX XXXXX XXX XXXXXX XX
    XXXXXXXXXXX XXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXX
  X

  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXX
  X

  XXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXX XXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXXXX X
    XXXXX XX
  X

  XXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXX X X XXX XXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXX XXXX
  X

  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXX XXXXX
    XXXXXXXXXX XXXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
  X

  XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX XX XXXXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXXX XXX XXX XXXXX
    XXXXXXXXXX XXXXXXXXXXX
  X

  XX XXXXXXX XXXX XXXXXX XXX XXXXXX XXXXXXXX XXXXXX XX
  XXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXX XXXX
  X

  XX XXXXXXXXX XXXXXXXX XXXX XXXXX XXX XXXXXX XX
  XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXX
  X

  XXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXX XXXX
    XXXX XXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXX XXXXXX
    XXXXXXXX XXX XXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXX XXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXX
  X

  XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
  X

  XX XXXXX XXXX XXXXXXX XXXXX XXXXXXXX XX
  XXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXX XXXXXX
    XXXXXX XXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
  X

  XXXXXXXXXXXXXX XX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXX XXX XXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX
    XXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
  X

  XX XXXXXX XXX XXXXXXXX XX
  XXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
  X
XXXXXXXX

XXXX XXXXXXXX XX XXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXX XXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXX XXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXX XXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Create Vehicle') XXXXX
    XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Vehicle registration form') XXXX

    XXXX XXXXXXXXXX XXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      BBBBBBBBBB

      XXXX XXXXXX XX XXX XXXXXXXX XXX
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX

        XXXX XXXXXXX XXXXXXXXX X XXXXXXXX XX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Client Information') XXXXX

            XXXX XXXXX XX XXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Search Client')  XXXXXXXXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                     XXXXXXXXXXXXX gettext(u'Type client name, email, phone or ID...') X XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX

            XXXX XXXXXX XXXXXXXXXX XXXXXXXX XXXX XXX XX XXXXXXXX XXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

            XXXX XXXXX XX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Client')  XXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFF
              BB BBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX

            XXXX XXXXXXX XXXXXXXXXXXX XXXXXXX XX XXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXX XXXXXXX X XXXXX XXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXX XXX XXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Vehicle Data') XXXXX

        XXXX XXXX XXXXX XXX
        XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX
           gettext(u'Core Specs') 
        XXXXX

        XXXX XXXXXXX XXXXX XXXX XXXXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXX XXX
          XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              X  gettext(u'Year')  X
            XXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFF
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
              X  gettext(u'Add') 
            XXXXXXXXX
            BB BBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                
              XXXXXX
            BBBBB
          XXXXXX

          XXXX XXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              X  gettext(u'Brand')  X
            XXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFF
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
              X  gettext(u'Add') 
            XXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                
              XXXXXX
            BBBBB
          XXXXXX

          XXXX XXXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              X  gettext(u'Model')  X
            XXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFF
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
              X  gettext(u'Add') 
            XXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                
              XXXXXX
            BBBBB
          XXXXXX
        XXXXXX

        XXXX XXXXXXX XXXXX XXXXXXXX XXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XX  gettext(u'License Plate') 
            XXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFF
            BB BBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                
              XXXXXX
            BBBBB
          XXXXXX

          XXXX XXX XXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              X  gettext(u'VIN') 
            XXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFF
            BB BBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                
              XXXXXX
            BBBBB
          XXXXXX

          XXXX XXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              X  gettext(u'Color') 
            XXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFF
            BB BBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                
              XXXXXX
            BBBBB
          XXXXXX
        XXXXXX

        XXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XX  gettext(u'Engine') 
            XXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFF
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
              X  gettext(u'Add') 
            XXXXXXXXX
            BB BBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                
              XXXXXX
            BBBBB
          XXXXXX

          XXXX XXXXXXXXXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              X  gettext(u'Transmission') 
            XXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFF
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              X  gettext(u'Add') 
            XXXXXXXXX
            BB BBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                
              XXXXXX
            BBBBB
          XXXXXX
        XXXXXX
      XXXXXX

        XXXXXX XXXX XXXXXX XX XX XXXXXXX XXXXXXX XXX
      XXXXXX XXXX XXXXXX XXX XXXX XX XXX XXXXXXXX XXX

      XXXX XXXXXXX XX XXXXXX XXX
      XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXX
           XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX gettext(u'Cancel') XXXXXXX
        XXXX

        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX gettext(u'Create Vehicle') XXXXXXX
        XXXXXXXXX
      XXXXXX
    XXXXXXX
  XXXXXX

  XXXX XXXXXX XXX XXXXXXXXXX XXX
  XXXX XXXXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXX gettext(u'Vehicle registration form') XXXXXXX
      XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXXXX

XXXX XXXXX XXXX XXXXXXX XXXXXX XXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXX gettext(u'Add New') XXXXX
    XXXXX XXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
      XXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Name')  XXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
               XXXXXXXXXXXXX gettext(u'Enter name...') X XXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Cancel') 
        XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
           gettext(u'Add') 
        XXXXXXXXX
      XXXXXX
    XXXXXXX
XXXXXX
XXXXXX

XXXXXXXX
XX XXXXXXXX XXXXXXXXXXX XX XXXXXXXX XX XXXXXX XXXX
XXX XXXXXXXXXXXXXX
XXX XXXXXXXXXXXXXX X XXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        XX XX XXXXXXX XXXXXX XXXX XX XXXXXXXX XXXX XXX XXXX XXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX X XXXXX
        XXX
    X
    XXXXXXXX XXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXX X XXXXXX
    X

    XX XXXXXX XX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXX

        XX XXXXXXX XXXXXXX XXXXXXXX
        XX XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XX XX XXX XXXXX XX X XXXXXXXXXXX XXXXXXX XXXXXXXXXX
        XX XXXXXXXXXXXXX X XX X
            XXXXXXXXXXXXXXX
            XXXXXXX
        X

        XX XXXXXXXXX XXXXXXX XXXXX XXXXX XX XXXXXX
        XXXXXXXXXXXXX X XXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXX
        XX XXXXX
    XXX

    XX XXXXXXX XXXXXXXXXX XX XXXXX XXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXX
        X
    XXX

    XXXXX XXXXXXXX XXXXXXXXXXXXXXXX X
        XXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX
            XXXXX XXXX X XXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXX X XXXXX XXXXXXXXXXXX

            XX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX X
            XX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXXXXXXXX XXXXXXX X

            XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XX X
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
            XXXXXXXXXXXX
            XX XXXXXXXXX XXXX XXX XX XXXXXX XX XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX X XXXXXX
        X XXXXX XXX X
            XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXX
        X
    X

    XX XXXXXXX XXXX XXXXXXX XXXXXXXXX XXX XXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
        XXXXX XXXXX X XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
        XXXXX XXXX X XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
        XXXXXX XXXXX X XXXX XX XXXX
    X

    XX XXXXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX XXXX XX XXXXXXX
    XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXX XXXXXXXXX X
        XXXXXXXXXXXXXX X X XXX XXXXX XXXXXXXX XXXXXXX XXXXXXXX XX

        XX XXXXXXXXXX XXXXX XX XXXXXXX
        XX XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXX X XXX
        X

        XX XXXXXXXXXX XX XXXXX XX XXXXXXX XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXX X
            XX XXXXXX XX XXXXXX XXXXXXXXXXXXXXX XX XXXXXXX XXXXXXXXXXXX
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXX XXXXXX XX XXXXXXXX X
                XX XXXXXXXXXXXXX XX XXX X
                    XXXXXXXXXXXXXXX X XXXXX
                    XXXXXX
                X
            X
        X

        XX XXXXXXX XXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXX X XXXXX XX XXXXXXX XX XXXXXX XX XX XXXXX XX XXXXXXXX
        XXXXXXXXXXXXXXX
    XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X
        XXXXXXXXXXXXXX X XXXXX

        XX XXXXXXX XXXXX XXXXXX
        XX XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXX X XXX
        X

        XX XXXXXXX XX XXXXX XX XXXXXXX XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX XX XXXXXXXXXXX XX XXXXXXX XXXXXX XXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXX X XXX
        XXXXXXXXXXXXXXX
    XX

    XX XXXXXXXXX XX XX XXX XX XXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXX
    XX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX X
        XX XX XXX XX XXXXXX XXXXXX XX XXXXXXXXXXX XXX XXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX X
            XX XXXX XXXXXXX XXXXX XXX XXXXXXX XXXX XXXXXXX XXX XXXXX XXX XXXXXXX
            XX XXX XXXXXX XXXX XXXXXXXXX XXX XXX XX XXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX X X XXXXXXXXX
        X
    X

    XX XXXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXX X XXXXX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX X XXXXX
        X
        XX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX X XXXXX
        X
        XX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX X XXXXX
        X
    X

    XX XXXXXXX XXXX XXXXXX XXXXXXX XXX XXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXXXX XXXXXXX

                XXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX X XXXXX

                XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
                    XXXXXXXXXX XX X
                        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXX XX X
                            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXX X XXXXXXXXXX
                            XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX
                        XXXXXXXXXXXXXXXXXXXX X XXXXXX
                    XX
                    XXXXXXXXXXXX XX X
                        XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX
                        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXX X XXXXXX
                    XXX
    X

    XX XXXXXXX XXXX XXXXXX XXXXXXX XXX XXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXXX XXXXXXX

        XXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX X XXXXX

        XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
            XXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XX X
                    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX X XXXXXXXXX
                    XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX
                XXXXXXXXXXXXXXXXXXX X XXXXXX
            XX
            XXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX X XXXXXX
            XXX
    X

    XX XXXXXXX XXXX XXXXXX XXXXX XXX XXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXX XXXXXXX

        XXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX X XXXXX

        XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
            XXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX XX X
                    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX X XXXXXXXX
                    XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX
                XXXXXXXXXXXXXXXXXX X XXXXXX
            XX
            XXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX X XXXXXX
            XXX
    X

    XX XXXXXXXXXXX XX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXX

            XX XXXXXXX XXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX

            XX XXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX

            XX XXXXXXX XXXXXXX X XXXXX
            XX XXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX X XXXXX
            X
            XX XXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX X XXXXX
            X

            XX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX X
                XX XXXXXX XXXXXXX X XXXXX XX XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            X
        XXX
    X
XXX

XX XXXXXXXXX XXXX XX XXXXX XX XXXXXXX XXXXXX XXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX X XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Enter')  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX X XXXXXXX
X

XX XXXXXXX XX XXXXX XXX XXXXXXXXXX XXX XXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXX X
        XXXXXXX gettext(u'Please enter a name') XXX
        XXXXXXX
    X

    XX XXXXXXX XX XXXXX XXXXXX XX XXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

    XX XXXXXX XX XXXXX
    XXXXXXXXXXXXXXXXXXX
XXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXX XXXXXXX

    XX XXXX XXXXXXX X XXXXXX XXXXXXXXXXX XXXXX XX XXXXXXXX XX XX XXXXXXXX
    XX XXXXXXXXXX XXX XXXXXXX XX XXXXXXXXX XXX XXXXXXX X
        XX XXXXXXX XXXXX X XXXXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX X
            XXXXXXX gettext(u'Please select brand and model first') XXX
            XXXXXXX
        X

        XX XXXXX XX XXXXXXXX XX XX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    X XXXX X
        XX XXXX XXXXX XXXXXX XXXXX XXXXXX XXXXXXXX XXXX XXXXXXX XX XXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXX X XXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX  gettext(u'added successfully') XXX
    X
X

XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
    XXX X
        XX XXXX XXXX XXX XXXXXXX XXX XXXXXXXX XX XXXXXX XXX XXXXXXXXX
        XX XXXXXXXXXXX XXXXX XX XXXXXXXXXX XXX XXXXXXXXX X XX XXXXXX XXXXXXXXXX
        XX X XXXXX XX XXXXXX XXXXXXX XX XX XXXXXX XX XX XX

        XX XXXXX XX XXXXXXXX XX XX XXXXXXXX XXX XXXXXXXXX XXXX XXX
        XXXXX XXXXXXXX X XXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXX X
            XXXXXXX XXXXXXX
            XXXXXXXX X
                XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX
            XXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXX
                XXXXXXX XXXXXXXXXX
                XX XX XXXXXX XXXXXXXXX XXXX XXX XX XXX XXX XXXXXXX XXX XXXXXXXX XX XXXXXX XX
                XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX
        XXX

        XXXXX XXXXXX X XXXXX XXXXXXXXXXXXXXXX

        XX XXXXXXXXXXXXX X
            XX XXXXXXX XX XXXXX XXXXXX XX XXXXXX
            XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX X XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX X XXXXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'added successfully') XXX
        X XXXX X
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        X
    X XXXXX XXXXXXX X
        XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXX
        XXXXXXX gettext(u'Error creating record') XXX
    X
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XX XXXXX XXXXXXXX XX XXXXXXX XXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX X X
        XXXXXXXXX XXXXXX
        XXXX XXXXX
        XXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXX XXXXXX
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
        XXXXXXXX XXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXXXX XXXX XXXXX
    XX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXX XXXXXXX XX X XXXXXXXX
    XXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX XXXX XXXXXX
        XXXXXXXXXXXXX XX X
            XX XXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XX XXXXX
    XX XXXXXX
X

XX XXXXXX XXXXX XX XXXXX XXXX XXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XX XXXXXXXXX XXX XXXXX X
        XXXXXXXXXXXXXXXXXXX
    X
XXX

XX XXXXXX XXXXX XXX XXXXX XXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XX XXXXXX XXX XXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX
    X
XXX

XX XXXXXXX XXXXXXX XXX XXXX XXX XXXXXXXXXXX
XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXX X X
    XXXXXXXXXX XXXXXXX X
        XXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XX X XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XX X
    X
    XXXXXXXXXX XXXXXXXX X
        XXXX X XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XX X
        XX X XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XX X
    X
XX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX
XXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXX X XXX XXX XXXXXXX XXXXXXXXXXXXX XXX XXXXXXX XXXXXX XXX

XXXXXXX
XXXXXXX
