BBBB BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXX gettext(u'Agregar caja') XXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
  XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
XXXXXXX
XXXXXX
  XXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Agregar caja') XXXXX

    XXXXX XXXXXXXXXXXXXX
      BBBBBBBBBB
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXFFFFFFFFFFXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXFFFFFFFFFFXX

      XXXXXXX gettext(u'Nombre de la caja')  XXXXXXXXX
      XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXX XXX XXXXX XXXX XXXXXX

      XXXX XXXXXXXXXXXX
        XXXXX
          XXXXXXX gettext(u'Modelo (referencia)') XXXXXXXX
          XXXXXX XXXXXXXXXXX XXXXXXXFFFFFFFFFFFX XXXXXXXX XXXXXXXXXXXXXX
        XXXXXX
        XXXXX
          XXXXXXX gettext(u'Estado') XXXXXXXX
          XXXXXX XXXXXXXXXXX XXXXXXXBB BBBBBBBBB gettext(u'Se asociará al modelo') BBBB gettext(u'Caja general') BBBBBX XXXXXXXX XXXXXXXXXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXXXXXXX
        XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Guardar') XXXXXXXXX
      XXXXXX
    XXXXXXX
  XXXXXX
XXXXXXX
XXXXXXX
