BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXX XXXXXXX XXX
XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXX XXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXX XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXX XXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXX
  XXXX XXXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
               gettext(u'Vehicle Details') 
            XXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX gettext(u'Complete vehicle information') XXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX
             XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Edit') XXXXXXX
          XXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
             XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Back') XXXXXXX
          XXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX

      XXXX XXXX XXXXXXX XXXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

        XXXX XXXXXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXX
              XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Vehicle Overview') XXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXXXXXXXXX
                XXXXX
                  XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Brand') XXXXXXXX
                  XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  XXXX
                XXXXXX
                XXXXX
                  XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Model') XXXXXXXX
                  XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  XXXX
                XXXXXX
                XXXXX
                  XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Year') XXXXXXXX
                  XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXX
                XXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBB
                XXXXX
                  XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'License Plate') XXXXXXXX
                  XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                BBBBB
                BB BBBBBBBBBBBB
                XXXXX
                  XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'VIN') XXXXXXXX
                  XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                BBBBB
                BB BBBBBBBBBBBBBB
                XXXXX
                  XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Color') XXXXXXXX
                  XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                BBBBB
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXX XXXXXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXXXXX
              XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Technical Specifications') XXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
                XXXXX
                  XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Engine') XXXXXXXX
                  XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  XXXX
                XXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
                XXXXX
                  XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Transmission') XXXXXXXX
                  XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  XXXX
                XXXXXX
                BBBBB
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXX
                XXXXX
                  XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Registration Date') XXXXXXXX
                  XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFF FF FFXXXX
                XXXXXX
                XXXXX
                  XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Last Updated') XXXXXXXX
                  XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFF FF FFXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXX XXX
        BB BBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXX
              XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Observations') XXXXX
            XXXXXX

            XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        BBBBB
      XXXXXX

      XXXX XXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXX

        XXXX XXXXXX XXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXX
              XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Client') XXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXX
              XXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Name') XXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                  FFFFFFFFFFF FFFFFFF
                XXXX
              XXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBB
              XXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Email') XXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX
              BBBBB
              BB BBBBBBBBBBBBBBBBBBBBBBBBB
              XXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Phone') XXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX
              BBBBB
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXX
              XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Quick Actions') XXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXX
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX
                 XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX
                XXXXXX gettext(u'Edit Vehicle') XXXXXXX
              XXXX

              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
                 XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
                XXXXXX gettext(u'View All Vehicles') XXXXXXX
              XXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
