BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBB

BBBBB BBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXX
X X
    XXXXXXX XX
    XXXXXXXX XX
    XXXXXXXXXXX XXXXXXXXXXX
X

XXXX X
    XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
    XXXXXX XXXXX
    XXXXXXXXXX XXXXXX
    XXXXXXXX XXXXX
X

XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
X

XXXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXX
X

XXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXX X
    XXXXXXXX XXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
X

XXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXX XXXXX
X

XXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X X X XXX XXXXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
X

XXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXX
    XXXXXXXXXXXX XXXX
X

XXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXX XXXX
    XXXXXXX XXXXXXXX
X

XXXXXXXXXXXX XXXXX X
    XXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXX XXXXXXXX
X

XXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXX XXX XXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXX X X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXX XXXXX
X

XXXXXXXXXXXXXXXX XXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXX
X

XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXXX XXXXXXXX
X

XXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
X

XXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXX XXXXX
X

XXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXX XXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXXXXXXXXXX X
        XXXXXXXX XXXX XXXXX
    X

    XXXXXXXXXXX X
        XXXXXXXXXX XXXXX
    X

    XXXXXXXXXXXX X
        XXXXXXXXXX XXXXX
    X
X

XX XXXXX XXXXXXXX XX
XXXXXX X
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
X

XXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXX X XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
        BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BB BBBB BB BBBBBBB BB BBBB BB BBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        BBBB BBBB BB BBBBB BB BBBB BB BBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
        BBBBB
        BBBBBBB
    XXXXXX

    XXXX XXXXXX XXX
    XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Sign In') XXXXX

    XXXX XXXXXXXX XX XXXXX XXX
    BB BBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX
        
    XXXXXX
    BBBBB

    XXXX XXXXXXXXXX XXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBXX
        BBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX

        XXXX XXXXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                 gettext(u'Email or Username') 
            XXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFF FFFFFF
            BB BBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
            XXXXXX
            BBBBB
        XXXXXX

        XXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                 gettext(u'Password') 
            XXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFF FFFFFFFFF
            BB BBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXX
            BBBBB
        XXXXXX

        XXXX XXXXXXXX XX XXX
        BB BBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXX
            
            XXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Remember me') XXXXXXXX
        XXXXXX
        BBBBB

        XXXX XXXXX XXXXXX XXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
             gettext(u'Sign In') 
        XXXXXXXXX
    XXXXXXX

    XXXX XXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
             gettext(u'Forgot your password?') 
        XXXX
    XXXXXX

    XXXX XXXX XX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u"Don't have an account?") XXXXXXX
        XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX
             gettext(u'Sign up') 
        XXXX
    XXXXXX
XXXXXX
BBBBBBBB
