BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Company Settings')  X XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
  XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      
      XXX XXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
         gettext(u'Company Settings') 
      XXXXX
      
      XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXX XXXXXXXXXXX XX XX XXXXXXX XXX
        XXXX XXXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'Company Information') XXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  
                  
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  
                  
                XXXXXX
              XXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  
                  
                  BB BBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXX
                      XXXX XXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                    XXXXXX
                  BBBBB
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  
                  
                  XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                     gettext(u'Brand color for UI customization') 
                  XXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        
        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'Contact Information') XXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  
                  
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  
                  
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  
                  
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        
        XXXX XXXXXXXXX XXXXX XXX
        XXXX XXXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Legal Address') 
            XXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXX X XXXXXX X XXXXXX XXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  
                  
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'State/Department') XXXXXXXX
                  XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                     gettext(u'Select country first') 
                  XXXXXXXX
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  
                  
                XXXXXX
              XXXXXX
            XXXXXX
            
            XXXX XXXXXXXXX XXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  
                  
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  
                  
                XXXXXX
              XXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  
                  
                XXXXXX
              XXXXXX
            XXXXXX
            
            XXXX XXXXXXX XX XXXXXXXXX XXXXXXXX XXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
              XXXXXXXX gettext(u'Address preview:') XXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXX XXXXXX XXX
        XXXX XXXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'Tax Settings') XXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  
                  
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  
                  
                  XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                     gettext(u'Default tax rate (%%)') 
                  XXXXXXXX
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX
                  
                  
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        
        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX
             gettext(u'Cancel') 
          XXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXX
             gettext(u'Save Settings') 
          XXXXXXXXX
        XXXXXX
        
      XXXXXXX
      
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXX XXXXXXX XX XXXXXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXX
  XXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXXX XBBBBBB BBBBBBBBBBBBBBBBBXX
  
  XX XXXX XXXXXXX XX XXXXXXXXX XXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXX X gettext(u'Loading...') XX
    XXXXXXXXXX X gettext(u'Select...') XX
    XXXXXX XXXX
  XXX
  
  XX XXXXXXXXXXXXX XXXX XXXXX XXX X XXXXXXX
  XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXXXXXXXXXX X
    XX XXXXXXXX XXXXX XXX
    XXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
    
    XX X XXXXX XXXXXXX XXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXX
    XX XXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXX X XFFFFFFFFFFXX
    X
    
    XX XXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    X
  X
  
  XX XXXXXXX XX XXXXXXXXX XXXXXXXX
  XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  
  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
    
    XX XXXXXX XX XXXXXXXX XX XXXXXXXXX XX XXXXXXXX X
      XXX XXXXXXX X XXXXXX
      XX XXXXXXX XXXXXXX XX XX X X XXXXXX
      XXXXXXX XX XXXXXX X XXXXXXXX X XX X X XXXXXXXXXX
      XXXXXXX XX XXXXXX X XXXXXXXX
      XX XXXXXXXXXXXX XXXXXXX XX X X X XXXXXXXXXXX
      
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    X XXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    X
  X
  
  XX XXXXXXXXX XXXX XXXXXXX
  XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX X
    XX XXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    X
  XXX
  
  XX XXXXXXX XXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX

XXXXXXX
  XXXXX X
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
  X
  
  XXXXXXXXXXX X
    XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXXX
  X
  
  XXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXXX XXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXX
  X
  
  XXXXXXXXXXXX XX X
    XXXXXXX XX
    XXXXXXXXXX XXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXX XXXXXXXXXXXX
    XXXXXXXX XXXX
  X
  
  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X X X XXXXXX XXXXXXXXX XXXX XXXX XXXXXX
  X
  
  XXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
  X
  
  XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXXXX XXXX XXXX XXXXX
  X
XXXXXXXX
BBBBBBBB

