BBBB BBBB
XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX gettext(u'Otros Servicios (externos)') XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
        XXXX
          XXX XXXXXXXXXXXXXXX gettext(u'Nombre del servicio') XXXXX
          XXX XXXXXXXXXXXXXXX gettext(u'Compañía') XXXXX
          XXX XXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Valor Taller') XXXXX
          XXX XXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Valor Cliente') XXXXX
          XXX XXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Ganancia') XXXXX
          XXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Acciones') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXX XXXXXXXXXX
        
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBB
        XXX XXXXXXXXX
          XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX
          XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX
          XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
          XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFFFFXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
        XXXXX
        BBBBB
        
        BBBBBB
      XXXXXXXX
    XXXXXXXX

    XXXX XXXXXXXXXXX XXXX XXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Agregar otro servicio') XXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX
XXXXXXXXXXXX
  XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXX XXXXXXX

  XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X

  XXXXXXXX XXXXXXXXXXXX
    XXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
    XXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXX XXXXXXXXXXXX
  XXX

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXX X X
        XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX
      XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
  XXX

  XX XXXXXXXXXX XXXXX XXXXXXXXXX XX XXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX
XXXXXXXXX
