BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB X XXXXXX XX XXXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX
XX X XXXXXX XX XXXXXXXX XXXXXXXX XXXX XXXXXXXXX XX
XXXXX X
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXX XXX XXX XXXXXX
    XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
    XXXXXXXXXXXX X X XXXXX
X

XXXX X
    XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXXXXXXX
    XXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXX X XXX X XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXX XX XXXXXXXXX
X

XXXXXXXXXX XXXXXXXXX X
    XXX XXXX X XXXXXXXX XX X
    XXX X XXXXXXXX XX X
X

XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        X XXXX XXXX XXXXXXXXX XXXX XX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XXXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XX XXXXX XXXXXXXXXXXXX
    XXXXXXXXXXX XXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXX
X

XXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXX
    XXXXXXXXXXX XXXXX
X

XX X XXXXX XXXXX XXXXXXXXX X XXXXXX XXXXXXXX XX
XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXX XXXX X XXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXX XXXX XXXXX XXX
        XXXXXXXXX XXX XXXX XXXXX XXXX
        XXXXXXXXX XXXX XX XXXXX XXXX
        XXXXXXX XXXX XXXX XXXXX XXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX XXXXXX
    XXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXX
        X X XXXX XXXXXXXXXXXXXXXXXX
        X X XXXX XXXXXXXXX XXXX XX XXXXX
        XXXXX X X XXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXX XXXXX
X

XXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXX XXXXXXXXX XX XXXXXXXX XXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXX X
XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXXXX X
XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXX X

XXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXX
X

XXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX
    XXXXXXXXXXX XXXX
    XXXXXXXXXXXXXXX XXXX
X

XXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
X

XXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXX XXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXXX XX XXXXXXXX XXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXX XXXX XX XXXXX
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX
    XXXXXXXXXXXX XXXX
X

XXXXXXXXXX X
    XXXXXXXXXXXXXX XXXX
    XXXXXXXX XXXX
X

XX XXXXXXXXXXX XXXXXXXXXX XXXX XX XXXXX XXXXX XX
XXXXXXXXXX XXXXXXXXXXXX X
    XX X XXXXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXX X
X

XXXXXXXXXX XXXXXXXXX X
    XX X
        XXXXXXXXXXXX X X XXX XXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXX
    X
    XXXX X
        XXXXXXXXXXXX X X XXXX XXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXX
    X
X

XXXXXXXXXX XXXXXXXXXX X
    XX X
        XXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXX
    X
    XXX X
        XXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXX
    X
    XXXX X
        XXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXX
    X
X

XXXXXXXXXX XXXXXXXX X
    XX X
        XXXXXXXXXXX X X XXX XXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXX
    X
    XXXX X
        XXXXXXXXXXX X X XXXX XXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXX
    X
X

XX XXXXXXXXXX XXXX XX XXXXX XXXXX XX
XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXX XXXX X XXXXXXXXXXX
        XXXXXXXXXXX XXXXXX
    X

    XXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXXXXXXXX X
        XXXX XXXX
    X

    XXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXXXX XXX XXXX
    X
X

XX X XXXXXXX XXXX XXXXXXX XXXXXXXX XX
XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXX XXXX XXXXX XXX
        XXXXXXXXX XXX XXXX XXXXX XXXX
        XXXXXXXXX XXXX XX XXXXX XXXXXX
    XXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXX XXXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXX
        X X XXXX XXXXXXXXX XXXX XX XXXXX
        X XXXX XXXX XXXXXXX XXXX XXXX XXXXX
        XXXXX X X XXXX XXXXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXX XXXXX
X

XXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXXX XX
    XXXXXXXXXX XXXXXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXX
X

XXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXX XX
    XXXXXX XX
    XXXXXXXX XXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXX XXXX
X

XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX
    XXXXXXXX XXXX
    XXXXXXXXXXXX XXXX
X

XX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXX XX
XXXXXXXXXX XXXXXXXXXXX X
    XX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXX XX
    X
    XXX X
        XXXXXXXX XX
    X
    XXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXX XX
    X
X

XXXXXXXXXX XXXXXXXXXXXXXXX X
    XXX XXXX X
        XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
    X
    XXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
    X
X

XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
    XXX XXXX X
        XXXXXXXX XXXX
        XXXXXXXXXX XXXXXXXXX
    X
    XXX X
        XXXXXXXX XX
        XXXXXXXXXX XXXXXXXXXXX
    X
X

XXXXXXXXXXXXX X
    XXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXXXX
    XXXXXXX XXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
X

XX X XXXXXX XXXXXXX XXXXXXX XX
XXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX
    XXXX XXXXX
    XXXXXXX XXXXXX
    XXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXX XXX XXXXXXXXX XXX XXXX XXXX XXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX
        X XXX XXXX XXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXX
X

XX XXXXXXX XX XXXXX XXXX XXXXXXX XX
XXXXXXXXXXX X
    XXXXXXXXXXXX XXXX XX
    XXXXXXXXX XXXX XX
X

XXXXXXXXXXXX X
    XXXXXXXXXXXX XXXX XX
    XXXXXXXXX XXXX XX
X

XXXXXXXXXXX X
    XXXXXXXXXXXX XXXX XX
    XXXXXXXXX XXXX XX
X

XXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
X

XXXXXXXXXX X
    XXXXXX XXXX
    XXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXX XX XXXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXX X
    XXXXXXX XXXXXXXXX X XXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXX XX
X

XXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXXX
    XXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX
X

XX XXXXXXXXXX XXXX XXXXXXXXX XXXXXXXX XX
XXXXXX XXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX
        XXXXXXX XXXXXX
    X

    XXXXXXXXXXX X
        XXXXXXXXXXXX XXXX XX
        XXXXXXXXX XXXX XX
    X
X

XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX
        XXXXXXX XXXXXX
    X

    XXXXXXXXXXXX
    XXXXXXXXXXXX X
        XXXXXXXXXXXX XXXX XX
        XXXXXXXXX XXXX XX
    X

    XXXXXXXXXXX X
        XXXXXXXXXXXX XXXX XX
        XXXXXXXXX XXXX XX
    X
X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXX

    XXXX X XXXXXXXX XXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXX XXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
        BB BBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXX XXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX
        XXXXXX
        BBBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'Centro de Operaciones') XXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX
                FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
            XXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                FFFFFFFFFFFFFFFFFFFF _("Control total para tu flota estelar") 
            XXXX
        XXXXXX
    XXXXXX

    XXXX X XXXXX XX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXX XX XXXXXXXX XX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX

            XXXX XXXXX XXXXX XXXXXXXXX X XXXXXXXXXXXX XXXXXXX XXXXX XXX
            XX XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                XXXXXX
            XXXX

            XX XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX

            XX XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
            XXXX

            XX XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX

            XX XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
            XXXX

            XX XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX
            XXXX

            XX XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX
            XXXX


                        XX XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXX XX XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXX
            XXXX
        XXXXXX
    XXXXXX

    XXXX X XXXXXXX XX XXXXXXX X XXXXXXXXX XXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX X XXXXXXX XXXXXXXXXX

        XXXX XXXX XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXX

            XXXX XXXX XXXXXX X XXXXXXX XXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXX XXXXXXX X XXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXX XXXXXXX X XXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXX XXXXXXX X XXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXX XXXXXXX X XXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXX XXXXXXX X XXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXX XXXXXXX X XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX
                XXXXXX
            XXXXXX

        XXXXXX
    XXXXXX

XXXXXX

XXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X

    XX XXXXXXXXXXXXX XXXXX XX XXXXXXXX XXXX XXXXXX XXXXXXX
    XXXXX XXXXXXXXXXXXX X X
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXX X
            XXXXXXX X
                XXXXXXXX XXXXX
            X
        XX
        XXXXXXX X
            XX X
                XXXXXXXX XXXXX
            XX
            XX X
                XXXXXXXX XXXXX
            X
        XX
        XXXXXXXXX X
            XXXXXX X
                XXXXXXX XX
                XXXXXXXXXXXX X
            X
        X
    XX

    XX X XXXXXXX XXXXXXXXX X XXXXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXX XX XXXXXXXXXXXXX X
        XXX XXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXX
            XXXXX X
                XXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXX XXXXXX XXXXXX XXXXXXX
                XXXXXXXXX XX
                    XXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXX
                    XXXXXXXXXXXX XXXXXXXXXX
                    XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXX
                    XXXXX XXXXX
                    XXXXXXXX XXXX
                    XXXXXXXXXXXX XX
                    XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXXXXXXXXXXXXX XXXXXXXXX
                XX
            XX
            XXXXXXXX X
                XXXXXXXXXXXXXXXXX
                XXXXXXX X
                    XX X
                        XXXXXXXX XXXXX
                        XXXXXX X
                            XXXXXX XXXXXXXXXX
                            XXXXX X XXXXX XX X
                        XX
                        XXXXX X XXXXXXXX XXXXX X
                    XX
                    XX X
                        XXXXXXXX XXXXX
                        XXXXXX X
                            XXXXXX XXXXXXXXXX
                            XXXXX X XXXXX XX X
                        XX
                        XXXXX X
                            XXXXXX XXXXXXXX XXXX XXXX XXXXXX
                            XXXXXXXXXX X
                        X
                    X
                X
            X
        XXX
    X

    XX X XXXXXXX XXXXXXXXX X XXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXX XX XXXXXXXXXXXXX X
        XXX XXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXXXXX
            XXXXX X
                XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX
                XXXXXXXXX XX
                    XXXXX XXXX XXX XXX XXXX
                    XXXXXXXXXXXXXXXX X
                        XXXXXXXXXX
                        XXXXXXXXXX
                        XXXXXXXXXX
                        XXXXXXXXX
                    XX
                    XXXXXXXXXXXX XX
                    XXXXXXXXXXXX XXXXXXXXX
                XX
            XX
            XXXXXXXX X
                XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXX
                XXXXXXXX X
                    XXXXXXX X
                        XXXXXXXX XXXXX
                        XXXXXXXXX XXXXXXXXX
                        XXXXXXX X
                            XXXXXX XXXXXXXXXX
                            XXXXX X XXXXX XX XX
                            XXXXXXXXX XXX
                            XXXXXXXX XX
                        X
                    X
                X
            X
        XXX
    X

    XX XXX XXXXXXX XXXXXXXX X XXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXX XX XXXXXXXXXXXXX X
        XXX XXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXX
            XXXXX X
                XXXXXXX XXXXXXXX XXXXXXXX XXXXXX XXXXXXXX
                XXXXXXXXX XX
                    XXXXX XXXX XXX XXX XXXX
                    XXXXXXXXXXXXXXXX X
                        XXXXXXXX XXXX XXXX XXXXXX
                        XXXXXXXXXX XXX XXXX XXXXXX
                        XXXXXXXXXX XXXX XX XXXXXX
                        XXXXXXXX XXXX XXXX XXXXX
                    XX
                    XXXXXXXXXXXX X
                        XXXXXXXXXX
                        XXXXXXXXXX
                        XXXXXXXXXX
                        XXXXXXXXX
                    XX
                    XXXXXXXXXXXX X
                XX
            XX
            XXXXXXXX X
                XXXXXXXXXXXXXXXXX
                XXXXXXX X
                    XX X
                        XXXXXXXX XXXXX
                        XXXXXX X
                            XXXXXX XXXXXXXXXX
                            XXXXX X XXXXX X X
                        XX
                        XXXXX X XXXXXXXX XXXXX X
                    XX
                    XX X
                        XXXXXXXX XXXXX
                        XXXXXX X
                            XXXXXX XXXXXXXXXX
                            XXXXX X XXXXX X XX
                            XXXXXXXXX XXXXXXXXXXXXXXX X
                                XXXXXX XXXXX X XXXX
                            X
                        XX
                        XXXXX X
                            XXXXXX XXXXXXXX XXXX XXXX XXXXXX
                            XXXXXXXXXX X
                        XX
                        XXXX XXX
                    X
                X
            X
        XXX
    X

    XX XXXXXXXXX XX XXXXXXXXXX XX XXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX X
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                XX XXXXXXX X XX X
                    XXX XXXXXXX X XX
                    XXXXX XXXXXXXXX X XXXXXX X XXX
                    XXXXX XXXXX X XXXXXXXXXXXXXX XX X
                        XXXXXXX XX XXXXXXXXXX
                        XX XXXXXXXX XX XXXXXXX X
                            XXXXXXX X XXXXXXX
                            XXXXXXXXXXXXXXXXXXXXX
                        X
                        XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
                    XX XXXX
                X
            X
        XXX
    X

    XX XXXXXX XX XXXXXXXXXXXXX XX XXXXXX XXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX X XXX X XXXXXX
        XXX
    X

    XX XXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX

    XX XXXXXX XXXXX XX XXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXX X XXXXXXXXX XXXXXXXXXXXXXXX
        XXX
    XXX
XXX
XXXXXXXXX
BBBBBBBB
