
BBBB BBBB BBBBBB

BBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXX
  XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
       gettext(u'Account activated!') 
    XXXXX

    XX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX
       gettext(u'Your account has been activated successfully.<br>Welcome to <span class="font-bold text-fuchsia-400">eGarage</span>!') SSSS SSSSSSS SSS SSSS SSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSS SS SSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
    XXXX

    XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX

    BBBB BBBBBBBBBBBB
    XX XXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
       gettext(u'Sign in') 
    XXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
      XXXXXXX  X 
    XXXX
  XXXXXX
XXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXX X X XXXX XXXXXXXX X X XXX XXXXXXXX X X XXX XXXXX
    XXXXXXXXXXXXXXX XXXX
  X
XXXXXXXX
