BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXX XXXXXXX XXX
XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXX XXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXX XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXX XXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXX
  XXXX XXXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
               gettext(u'Vehicle Details') 
            XXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX gettext(u'Complete vehicle information') XXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Edit') XXXXXXX
          XXXX
          XX XXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Back') XXXXXXX
          XXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX

      XXXX XXXX XXXXXXX XXXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

        XXXX XXXXXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXX
              XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Vehicle Overview') XXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Brand') XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                XXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Model') XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                XXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Year') XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'License Plate') XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBXXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'VIN') XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBXXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Color') XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXX XXXXXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXXXXX
              XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Technical Specifications') XXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Engine') XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBBB
                    
                  BBBB
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                  BBBBB
                XXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Transmission') XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBB
                    
                  BBBB
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                  BBBBB
                XXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Registration Date') XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXFFFFFFF FF FFXXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Last Updated') XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXFFFFFFF FF FFXXXXXX
              XXXXXX

              BB BBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Mileage') XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFFF  gettext(u'miles') XXXXXX
              XXXXXX
              BBBBB
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXX XXX
        BB BBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXX
              XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Observations') XXXXX
            XXXXXX

            XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        BBBBB
      XXXXXX

      XXXX XXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXX

        XXXX XXXXXX XXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXX
              XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Client Information') XXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Name') XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                  FFFFFFFFFFF FFFFFFF
                XXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Email') XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                XXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Phone') XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                XXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Company') XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXX
              XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Quick Actions') XXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX
                XXXXXX gettext(u'Edit Vehicle') XXXXXXX
              XXXX

              XX XXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
                XXXXXX gettext(u'View All Vehicles') XXXXXXX
              XXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
