BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXX

    XXXX XXXXXX XX XXXXXX XX XXXXXXXXXXX XXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXX XXX XXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X X XXXX X X X X XXX XXXXXXXXX X X XXXX XXXXX X X XXX XXXXX X X XXXXXXXX XXXXXXXXXXXXXXXXXXX XX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXX
                    
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX
    BBBBB

    XXXX XXXXXXXXXXX XX XX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXX XXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXX XXXXXXXXXXX XXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFF FFFFXXXXX
                    XXXXXX
                XXXXX
            XXXXXX

            XXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXX XXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
                                FFFFF
                            XXXXXXX
                        XXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFFXXXXX
                    XXXXXX
                XXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXX XX XXX XX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXX XXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXXX XX XXXXXXXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXX XX XXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXX XXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFF FFFFFFFFFFFXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            BB BBBBBBBBBBB
                                XXXX XXXXXX XXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
                            BBBB
                                XXX XXXX
                            BBBBB
                        XXXXX
                    XXXXXX
                XXXXX
            XXXXXX

            XXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            BB BBBBBBBBBBBB
                                XXXX XXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
                            BBBB
                                XXX XXXX
                            BBBBB
                        XXXXX
                    XXXXXX
                XXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXX XX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXX
            XXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XX
  XXXX XXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXX XX
  XXXXXX
XX XXXXX XXBBBBBBBBBBBXXXXXXXXXXXXX
            XXXXXX

            XXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXBBBBBBBBBBBXXXXXXXXXXXXX
            XXXXXX

            XXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXX XX X XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
XXXXXXXXXBBBBBBBBBBBXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB
