#!/bin/bash
# Script para copiar el archivo completo selector_pais.html al servidor
# Usa base64 para evitar problemas de codificación

echo "📋 Para actualizar el archivo en el servidor, ejecuta este comando:"
echo ""
echo "1. Desde tu PC local, ejecuta este comando para generar el archivo codificado:"
echo ""
echo "cd /ruta/a/tu/proyecto/e_garage && \\"
echo "base64 -w 0 templates/public/selector_pais.html > selector_pais_base64.txt"
echo ""
echo "2. Luego copia el contenido de selector_pais_base64.txt y pégalo en el servidor:"
echo ""
echo "cd /home/atlantareciclajes/apps/egarage/current && \\"
echo "cat > selector_pais_base64.txt << 'ENDOFFILE'"
echo "[PEGA AQUÍ EL CONTENIDO DE selector_pais_base64.txt]"
echo "ENDOFFILE"
echo ""
echo "3. Finalmente, decodifica y guarda el archivo:"
echo ""
echo "base64 -d selector_pais_base64.txt > templates/public/selector_pais.html && \\"
echo "rm selector_pais_base64.txt && \\"
echo "touch /var/www/www_egarage_cl_wsgi.py && \\"
echo "echo '✅ Archivo actualizado y servidor reiniciado'"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "O usa este método más simple con Python:"
echo ""
echo "cd /home/atlantareciclajes/apps/egarage/current && \\"
echo "python3 << 'PYEOF'"
echo "import sys"
echo "import base64"
echo ""
echo "# El contenido del archivo se copiará aquí"
echo "# O mejor aún, usa scp o rsync desde tu PC local"
echo "PYEOF"

