from django.db import migrations


CREATE_PAGO_PENDIENTE_SQL = """
CREATE TABLE "taller_pagopendiente" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "plan" varchar(20) NOT NULL,
    "monto" numeric(12, 2) NOT NULL,
    "comprobante" varchar(100) NOT NULL,
    "estado" varchar(20) NOT NULL,
    "fecha_subida" timestamp with time zone NOT NULL,
    "fecha_verificacion" timestamp with time zone NULL,
    "notas" text NOT NULL,
    "referencia" varchar(100) NOT NULL,
    "metodo_pago" varchar(50) NOT NULL,
    "empresa_id" bigint NOT NULL,
    "verificado_por_id" integer NULL
);

ALTER TABLE "taller_pagopendiente"
ADD CONSTRAINT "taller_pagopendiente_empresa_id_dec5e413_fk_taller_empresa_id"
FOREIGN KEY ("empresa_id")
REFERENCES "taller_empresa" ("id")
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "taller_pagopendiente"
ADD CONSTRAINT "taller_pagopendiente_verificado_por_id_eb544bba_fk_auth_user_id"
FOREIGN KEY ("verificado_por_id")
REFERENCES "auth_user" ("id")
DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "taller_pagopendiente_empresa_id_dec5e413"
ON "taller_pagopendiente" ("empresa_id");

CREATE INDEX "taller_pagopendiente_verificado_por_id_eb544bba"
ON "taller_pagopendiente" ("verificado_por_id");
"""


def restore_pagopendiente_if_missing(apps, schema_editor):
    """
    Compatibilidad entre dos historias de migraciones:

    - Bases legacy de producción:
      0101_pago_delete_pagopendiente eliminó físicamente la tabla.
      En ellas debemos restaurarla.

    - Bases nuevas:
      0073 ya crea físicamente taller_pagopendiente.
      En ellas esta migración debe ser un no-op.
    """
    table_name = "taller_pagopendiente"

    existing_tables = schema_editor.connection.introspection.table_names()

    if table_name in existing_tables:
        return

    schema_editor.execute(CREATE_PAGO_PENDIENTE_SQL)


def reverse_restore_pagopendiente(apps, schema_editor):
    """
    Reverse conservador: elimina la tabla solo si existe.
    """
    schema_editor.execute(
        'DROP TABLE IF EXISTS "taller_pagopendiente";'
    )


class Migration(migrations.Migration):

    dependencies = [
        ("taller", "0168_publicpageview"),
    ]

    operations = [
        migrations.RunPython(
            restore_pagopendiente_if_missing,
            reverse_restore_pagopendiente,
        ),
    ]
