BBBB BBBBBBBBBBBBB
XXXX XXXXXX XXXXXXX XXX XXXXXXXXXX XX XXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFF
      BB BBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFF
      BB BBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFF
      BB BBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFFF
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBB
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X XXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFF
      BB BBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFF
      BB BBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBB
    XXXXXX
  XXXXXX
XXXXXX
