BBBB BBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XX X XXX X XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX
XXXXXXX
XX XXXX XXXXXXXXX XXXX XXXXXXX XXX XXXX XX
XXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX XXXXXXX
X

XX XXXXX XXX XXXXXXXXX XXXXXX XX
XXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXX
    XXXX XX XXXXX XX XXXXXX XXXXXX XXXXXXX XXXXXX
    XXXXXXXX XXX
    XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXX XXXX XXXXX XXX XXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
X

XX XXXXXXXXXX XXXXXXXXX XXXXXX XX
XXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXX
    XXXX XX XXXXX XX XXXXXX XXXXX XXXXXXX XXXXX
    XXXXXXXX XXX
    XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXX XX XXXX XXXXX XXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXX XX XXXX XXXXX XXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXX XX XXXX XXXXX XXXXXXXXX XXX XXXX XXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXX XX XXXXX XXXXX XXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXX XX XXXXX XXXXX XXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXX XXXXXX
    XXXXXXXXXX XXXXXXX XX XXXXXX XXXXXXXXX
X

XXXXXXXXXX XXXXXXX X
    XX X XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXX X XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXXX X XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
X

XXXXXXXXXX XXXXXXX X
    XX X XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX X
    XXX X XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXX X
    XXXX X XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XX X
X

XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXX XXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        XXXXX X XXX X XXXXXXX XXXX XXXX XXXXX
    XXXXXXXX XXXX XXXXXXX
    XXXXXX XXXXX
    XXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
    XXXXXXXXXX XXXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XXXXX
    XXXXX XXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXXX XXX XXXXXX XXXXXXXXX
    XXXXXXXX XXX
X

XXXXXXXXXX XXXXXX X
    XX X XXXXXXXXXX XXXXXXXXXXXXX X
    XXXX X XXXXXXXXXX XXXXXXXXXXXXXXX X
X

XXXXXXXXXX XXXXXXXX X
    XX X
        XXXXXXXXXXX
            X X XXXX XXXXXXX XXXX XXXX XXXXX
            X X XXXX XXXXXXX XXXX XXXX XXXXX
            XXXXX X XXX X XXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXXXX XXXXXXXX
    X
    XXXX X
        XXXXXXXXXXX
            X X XXXX XXXXXXX XXXX XXXX XXXXX
            X X XXXX XXXXXXX XXXX XXXX XXXXX
            XXXXX X XXX X XXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXXXX XXXXXXXX
    X
X

XXXXX X
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXX XXXXXXXXXXXXX X XXXX XXXXXXX XXXX XXXX XXXXXX
X

XXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXXX XXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXXX XXXXXXXXXXX
X

XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXX X
    XXXXXXXX XXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        XXXXX X X XXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXX XXXXXX XXXX XXXXXX XXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
    XXXXXX XXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        X XXX XXXX XXXXXXX XXXX XXXX XXXXX
        XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
    XXXXXXXXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        X XXX XXXX XXXXXXX XXXX XXXX XXXXX
        XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXX XXXXXXXX
X

XXXXXXXXXX XXXXXXXXXXX X
    XX X
        XXXXXXXXXXX
            X X XXXX XXXXXXX XXXX XXXX XXXXX
            X XXX XXXX XXXXXXX XXXX XXXX XXXXX
            XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    X
    XXXX X
        XXXXXXXXXXX
            X X XXXX XXXXXXX XXXX XXXX XXXXX
            X XXX XXXX XXXXXXX XXXX XXXX XXXXX
            XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    X
X

XXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX X X XXX XXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXXX X X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXXX XXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXX X X XXX XXXXXXXXX XXXX XXXX XXXXX
X

XX XXXXXXXXXX XX
XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXXXXX X
        XXXXXXX XXXXX
        XXXXXXXX XXXX XXXXXXX
    X

    XXXXXXXXXXXX X
        XXXXXXXXXX XXXXX
    X
X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                 gettext(u'Sign In')
            XXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Welcome back to E-Garage USA')
            XXXX
        XXXXXX

        BB BBBBBBBB
            BBB BBBBBBB BB BBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXX

                XXXXXX
            BBBBBB
        BBBBB

        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            BBBBBBBBBB

            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Username') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBB
                    BBB BBBBB BB BBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBBB
                BBBBB
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Password') XXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBB
                    BBB BBBBB BB BBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBBB
                BBBBB
            XXXXXX

            BB BBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB

                    BBBBBB
                XXXXXX
            BBBBB

            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                X  gettext(u'Sign In')
            XXXXXXXXX
        XXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u"Don't have an account?")
            XX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'Sign Up') XXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXX
XXXXXXX
