BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XX X XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX
XXXXXXX
XX XXXX XXXXXXXXX XXXX XXXXXXX XXX XXXX XX
XXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX XXX XXXXXXXXXXX
X

XX XXXXX XXX XXXXXXXXX XXXXXX XX
XXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXX
    XXXX XX XXXXX XX XXXXXX XXXXXX XXXXXXX XXXXXX
    XXXXXXXX XXX
    XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXX XXXX XXXXX XXX XXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
X

XX XXXXXXXXXX XXXXXXXXX XXXXXX XX
XXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXX
    XXXX XX XXXXX XX XXXXXX XXXXX XXXXXXX XXXXX
    XXXXXXXX XXX
    XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXX XX XXXX XXXXX XXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXX XX XXXX XXXXX XXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXX XX XXXX XXXXX XXXXXXXXX XXX XXXX XXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXX XX XXXXX XXXXX XXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXX XX XXXXX XXXXX XXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXX XXXXXX
    XXXXXXXXXX XXXXXXX XX XXXXXX XXXXXXXXX
X

XXXXXXXXXX XXXXXXX X
    XX X XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXX X XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXXX X XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
X

XXXXXXXXXX XXXXXXX X
    XX X XXXXXXXXXX XXXXXXXXXXXXXXXX X
    XXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXX X XXXXXXXXXX XXXXXXXXXXXXXXXX X
X

XXXXXXXXXX XXXXXXXX X
    XX X
        XXXXXXXXXXX
            X X XXXX XXXXXXX XXXX XXXX XXXXX
            X X XXXX XXXXXXX XXXX XXXX XXXXX
            X X XXXX XXXXXXX XXXX XXXX XXXXX
    X
    XXXX X
        XXXXXXXXXXX
            X X XXXX XXXXXXX XXXX XXXX XXXXX
            X X XXXX XXXXXXX XXXX XXXX XXXXX
            X X XXXX XXXXXXX XXXX XXXX XXXXX
    X
X

XXXXXXXXXX XXXXXXXXXXX X
    XX X
        XXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    X
    XXXX X
        XXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    X
X

XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXX XXXXXX
    XXXXXX XXXXX
    XXXXXXX X XXXXX
    XXXXXXXXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
X

XXXXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXX XXXXXXXXXXXXX X XXXX XXXXXXX XXXX XXXX XXXXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXX
X

XXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXX XXXXXX
    XXXXXXXXXXXX X X XXX XXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
    XXXXXXXXXXX
        X X XXXX XXXXXXX XXXX XXXX XXXXX
        XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXX
X

XXXXXXXXXXXX X X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXX X X XXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
X

XXXXXXXXXXXX XXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXX
    XXXXXXXXXXXX X X XXX XXXXXXXXX XXXX XXXX XXXXX
X

XXXXXXXX X
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXX
X

XXXXXXXX X X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
X

XXXXXXXX XXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX X X XXX XXXXXXX XXXX XXXX XXXXX
X

XX XXXXXXXXXX XX
XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXXXXXXXXXX X
        XXXXXXX XXXXX
        XXXXXXXX XXXX XXXXX
    X

    XXXXXXXXXXXX X
        XXXXXXXXXX XXXXX
    X
X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Access your account to manage your workshop with cutting-edge technology') XXXX
        XXXXXX

        BB BBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB

                BBBBBB
            XXXXXX
        BBBBB

        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
            BBBBBBBBBB

            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Username or Email') XXXXXXXX
                BB BBBBBBBBBB
                    FFFFFFFFFFFFFFFFFFFFFFFFFFF
                BBBB
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Username or email') X XXXXXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
                    XXXXXX
                BBBBB
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Password') XXXXXXXX
                BB BBBBBBBBBBBBB
                    FFFFFFFFFFFFFFFFFFFFFFFFFFF
                BBBB
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Password') X XXXXXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXXXX
                BBBBB
            XXXXXX

            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                X  gettext(u'SIGN IN')
            XXXXXXXXX
        XXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u"Don't have an account?")
            XX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Sign Up Here') XXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXX
            XXX
                XXXXXXXXXXXXXXX XXXXXXXXXXXX  gettext(u'developed by')  XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXX
XXXXXXX
