BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBXXXXXXX X XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXXX
  XXXX XXXXXXXX XXXXXX X XXX XXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX
    XXXX XXXXXXXXXXX XXXXXXX
      XX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXX XXXXXXXXXXXXXXXXBBBBBXXXXXXXX
      XX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXX XXXXXXXXXXXXXXXBBBBBXXXXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX
    XXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Client Management') XXXXX
      XXXXXX
      XX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
         gettext(u'Smart list with dynamic search, pagination and quick actions.') SSSSS SSSS SSSS SSSSSSS SSSSSSS SSSSSSSSSS SSS SSSSS SSSSSSSS
      XXXX

      XXXX XXXXXXXXXX XXXXXXX XXX
      XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Operations Center') XXXXXXX
        XXXX

        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Vehicles') XXXXXXX
        XXXX

        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Clients') XXXXXXX
        XXXX

        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Documents') XXXXXXX
        XXXX

        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Reports') XXXXXXX
        XXXX

        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Settings') XXXXXXX
        XXXX

        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Parts') XXXXXXX
        XXXX

        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Services') XXXXXXX
        XXXX

        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Other Services') XXXXXXX
        XXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XX XXXXX XXXX XXXXX XXXXXX XX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XX
        XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX
            XXX XXXXXXXXXXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          BBB BBBBBBB BB BBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX
              XXX XXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                  XXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXX
              XXX XXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFXXXXX
              XXX XXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFXXXXX
              XXX XXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBXBBBBBXXXXX
              XXX XXXXXXXXXXX XXXXXX
                XXXX XXXXXX XX X XXXXX X XXXXXX XX XXXXX XXX XXX XXXX XXX
                XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXX XX XXXX X XXXX XXX
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX
                     XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXXXX
                    XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX X X XXX XXXXXXX XXXX XXXX XXXXXXXXXXXXX
                  XXXX

                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX
                     XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXX X X XXXX XXXXXXXXX XXXX XXX XXXXXXX
                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX X X XXX XXXXXXXXX XXXX XXX XXXXXXXXXXXXX
                  XXXX

                  XXXX XXXX XX XXXXXX XXXXXXXXX XX X XXXXXXXXX XXX
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBX
                     XXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXX XXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXX X X XXXX XXXXXXXXX XXX XXX XXXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX X X XXX XXXXXXXXX XXX XXX XXXXXXXXXXXXX
                  XXXX
                XXXXXX
              XXXXX
            XXXXX
          BBBBB
            XXXX
              XXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
            XXXXX
          BBBBBB
        XXXXXXXX
      XXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXX XXX
    BB BBBBBBBBBBBB
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXX  X  XX  XXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
          XX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
        BBBB
          XXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        BBBBB

        XXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
           X
        XXXXXXX

        BB BBBBBBBBBBBBBBBBB
          XX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
        BBBB
          XXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBB
      XXXXXX
    XXXXXX
    BBBBB
  XXXXXX
XXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXX XXXXXXXXXXXXXX
    XXX XXXXXXXXXXXX X XXX

    XX XXXXX XXXXXXXX XXX XXXX XXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX XXXXXX XX X
        XXXXXXXXXXXXXXXXXXX X X
            XXXXXXXX XXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
            XXXXXXXX XXXX
        XX
    XXX

    XX XXXXXXXXX XXXXXXXXX XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXX X XX

        XX XXXXXXXXXXXXXXXXXX XXX XX X
            XX XXXX XXX XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX X XXXXX
                XXXXXXXXXXXXXXX
            XXX
        X XXXX X
            XX XXXXXX XXXX XXXXX XX XXXXXX XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXX XXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XX XXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX X XXXXX
                    XXXXXXXXXXXXXXX
                X XXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX X XXXXXX
                X
            XXX
        X

        XX XXXXXX XXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX X
        XX XXXXXX XXXXXXXX XXXXXX XXXXXXX
        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXX
        X

        XX XXXXXXXXXXXXXXXXXX X XX X
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX X XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX X XXXXX XXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXX

            XX XXXXXXXX XXX XX X
                XXXXXXXXXXXXXXXXXXX X X
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                        XX XXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX
                XX
            X XXXX X
                XXXXXXXXXXXXXXXXXXX X X
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                        XXXXXXX XXXXXXXXXX XX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX
                XX
            X

            XX XXXXXX XXXXXX XXXXXXX XXXXX XXX XXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    X

    XXXXXXXX XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXX XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XX XXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXXXXX X XX X
            XXXXXXXXXXXXXX
            XXXXXXXXXXXXX X XXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
            XX XXXXX XX XXXXXX XXXXXXXX XXX XXXXXXXXX XXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX
        X
    XXX

    XX XXXXXX XXXXX XXX X XXXXXXX XXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XX XXXXXX XXX XXXXXXXX X
            XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXX X
                XX XXXXXXXX XX XXXXXXXXXXX XXXXXX XXX XXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        X
    XXX

    XX XXXXXX XXXXXX XXX X XXXXX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XX XXXXXX XXX XXXXXXXXX X
            XXXXXXXXXXXXXXXXX X XXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
        X
    XXX

    XX XXXXX XXXXXX XXXX XXXXXXXX XXXXXXX XX XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXX X
            XXXXXXXXXXXXXXX
        X
    XXX
XXX
XXXXXXXXX

XXXXXXX
XX XXXXXXXXX XXXXXXXXX XXXXXX XX
XXXXXXXXXXXXX X
    XXXXXXXX XXXX XXXXXXXXXXX
X

XX XXXXXX XXXXXXXXXXX XXX XXXXXXXXX XX
XXXXX XX X
    XXXXXXXXXXX XXX XXXX XXXXXXXXXXXX
X

XX XXXXXX XXXXXX XXXXXXX XXXXXXXXXX XX
XXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX XXXX XXXXXXXXX
X

XXXXXXXXXX XXXXXXX X
    XXXX X
        XXXXXXXX XX
        XXXXXXXXXX XXXXXXXXXXXXXXXXXX
    X
    XX X
        XXXXXXXX XX
        XXXXXXXXXX XXXXXXXXXXXXXX
    X
X

XX XXXXXXXX XXXXXX XXXXX XXXXX XX
XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX X X X XXX XXXXXXX XXXX XXXX XXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
X

XX XXXXXXX XXXXXXX XXXXXXXXX XX
XXXXXXXXXXX X
    XXXXXXXXXX XXXX XX XXXXXX XXXXXXXXX
X

XXXXXXXXXX XXXX X
    XXXX X XXXXXXXXXX XXXXXXXXXXXXX X
    XX X XXXXXXXXXX XXXXXXXXXXXXXXX X
X

XX XXXXX XXX XXXXX XXXXXXX XXX XXXXXXX XXXX XX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXX XXX XXXXXXX XXXX XXXX XXXXX
X
XXXXXXXX

BBBBBBBB
