BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX
  XX XXXXXXXX XXX XXX XXXXXX XXXXXXXXX XX XXXXX XXXX XXXXXXX XX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    XXXXXX XXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXX XXXX XXXXXXXXXXX
    XXXXXXXX XXXX XXXX XXXXXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXX XXXXXXXXXXX
  X

  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX X X X XXX XXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    XXXXXXXX XXXX XXXXXXXXXXX
  X

  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
  X

  XX XXXXXXX XXXX XX XXXX XXXXXXXXX XX
  XXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXX XXXXXXXX X
    XX X
      XXXXXXXXXXX X X XXXX XXXXXXXX XXXX XXXX XXXXX
    X
    XXXX X
      XXXXXXXXXXX X X XXXX XXXXXXXX XXXX XXXX XXXXX
    X
  X

  XX XXXXXXX XXXX XX XXXXXX XX
  XXXXXXXXXXXX X
    XXXXXXXXXXXX X X XXXX XXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
  X

  XXXXXXXXXX XXXXXXXXX X
    XX X
      XXXXXXXXXXXX X X XXXX XXXXXXXX XXXX XXXX XXXXX
    X
    XXXX X
      XXXXXXXXXXXX X X XXXX XXXXXXXX XXXX XXXX XXXXX
    X
  X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX
        XXXX XXXX XXX XXXXXXX XX XXXXXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBX
                 XXXXXXXXXXXXX XXXXX
                 XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                X
            XXXXXX
        XXXXXX
      XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX gettext(u'Accede a tu cuenta para gestionar tu taller con tecnología de punta.') XXXX
  XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXX XXXXXXX
      BBBBBBBBBB

      XXXXX
        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Usuario') XXXXXXXX
        FFFFFFFFFFFFFFFFF FFFF FFFF FFFFFFFFFF FFFFFFFFFFFF FFFFFFFFFFFFF FFFFFF FFFFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFF FFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF

      XXXXXX
      XXXXX
        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Contraseña') XXXXXXXX
        FFFFFFFFFFFFFFFFF FFFF FFFF FFFFFFFFFF FFFFFFFFFFFF FFFFFFFFFFFFF FFFFFF FFFFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFF FFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF

      XXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXX gettext(u'Ingresar') XXXXXXXXX
    XXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
       gettext(u'¿No tienes cuenta?')  XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Regístrate aquí') XXXXX
    XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX XXXXXXXX XX XX XXXXXXXX
    XXXXXX

    XXXX XXXXXXXX XX XXXXXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX  gettext(u'desarrollado por')  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
