BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBBB
BBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXX XXXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXXXX

  XXXX XXXXXXXX XXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXX XXXX XXXXX
    XXXX XXXXXXXXXX XXXX XXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
          XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                  XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                     gettext(u'External Services')
                  XXXXX
                  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                    XX XX
                  XXXXXXX
                XXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Advanced external services management system') XXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Operations Center') XXXXXXX
              XXXX

              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Vehicles') XXXXXXX
              XXXX

              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Clients') XXXXXXX
              XXXX

              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Documents') XXXXXXX
              XXXX

              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Reports') XXXXXXX
              XXXX

              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Settings') XXXXXXX
              XXXX

              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Parts') XXXXXXX
              XXXX

              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Services') XXXXXXX
              XXXX

              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'External Services') XXXXXXX
              XXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXX XXXXX XXX
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Total External Services') XXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Categories') XXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Subcategories') XXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'External Companies') XXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXX XXXXXXX XXX
      XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
          XXXXXX gettext(u'Add External Service') XXXXXXX
        XXXX

        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
          XXXXXX gettext(u'Internal Services') XXXXXXX
        XXXX
      XXXXXX

      XXXX XXXXXXXX XXXXXXXX XXXX XXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'Recent External Services') XXXXX

          BB BBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXXX
                  XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Service Name') XXXXX
                    XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'External Company') XXXXX
                    XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Category') XXXXX
                    XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Cost') XXXXX
                    XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Price') XXXXX
                    XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Actions') XXXXX
                  XXXXX
                XXXXXXXX
                XXXXXXX
                  BBB BBBBBBBB BB BBBBBBBBBBBBBBB
                  XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                      BB BBBBBBBBBBBBBBBBBB

                      BBBB
                        X
                      BBBBB
                    XXXXX
                    XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                      BB BBBBBBBBBBBBBBBBBBBBB BB BBBBB
                        XFFFFFFFFFFFFF
                      BBBB
                        XFFFFFFFFFFFFF
                      BBBBB
                    XXXXX
                    XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                      BB BBBBBBBBBBBBBBBBBBBBB BB BBBBB
                        XFFFFFFFFFFFFF
                      BBBB
                        XFFFFFFFFFFFFF
                      BBBBB
                    XXXXX
                    XXX XXXXXXXXXXX XXXXXX
                      XXXX XXXXXXXXXXX XXXXXXX
                        XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                          XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                          XXXXX XXXXXXXXXXXXXXXX gettext(u'View') XXXXXXX
                        XXXX
                        XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                          XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                          XXXXX XXXXXXXXXXXXXXXX gettext(u'Edit') XXXXXXX
                        XXXX
                      XXXXXX
                    XXXXX
                  XXXXX
                  BBBBBB
                XXXXXXXX
              XXXXXXXX
            XXXXXX
          BBBB
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'No external services yet') XXXXX
              XX XXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Start by adding your first external service') XXXX
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                XXXXXX gettext(u'Add External Service') XXXXXXX
              XXXX
            XXXXXX
          BBBBB
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXX XXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
  XX XXXXXXXXXX XXXXXXXXX XXXXXX
  XX XXXXXXX XXXXXXXXXXX XXX XXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXX X XXXXXXX XXXXX XX
      XXXXXXXXXXX X XXXXXX X XXXXXX XXXXXXXXXXXXX X XX
      XXXXXXXXXX X
        XXXXXXX X XXXXXX XX XX
        XXXXXX X XXXXXX XXXXXXXXX XX
        XXXXX X XXXXXX X XX
        XXXXX X XXXXXXX XXXXX XXXXXX XXX XX
        XXXXXX X XXXXXXX XXXXX XXXXXX XXXXXXXXXX XXXXXXXX XXX X
      X
    XXX
  X
XXX
XXXXXXXXX
BBBBBBBB BBBBBBB
