BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBBBXXXXXXXXXXXXX XX XXXX XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXX XXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX

                    XXXX XXXXXXXX XXXXXX XXX
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXX
                        XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXX
                                XXXXXXXXXXXXXXXXX
                                XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX
                                BBBBBBBBBBBBBBB BBBBBBB
                            XXXXXX
                        XXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXX XX XXXXXX XXX
                    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        BBBBBBBBBB

                        XXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                BBB BBBBBB BBBBBBB BB BBBBBBBBBBBBBBBB
                                XXXXXXX XXXXXXXX BB BBBBB BB BBBBBBBBBBBBBBBBXXXXXXXXBBBBBX

                                XXXXXXXXX
                                BBBBBB
                            XXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXX XXXXXXXX XXXX XX XXXXXXXX XXX XXXXXX X XXXXX XX XXXXXXXXX XXXXXXX X XXXXXXXXXXX
                            XXXXXXXX
                        XXXXXX

                        XXXX XXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                            XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX
                            XXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XX XXXXXXXXX
                            XXXX
                        XXXXXX
                    XXXXXXX

                    XXXX XXXXXXXXXXX XXXXXXXXX XXX
                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXX XX XXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXX XX XXXXXXXX XXXXXXXXX XX XXXX XXXXX XX XX XXXXXXXXXXX
                            XXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXX XX XXXXXXXX XXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX X XXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                            XXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXX XXXXXXXXXXXX XXXX XXX XXXXX XXXXX XX XXXX XXXXXXXXXXXX
                        XXXXX
                    XXXXXX

                    XXXX XXX XXXXX XXXX XXX
                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XX XXXXXXX XXXXXXXXXXX
                        XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXX XXXXXXXXX
                                    XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXX
                                    XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXX XXXX XXXXXXXX
                                    XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXX XXXXXXXX XXX XXXXXXXXXX XXXXXXX
                                XXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                                    XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
                                    XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXX
                                XXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
XXXXX XXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXX XXX XXX X
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXX
    X

    XXX X
        XXXXX XXXXXXXX X XXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXX X XXXXX XXXXXXXXXXXXXXXX

        XX XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXX X X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX
            XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        X
    X XXXXX XXXXXXX X
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    X
X

XX XXXXXXXXXXXX XX XXXX XXXX XX XXXXXXXXX XXXXXXXX XX XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXX
XXX
XXXXXXXXX
BBBBBBBB
