BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXX XXXXXXXXXX
XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX
XXXXXXXX
XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
  XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXX
  BBBBBBBBBBBBB
XXXXXX
XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      BBBBBBBBBB

      XXXXX
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFFFF FFF FFFFFFF FFFFFFFFFFFFFFFF FFFFFFFFFF FFFFFFF
      XXXXXX
XXXXX
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFFFF FFF FFFFFFF FFFFFFFFFFFFFFFF FFFFFFFFFF FFFFFFF
      XXXXXX
XXXX XXXXXXXXXXX XXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
          X XXXXXXX XXXXXXXX
        XXXXXXXXX
XXXXXX
XXXXXXX
XXXXXX
XXXXXX
BBBBBBBB
