BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBB
BBBB BBBBBBBBBBB

BBBBB BBBBBBBBBB
XXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX X
    XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
  X

  XX XXXXXXXXXX XXXXXXXXXX XX
  XXXXXXXXXXXXXX X
    XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXXXX
    XXXXXXXXX XXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXX XXX
  X

  XXXXXXXXXX X
    XXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXX XXXX XXXX XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXX XXXX XXXX XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXX XXXXX
    XXXXXXXXX XXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXX XXX
    XXXXXXXX XXXX
    XXXXXXXXXX XXXXXXXX XXX XXXXXX XXXXXXXXX
  X

  XXXXXXXXXX XXXXXXXX X
    XX X XXXXXXXXXX XXXXXXXXXXXX XXX X
    XXXX X XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX X
  X

  XX XXXXXXXX XXXXXXXXX XX
  XXXXXXXXXX X
    XXXXXXXXX XXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXX XXX
    XXXXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXX XXXX
    XXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXX XXXXX X
    XXX XXXX X XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX X
    XXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XX X
  X

  XX XXXXXXXXXX XXXXX XX
  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XXXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXX XXXX XXXXX XXXXXXXXXXXXX
    XXXXXXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXX
      X XXXX XXXX XXXXXXXXX XXX XXXX XXXXX
      X X XXXX XXXXXXXXX XXX XXXX XXXXX
      XXXXX X XXX X XXXXXXXXX XXXX XXXX XXXXX
  X

  XX XXXXXXX XXXXX X XXXXXXX XXX XXXXXXXXXXX XX
  XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
    XXXXXXX XXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXX
      X XXXX XXXX XXXXXXX XX XX XXXXX
      X X XXXX XXXXXXXXX XXX XXXX XXXXX
  X

  XX XXXXXXXXXXX XXXXXXXX XX
  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXX XXXXX XXXXXXXXX XXX XXXX XXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXX XXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XXXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
    XXXXXXXXXXX XXXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXX XXXXX XXXXXXXXX XXX XXXX XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX XXX XXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
  X

  XX XXXXXXXXXX XXXXXX XX
  XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XX
    XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
    XXXXXXXX XXX
  X

  XX XXXXXXX XXXX XX
  XXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX
      X X XXXX XXXXXXXXX XXX XXXX XXXXX
      X X XXXX XXXXXXXXX XXX XXXX XXXXX
      X X XXXX XXXXXXXXX XXX XXXX XXXXX
  X

  XX XXXXXX XXXXXXXXXX XX
  XXXXXXXXXXXXXXXXX X
    XXXXXX XXXX
    XXXXXXX XXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXXX XXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXXX XXX XXX XXXXX
  X

  XXXXXXXXXX XXXXX X
    XXX XXXX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXX X
    XXX X XXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXX X
  X

  XX XXXXXX XXXXXXXXX XX
  XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXX XXXXXX XXXXXXXXX XXX XXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXX
  X

  XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXXX XXX XXXX XXXXX
  X

  XX XXXX XXXXXX XXX XXXXXXX XXXXX XX
  XXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXX
  X

  XX XXXXXXXXXX XXXXXX XX
  XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXX XXXX
    X

    XXXXXXXXXXXXX X
      XXXXXXXX XXXXX
    X
  X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX X XXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXX XXXXXX XXXX XXXXX XXXXXX XXXXX XXXXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXX XXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXX XXXXXX X XXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXX XXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXX XXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXX XXXXXX
  XXXX XXXXXXXXXX XXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXX
             gettext(u'Vehicle Fleet') 
          XXXXX
          XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Advanced vehicle management system') XXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'System Online') XXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXX XXXXXXXX XXX
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXX

XXXXXXXX
XX XXXXXXXX XXXXXXXX XXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXX X
  XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXX X XXX

  XXX XXXX X X XX X X XXXXXXXXXXXXXX XXXX X
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXX X XXXX
    XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXX X XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X X X XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X X X XX X XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X
X

XX XXXXXXXXXX XXXXXXXXX XX XXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
  XXXXXXXXXXXXXXXXXX

  XX XXX XXXXXXXXXXX XXXXXXX XX XXXXXXX XXXXX
  XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX XXXXXXXXXX
    XXX
  XXX
XXX
XXXXXXXXX
BBBBBBBB
