BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXX XXXXXXXXXX XXX
  XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX

  XXXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXX XXXX XXXXXX

    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
           gettext(u'Editar Vehículo') 
        XXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX
            XXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXXXXXXBBBBBX
            XXXXXXXXXXXXXXXXXX
        BBBBBBBBBB

        XXXX XXXXXXXXXXX XXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
               gettext(u'Información del Cliente') 
            XXXXX

            XXXX XXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                 gettext(u'Cliente')  X
              XXXXXXXX
              BBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBB BBBB BBBB BBBBBBBBBB BBBBBBBB BBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
              BB BBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
              BBBBB
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
               gettext(u'Datos del Vehículo') 
            XXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
              XXXX XXXXXXX XXXXX XXXX XXXXXX XXXXXX XXX
              XXXXX
                XXXX XXX XXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                   gettext(u'Año')  X
                XXXXXXXX
                BBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBB BBBB BBBB BBBBBBBBBB BBBBBBBB BBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                BBBBB
              XXXXXX

              XXXXX
                XXXX XXXXX XXX
                XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                   gettext(u'Marca')  X
                XXXXXXXX
                BBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBB BBBB BBBB BBBBBBBBBB BBBBBBBB BBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                BBBBB
              XXXXXX

              XXXXX
                XXXX XXXXXX XXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                   gettext(u'Modelo')  X
                XXXXXXXX
                BBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBB BBBB BBBB BBBBBBBBBB BBBBBBBB BBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                BBBBB
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX
              XXXX XXXXXXX XXX
              XXXXX
                XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                   gettext(u'Patente')  X
                XXXXXXXX
                BBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBB BBBB BBBB BBBBBBBBBB BBBBBBBB BBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                BBBBB
              XXXXXX

              XXXX XXXXX XXX
              XXXXX
                XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                   gettext(u'Color') 
                XXXXXXXX
                BBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBB BBBB BBBB BBBBBBBBBB BBBBBBBB BBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                BBBBB
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX
              XXXX XXX XXX
              XXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                   gettext(u'VIN') 
                XXXXXXXX
                BBBBBBBBBBBB BBBBBBBB BBBBBBBBBBBBB BBBB BBBB BBBBBBBBBB BBBBBBBB BBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                BBBBB
              XXXXXX

              XXXX XXXXX XXX
              BB BBBBBBBBBB
              XXXXX
                XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                   gettext(u'Motor') 
                XXXXXXXX
                BBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBB BBBB BBBB BBBBBBBBBB BBBBBBBB BBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                BBBBB
              XXXXXX
              BBBBB
            XXXXXX

            XXXX XXXX XX XXXXXXX XXX
            BB BBBBBBBBB
            XXXX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                 gettext(u'Caja de Cambios') 
              XXXXXXXX
              BBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBB BBBB BBBB BBBBBBBBBB BBBBBBBB BBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
              BB BBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
              BBBBB
            XXXXXX
            BBBBB
          XXXXXX
        XXXXXX

        XXXX XXXXXXX XXX XXXXXXXXXX XXX
        BB BBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXX
                
              XXXXXX
            XXXXXX
          XXXXXX
        BBBBB

        XXXX XXXXXXX XX XXXXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXX
          XX XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXBBBBBX
             XXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX gettext(u'Cancelar') XXXXXXX
          XXXX

          XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX gettext(u'Actualizar Vehículo') XXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
        XXXXXX
      XXXXXXX
    XXXXXX

    XXXX XXXXXX XXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
         gettext(u"Modifica los datos del vehículo y haz clic en 'Actualizar Vehículo' para guardar los cambios.") 
      XXXX
    XXXXXX

  XXXXXX
XXXXXX

XXXX XXXXXXXXX XXXXXX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
  XX XXXXXX XXXXXX XXXX XXXXXXXXX XXX XX XXXXXX XXXXXX
  XXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
      XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXXXXX
    XXX
  X
XXX
XXXXXXXXX
BBBBBBBB
