BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBB
XXXXXXX
    XX XXXXXXXXX XXX XXXX XXXXXXXXX XX
    XXXXX X
        XXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXX
    X

    XXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
        XXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX
        XXXXXXXXXXX XXXXXX
    X

    XX XXXXXX XXXXXXXXX XX
    XXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXX XXX XXXXXXXXX XXX XXXX XXXX XXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX X X XXXX XXXXXXX XXXX XXXX XXXXX
        XXXXXXXXX XXXXXXXXX
        XXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXX
        XXXXXXXXX XXXXXXXXX
        XXXX XX
        XXXXX XXXXXX
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
        XXXXXXXXXX XXXX XX XXXXXXXXX
    X

    XXXXXXXXXX XXXX X
        XX X XXXXX XXXXXX X
        XXXX X XXXXX XXXXX X
    X

    XXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXX XXXX
        XXXXXXXXXX XXXXXXX
    X

    XX XXXXXXXXXX XXXXXXXXX XX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX X X XXXX XXXXXXXX XXXX XXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX
    X

    XXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXX
        XXXXXXXXXXXX XXXX
    X

    XXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXX XXXX
    X

    XXXXXXXXXXXXX XXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX XX XX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
    X

    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X X XXXX XXXXXXXX XXXX XXX XXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXX XXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXX XXXXX
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXX XXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXXX XXXXX
    X

    XXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXXX XXXX XXXXXXXX XXXX XXX XXXXX
        XXXXXXX XXXXXXXXXXXXXXXX
    X

    XX XXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXX X X XXXX XXXXXXXXX XXX XXXX XXXXX
    X

    XXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXX
    X

    XXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXX
        XXXXXXXX XXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXX
    X

    XX XXXXX XXXXXXXXX XX
    XXXXXXXXXXXX X
        XXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXX XXXXX
    X

    XXXXXXXXXXXX XX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXX XXXX
    X

    XXXXXXXXXXXX XX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXX XXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXXX XXX XXXXX
        XXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
    X

    XX XXXXX XXXX XXXXX XX XXXXXXXXX XX
    XXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXX
        XXXXXXXXXXX XXXXX
    X

    XXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX XX XX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXX XXXXXXXX
    X

    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X X XXXX XXXXXXXX XXXX XXX XXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXX X
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
    X

    XXXXXXXXXX X
        XXXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXX
    X

    XX XXXXXXX XX XXXXXXXXXX XX
    XXXXXXXXXXXXX X
        XXXXXXXXX XXXXXX
        XXXX XX
        XXXXX XX
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXX XXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
                    XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXX XXXX XXXX XXX XXXXXXXXXXX XXXXX
                    XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXX XXXX XXX XXXX XXX XXXXXXXXXXX XXXXX
    X

    XX XXXXXXXXXX XX
    XXXXXX XXXXXXXXXXX XXXXXX X
        XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXX XXXX
        X

        XXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
        X

        XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        X
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX
    XXXX XXXXXXXX XXXXXX X XXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX
        XXXX XXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXX XXXXXXXXXXXXXXXXBBBBBXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXX XXXXXXXXXXXXXXXBBBBBXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXX XXXXXXX XXX
            XXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXX  gettext(u'Reports by Date') XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Unified temporal analysis system with intelligent filters') XXXX
            XXXXXX

            XXXX XXXXXXXXXX XXXX XXX
            XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Operations Center') XXXXXXX
                XXXX

                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Vehicles') XXXXXXX
                XXXX

                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Clients') XXXXXXX
                XXXX

                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Documents') XXXXXXX
                XXXX

                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Reports') XXXXXXX
                XXXX

                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Settings') XXXXXXX
                XXXX

                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Parts') XXXXXXX
                XXXX

                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Services') XXXXXXX
                XXXX

                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Other Services') XXXXXXX
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Reports by Date') XXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Unified temporal analysis system with intelligent filters') XXXX
    XXXXXX

    XXXX XXXXXXXXXX XX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XX XXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXX XXXXX XXX XXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXBBBBBXX XXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBBBBXXXXXXXXBBBBBXX XXXXXXX XX XXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBXXX XXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBXXX XXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBBBBXXXXXXXXBBBBBXX XXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXXX
    XXXXXX

    BB BBBBBBBBBB BB BBB BBBB
    XXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX

        BB BBBBBBBBBB
        XXXX XXXXXXX XXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXX
            BBB BBBBB BBBBB BB BBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            BBBBBB
        XXXXXX

        XXXX XXXXX XX XXXXXXXXXX XXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX
                XXXX
                    XXXXX XXXXXXXXXXX
                    XXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXX
                    XXXXX XXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXX
                    XXXXX XXXXXXXXXX
                    XXXXX XXXXXXXXXXXXX
                XXXXX
            XXXXXXXX
            XXXXXXX
                BBB BBB BB BBBBBBBBBB
                XXXX
                    XXXXFFFFFFFFFFFF FFFFFFFXXXXX
                    XXXX
                        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                    XXXXFFFFFFFFFFFFXXXXX
                    XXXX FFFFFFFFFFXXXXX
                    XXXXFFFFFFFFFFFF FFFFFFFFXXXXX
                    XXXX
                        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                            XFFFFFFFFFFFFFFFFFFFFFFFF
                        XXXXXXX
                    XXXXX
                    XXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBX
                           XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
                            XX XXX
                        XXXX
                    XXXXX
                XXXXX
                BBBBBB
            XXXXXXXX
        XXXXXXXX

        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXX XXXX XXX XXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXX
                    XFFFFFFFFFFFFF
                XXXXXXX
            XXXXXX
        XXXXXX

        BBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXX XXX XXXXXXXXX XX XX XXXXX XX XXXXXX XXXXXXXXXXXXXXXX
        XXXXXX
        BBBBB
    XXXXXX
    BBBBB

    XXXX XXXXXXXXXXX XXXXXXXXX XXX
    BB BBB BBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXX XXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX
        XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXX XX XXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XX XXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    BBBBB
XXXXXX

XXXXXXXX
XX XXXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XX XXXXXX XX XXXXXX XXXX XX XXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXX X XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX X XXX
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXX X X XX
        XXXXXXXX XXXXXXXXXXXX X
            XX XX X XXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX
                XXXX
                XXXXXXXXXXXXXXXXXXXXXX XXXXX
            X
        X
        XXXXXXXXXXXXXXXXXXXXXX XXXXX
    X

    XX XXXXXXXXX XX XXX XXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXX XX X
        XXXXXXXXXXXXXXXXXX X XXXX
        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXX X XXXX XXXX XXXXXX
            XXXXXXXXXXXXXXXXXX X XXXX
            XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
        XX XXXXX X XXXXX
    XXX
XXX
XXXXXXXXX
BBBBBBBB
